### ISSUE TITLE
output_errors

### ISSUE THREAD

**Issue by exoglycerin** [MontrealCorpusTools/Montreal-Forced-Aligner#107]
Attempting to align five audio files in an endangered language. Only two of my recordings output .TextGrid files. The other three kick some errors into an output_errors.txt file. 

############################################################################
The following exceptions were encountered during the ouput of the alignments to TextGrids:

RJ_01:
Traceback (most recent call last):

  File "aligner/textgrid.py", line 100, in ctm_to_textgrid

KeyError: 'RJ_01'

AJ_01:
Traceback (most recent call last):

  File "aligner/textgrid.py", line 100, in ctm_to_textgrid

KeyError: 'AJ_01'

MP_01:
Traceback (most recent call last):

  File "aligner/textgrid.py", line 100, in ctm_to_textgrid

KeyError: 'MP_01'
###############################################################################

I have inspected the input .TextGrid files, comparing those that kick this error with those that successfully output and cannot for the life of me find any difference. 

Any help would be appreciated.

Thanks.

**Comment by exoglycerin** [comment]
I just ran the same training data on an earlier version (prob. 1.0. It's hard to tell what version). These did not throw the same errors. I am not sure if this is helpful, but I thought I would check.

**Comment by exoglycerin** [comment]
I have finally noticed that it is only stereo WAV files that are having the above problem. It seems that the corpus.py file creates two objects for such files, e.g. some_audio_A.wav, some_audio_B.wav. This then seems to cause problems when writing the TextGrid output. Whenever a multichannel file is to be output, it looks for the filename (i.e. lacking the _A and _B tags) in the corpus without success. 

The precise point is in aligner/textgrid.py, line 100.

speaker_directory = os.path.join(out_directory, corpus.file_directory_mapping[filename])

This throws the KeyError error, because there is no file for the file itself.

**Comment by zkokaja** [comment]
Thanks for narrowing down the problem for me. My issue was that it threw a `TypeError` when trying the `os.path.join` so I added it to the exception list: `except (KeyError, TypeError)` and it bypassed this particular problem.
