### ISSUE TITLE
sre_constants.error: unterminated character set at position 5

### ISSUE THREAD

**Issue by Joee1995** [MontrealCorpusTools/Montreal-Forced-Aligner#108]
I try `bin/mfa_generate_dictionary /path/to/lang_g2p.zip /path/to/corpus /path/to/corpus lang_dict.txt`, and receive an error as follow:

> Setting up corpus information...
set()
Traceback (most recent call last):
  File "aligner\command_line\train_and_align.py", line 171, in <module>
  File "aligner\command_line\train_and_align.py", line 53, in align_corpus
  File "aligner\dictionary.py", line 128, in __init__
  File "aligner\dictionary.py", line 18, in compile_graphemes
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\re.py", line 233, in compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\re.py", line 301, in _compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_compile.py", line 562, in compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 855, in parse
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 416, in _parse_sub
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 765, in _parse
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 416, in _parse_sub
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 523, in _parse
sre_constants.error: unterminated character set at position 5
[11432] Failed to execute script train_and_align

I think I do sth wrong. Thx in advance!

**Comment by Lizzymiz** [comment]
Hi did you find out what was wrong?
I'm getting the same error.
Thanks!

**Comment by mirfan899** [comment]
I'm also getting the same error on Cantonese dataset. Any update?

**Comment by mirfan899** [comment]
@Lizzymiz which language you are using? Most probably it's language issue not supported by MFA.

**Comment by liuyibox** [comment]
I am in the same issue, have anyone got any update on this. I am using python 3.7.3. I am wondering if this is because of the incompatible python versions.

**Comment by ahminn** [comment]
@Joee1995 I think bin/mfa_generate_dictionary accepts 3 arguments, not 4 according to https://arxiv.org/pdf/1811.05553.pdf

**Comment by zgoda** [comment]
I'm getting this error using librispeech lexicon for english and running `mfa_align`.

**Comment by ahminn** [comment]
@zgoda "Aligned TextGrids will overwrite any existing TextGrids (with the same name as the wav files) in the output directory. The aligner will throw an error if the corpus directory is specified as the output directory (to prevent overwriting any input TextGrids)." from https://montreal-forced-aligner.readthedocs.io/en/latest/aligning.html Not sure if this is the error you are facing

**Comment by wwdok** [comment]
Two years later, i met the same issue. The worst thing is that i can not find where is the source code that listing in the Traceback, so i can not debug...
