### ISSUE TITLE
Some TextGrid files not generated despite successful alignment

### ISSUE THREAD

**Issue by thewunneh** [MontrealCorpusTools/Montreal-Forced-Aligner#114]
Hi, thanks for creating MFA!
I've been using version 1.1 to obtain alignments for audiobooks for a while now, and mostly things have been working out. 

Today I tried aligning another audiobook, split into 64 segments, and the aligner reported success for all 64 segments. However, only 61 TextGrid files were generated.

The output_errors file contains the following text (indeed, with 3 files having issues):

> The following exceptions were encountered during the ouput of the alignments to TextGrids:
> 
> PofA_001:
> Traceback (most recent call last):
> 
>   File "aligner\textgrid.py", line 81, in ctm_to_textgrid
> 
>   File "site-packages\textgrid\textgrid.py", line 431, in add
> 
>   File "site-packages\textgrid\textgrid.py", line 189, in __init__
> 
> ValueError: (Decimal('27.850'), Decimal('27.832925170068027'))
> 
> 
> PofA_010:
> Traceback (most recent call last):
> 
>   File "aligner\textgrid.py", line 81, in ctm_to_textgrid
> 
>   File "site-packages\textgrid\textgrid.py", line 431, in add
> 
>   File "site-packages\textgrid\textgrid.py", line 189, in __init__
> 
> ValueError: (Decimal('28.740'), Decimal('28.726530612244897'))
> 
> 
> PofA_025:
> Traceback (most recent call last):
> 
>   File "aligner\textgrid.py", line 81, in ctm_to_textgrid
> 
>   File "site-packages\textgrid\textgrid.py", line 433, in add
> 
>   File "site-packages\textgrid\textgrid.py", line 441, in addInterval
> 
>   File "site-packages\textgrid\textgrid.py", line 208, in __lt__
> 
> ValueError: (Interval(27.460, 27.63501133786848, IY0), Interval(27.630, 27.63501133786848, sp))

Any idea what may be going on within the textgrid.py functions that keep my alignments from getting saved? Any thoughts/pointers would be much appreciated. I'm also happy to share any or all of the audio+text that lead to this issue.

Thanks!
-Juraj

**Comment by balajithoshkahna** [comment]
Hi Juraj,
Im trying a similar problem of having a long audio with pauses with multiple lines of text as the transcription and im trying to align this text to the audio. How are you ensuring that the segments of audio and the segments of text for alignment match? ie. how are you timing the length of the text to match the length of audio segments?Any comments will be helpful in my experiments too.

**Comment by thewunneh** [comment]
Hi Balaji,

to clarify, are you asking how I chop up the audio and text such that each pair of files has corresponding audio + text? If so, the answer is unfortunately that it's all done manually. I created little helper scripts to make the process faster, but ultimately I just cut the audio into ~30 sec chunks (cutting in the silence between words) and then copy-paste each segment's text into its own file. There probably is a simpler/smarter way, but this was the easiest to implement for my purposes.

BTW, I haven't really figured out the original issue I reported here (i.e. I still don't know why some TextGrid files were not generated), but I did come up with a workaround: I simply split the audio+text files that had the issue into two parts, and magically the aligner has no issues with those. 

-Juraj

**Comment by balajithoshkahna** [comment]
Hi Juraj
Thanks for your answer. I faced the same type of problem you have. Try this. Compile from the source, but now in aligner/config/basic_align.yaml increase the beam width from default of 10 and retry of 40 to say default of 100 and retry of 400(Just a setting that allows it to search more in longer files). It helped me from these dropped files a lot(Almost went from 60% dropped files to less than 2%). Hope this suggestion helps.

**Comment by thewunneh** [comment]
Thanks, that's definitely a good suggestion for getting the aligner to work, especially with longer audio+text. However, I am not sure it addresses the exact issue I mentioned in the OP -- the issue here was not that the alignment was failing, but that there was some error during the TextGrid generation. In other words, somehow at the final stage of MFA, textgrid.py is failing to create TextGrid files containing the results of successful alignment. The message that's printed out when MFA finishes is that there were no issues, yet some files are missing. My guess is that this is some kind of bug in / incompatibility with the dependencies of MFA (i.e. textgrid.py).

**Comment by jonorthwash** [comment]
This looks like #63.

**Comment by cesarmak** [comment]
Had the same issue, with a thousand of audio files of ~1min, each transcripted. 

The test results were interesteing:
1) All 1000 input files in a single folder -> Total 950 output Textgrids
2) Create 20 subfolders, and each contains 50 files -> only 11 subfolders at output; total only 530 Textgrids. 

Repeated the tests above, and this behaviour seems consistent. Any thoughts?
Thanks for the effort!

**Comment by JRMeyer** [comment]
@cesarmak -- did you solve this problem?

**Comment by carankt** [comment]
I was facing the same issue, in my case, I realized it was because a few filenames.wav and filenames.lab contained space in the beginning and in between the file name. Maybe renaming the file can help.

**Comment by cesarmak** [comment]
> @cesarmak -- did you solve this problem?

i manually split my files into 30sec segments, and **most** of the files had outputs generated. 

No luck with the multiple-subfolder approach; tried only every input file within one subfolder
