### ISSUE TITLE
Building from source.  FileNotFoundError: [Errno 2] No such file or directory: '/home/nmj/MFA_all/1.1.0/Montreal-Forced-Aligner-1.1.0-beta.2/dist/train_and_align'

### ISSUE THREAD

**Issue by rosa1122** [MontrealCorpusTools/Montreal-Forced-Aligner#136]
586163 INFO: Building EXE from EXE-04.toc completed successfully.
586177 INFO: checking COLLECT
586177 INFO: Building COLLECT because COLLECT-04.toc is non existent
586178 INFO: Building COLLECT COLLECT-04.toc
589024 INFO: Building COLLECT COLLECT-04.toc completed successfully.
Traceback (most recent call last):
  File "/home/nmj/anaconda3/lib/python3.7/shutil.py", line 557, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nmj/MFA_all/1.1.0/Montreal-Forced-Aligner-1.1.0-beta.2/dist/train_and_align' -> '/home/nmj/MFA_all/1.1.0/Montreal-Forced-Aligner-1.1.0-beta.2/dist/montreal-forced-aligner/lib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "freeze.py", line 58, in <module>
    shutil.move(orig_dir, lib_dir)
  File "/home/nmj/anaconda3/lib/python3.7/shutil.py", line 571, in move
    copy_function(src, real_dst)
  File "/home/nmj/anaconda3/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/nmj/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nmj/MFA_all/1.1.0/Montreal-Forced-Aligner-1.1.0-beta.2/dist/train_and_align'

**Comment by rosa1122** [comment]
My fault. I already know.
I forgot to read thirdparty/READ.ME

**Comment by iroh7** [comment]
Hi! I've still the error however I've completed the thirdparty/README.md installation.
Did you solve it ?
