### ISSUE TITLE
Stuck with MFA-Validator Error: TypeError: expect bytes or str, not NoneType """

### ISSUE THREAD

**Issue by penkesiva** [MontrealCorpusTools/Montreal-Forced-Aligner#138]
Any comments regarding this would be of great help. Cheers!

`bin/mfa_align -v /tmp  ../../../Dict/english/librispeech-lexicon.txt pretrained_models/english.zip /mfa-out
align.py:92: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
/home/siva.penke/workarea/Projects/2019/visemenet-mps/Montreal-Forced-Aligner/dist/montreal-forced-aligner/lib/aligner/models.py:107: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
/home/siva.penke/workarea/Projects/2019/visemenet-mps/Montreal-Forced-Aligner/dist/montreal-forced-aligner/lib/aligner/config/__init__.py:124: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing/pool.py", line 119, in worker
  File "aligner/features/processing.py", line 32, in mfcc_func
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1474, in _execute_child
  File "os.py", line 862, in fsencode
TypeError: expect bytes or str, not NoneType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 129, in align_corpus
  File "aligner/aligner/pretrained.py", line 61, in __init__
  File "aligner/aligner/base.py", line 50, in __init__
  File "aligner/aligner/pretrained.py", line 79, in setup
  File "aligner/aligner/base.py", line 55, in setup
  File "aligner/features/config.py", line 153, in generate_features
  File "aligner/features/config.py", line 140, in generate_base_features
  File "aligner/features/processing.py", line 83, in mfcc
  File "aligner/features/processing.py", line 83, in <listcomp>
  File "multiprocessing/pool.py", line 608, in get
TypeError: expect bytes or str, not NoneType
[11673] Failed to execute script align
`

**Comment by penkesiva** [comment]
Solved it. In case anyone faces this issue, here is how I solved it.

sudo apt-get install libatlas3-base
and use 1.1.0 Beta version of MFA
and use the following command
./bin/mfa_align ../data/Librispeech/ ../data/dict/english/librispeech-lexicon.txt english ../results/mfa/
#the dataset should only contain .wav and .lab or .txt files and nothing else
