### ISSUE TITLE
mfa_train_and_align not working on VCTK data

### ISSUE THREAD

**Issue by michael1b** [MontrealCorpusTools/Montreal-Forced-Aligner#145]
I have `MFA Version 1.1.0 Beta 2` set up in my `Ubuntu 18.04` machine. (I tried the `MFA Version 1.0.1` first but I get the error described in issue #91 )

I was successful in trying the demo for the `bin/mfa_train_and_align` using a subset of the `librispeech` data (although I had to fix the lexicon first because there were some missing words):

--> here's the command
```
bin/mfa_train_and_align ~/Documents/spr25-issue137-dataprep/data/librispeech/egs/dataset/ ~/Documents/spr25-issue137-dataprep/model/lexicon/eng-lexicon_librispeech-updated.txt ~/Documents/spr25-issue137-dataprep/data/librispeech/egs/aligned2/
```

--> corresponding log
```
Setting up corpus information...
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Initializing training for mono...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [03:49<00:00,  5.89s/it]
Initializing training for tri...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:46<00:00,  1.37s/it]
Initializing training for lda...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initializing training for lda...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initialization complete!
Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [02:05<00:00,  3.69s/it]
Initializing training for sat1...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initializing speaker-adapted triphone training...
Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:59<00:00,  1.75s/it]
Initializing training for sat2...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initializing speaker-adapted triphone training...
Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [05:53<00:00, 10.40s/it]
```

However, when I used the same process with a different dataset -- specifically the one from `VCTK`, I get an error

--> here's the command
```
bin/mfa_train_and_align ~/Documents/spr25-issue137-dataprep/data/vctk/p225-wav-16kHz/ ~/Documents/spr25-issue137-dataprep/model/lexicon/eng-lexicon_librispeech-updated.txt ~/Documents/spr25-issue137-dataprep/data/vctk/aligned/
```

--> here's the corresponding error
```
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 131, in <module>
  File "aligner/command_line/train_and_align.py", line 56, in align_corpus
  File "aligner/dictionary.py", line 153, in __init__
aligner.exceptions.DictionaryFileError: The specified path for the dictionary (No words were found in the dictionary path /home/michael1b/Documents/spr25-issue137-dataprep/model/lexicon/eng-lexicon_librispeech-updated.txt) is not a file.
[22502] Failed to execute script train_and_align
```

Not sure why it was referring to the lexicon for the error when the same file worked with the `librispeech` demo. I'm trying to figure out why it's not working, so any help will be much appreciated. Thank you!

Some notes
* I transformed the `VCTK` data from FLAC format, 24 kHz to WAV format, 16 kHz
* `vctk/p225-wav-16kHz/` contains two folders of data (wav and lab), similar to the librispeech demo (has three subfolders in `egs/dataset`)

**Comment by michael1b** [comment]
UPDATE

I ran `mfa_validate_dataset` to see what's wrong with the transformed `VCTK` data

--> here's the command
```
bin/mfa_validate_dataset ~/Documents/spr25-issue137-dataprep/data/vctk/dataset/ ~/Documents/spr25-issue137-dataprep/model/lexicon/eng-lexicon_librispeech-updated.txt
```

--> here's the corresponding log
```
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/validate_dataset.py", line 78, in <module>
  File "aligner/command_line/validate_dataset.py", line 30, in validate_corpus
  File "aligner/dictionary.py", line 153, in __init__
aligner.exceptions.DictionaryFileError: The specified path for the dictionary (No words were found in the dictionary path /home/michael1b/Documents/spr25-issue137-dataprep/model/lexicon/eng-lexicon_librispeech-updated.txt) is not a file.
[23562] Failed to execute script validate_dataset
```

I ran the same command, but this time with the `librispeech` demo in the same directory as my transformed `VCTK` data, and I got the following log:

```
Setting up corpus information...
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...

    =========================================Corpus=========================================
    0 sound files
    367 sound files .lab transcription files
    0 sound files with TextGrids transcription files
    0 additional sound files ignored (see below)
    3 speakers
    367 utterances
    4217.890 seconds total duration
    
    DICTIONARY
    ----------
    There were no missing words from the dictionary. If you plan on using the a model trained on this dataset to align other datasets in the future, it is recommended that there be at least some missing words.
    
    SOUND FILE READ ERRORS
    ----------------------
    There were 462 sound files that could not be read. Please see /home/michael1b/Documents/MFA/dataset/corpus_data/wav_read_errors.csv for a list.
    
    FEATURE CALCULATION
    -------------------
    There were no utterances missing features.
    
    FILES WITHOUT TRANSCRIPTIONS
    ----------------------------
    There were no sound files missing transcriptions.
    
    TRANSCRIPTIONS WITHOUT FILES
    --------------------
    There were no transcription files missing sound files.
      
    TEXTGRID READ ERRORS
    --------------------
    There were no issues reading TextGrids.
    
    UNREADABLE TEXT FILES
    --------------------
    There were no issues reading text files.
    
    UNSUPPORTED SAMPLE RATES
    --------------------
    There were no sound files with unsupported sample rates.
    
Initializing training for mono...
.
.
.
```
The `462 sound files` that cannot be read by `MFA` are the recordings from the transformed `VCTK` data -- so it looks like the problem isn't really the lexicon

I converted the `VCTK` data via `sox` though, specifically using this command:

`sox <file.flac> -G -b 32 -c 1 -r 16k <file.wav>`

Still checking for alternative ways to do the conversion.

**Comment by michael1b** [comment]
UPDATE:

Looks like it has something to do with how I converted the `VCTK` data via `sox`

Instead of
```
sox <file.flac> -G -b 32 -c 1 -r 16k <file.wav>
```
I did this
```
sox <file.flac> -G -r 16k <file.wav>
```

Log below shows the successful run of `mfa_validate_dataset`
```
Setting up corpus information...
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...

    =========================================Corpus=========================================
    0 sound files
    462 sound files .lab transcription files
    0 sound files with TextGrids transcription files
    0 additional sound files ignored (see below)
    1 speakers
    462 utterances
    1634.980 seconds total duration
    
    DICTIONARY
    ----------
    There were 4 word types not found in the dictionary with a total of 14 instances. Please see /home/michael1b/Documents/MFA/dataset/corpus_data/oovs_found.txt for a full list of the word types and /home/michael1b/Documents/MFA/dataset/corpus_data/utterance_oovs.txt for a by-utterance breakdown of missing words.
    
    SOUND FILE READ ERRORS
    ----------------------
    There were no sound files that could not be read.
    
    FEATURE CALCULATION
    -------------------
    There were no utterances missing features.
    
    FILES WITHOUT TRANSCRIPTIONS
    ----------------------------
    There were no sound files missing transcriptions.
    
    TRANSCRIPTIONS WITHOUT FILES
    --------------------
    There were no transcription files missing sound files.
      
    TEXTGRID READ ERRORS
    --------------------
    There were no issues reading TextGrids.
    
    UNREADABLE TEXT FILES
    --------------------
    There were no issues reading text files.
    
    UNSUPPORTED SAMPLE RATES
    --------------------
    There were no sound files with unsupported sample rates.
    
Initializing training for mono...
Initialization complete!
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [02:10<00:00,  3.36s/it]

    =======================================Alignment========================================
    All 462 were successfully aligned!
```

and of `mfa_align`
```
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 462.0
Creating dictionary information...
Done with setup.

Done! Everything took 15.477418899536133 seconds
```

Still need to figure out why that is the error -- I was able to read and play the first version of the  transformed data using other platforms (e.g. Audacity).

**Comment by bonafonte** [comment]
Hi. Happy it is already solved. I don't now what formats are supported by the aligner, but the option -b32 is not the most standard (32 bits per sample). The most standar one is -b16.  If you are curious about the final files, you can run soxi -b yourfilename.wav

**Comment by michael1b** [comment]
Ah yes, the files generated by mfa uses 16 bits. I'll close the issue now. Thanks
