### ISSUE TITLE
aligner.exceptions.ArgumentError: The specified corpus directory (vietnamese_g2p.zip) is not a directory. [30042] Failed to execute script generate_dictionary

### ISSUE THREAD

**Issue by chaoticz044** [MontrealCorpusTools/Montreal-Forced-Aligner#147]
Hi, I'm new in forced alignment. I want to generate a phoneme level transcription from a vietnamese transcript and followed the installation instructions. I use version 1.0.1.  I downloaded the G2P model and placed it outside the _pretrained_models_ folder and I tried following the tutorial and run the command:

 `bin/mfa_generate_dictionary vietnamese_g2p.zip transcript.txt output.txt`

and got an error message saying that:

```
Traceback (most recent call last):
  File "aligner/command_line/generate_dictionary.py", line 55, in <module>
  File "aligner/command_line/generate_dictionary.py", line 38, in validate
aligner.exceptions.ArgumentError: The specified corpus directory (vietnamese_g2p.zip) is not a directory.
[30042] Failed to execute script generate_dictionary
```
I tried the running:

 `bin/mfa_generate_dictionary vietnamese_g2p transcript.txt output.txt`

but also encountered an error saying

```
Traceback (most recent call last):
  File "aligner/command_line/generate_dictionary.py", line 55, in <module>
  File "aligner/command_line/generate_dictionary.py", line 31, in validate
aligner.exceptions.ArgumentError: Could not find the G2P model file vietnamese_g2p.
[30031] Failed to execute script generate_dictionary
```

**Comment by RostyslavBryiovskyi** [comment]
Hi, @chaoticz044 
I advice you this version https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/tag/v1.1.0-beta.2
Have a nice day!)
