### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by JackSCJackson** [MontrealCorpusTools/Montreal-Forced-Aligner#155]
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 140, in validate_args
  File "aligner/command_line/align.py", line 135, in align_included_model
  File "aligner/command_line/align.py", line 85, in align_corpus
  File "aligner/corpus.py", line 543, in speaker_utterance_info
ZeroDivisionError: division by zero
[32671] Failed to execute script align

**Comment by JackSCJackson** [comment]
Mac kept pushing wav file to cloud storage mid-work. Check your files are local, Finder can be trashy.
