### ISSUE TITLE
mfcc/raw_mfcc.0.scp can't find,but it is in the upper directory,how should I modify it?

### ISSUE THREAD

**Issue by c9412600** [MontrealCorpusTools/Montreal-Forced-Aligner#160]
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 171, in <module>
  File "aligner/command_line/train_and_align.py", line 67, in align_corpus
  File "aligner/aligner/base.py", line 85, in __init__
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: 'examples/aligned_output/CH/train/mfcc/raw_mfcc.0.scp'
but file of raw_mfcc.0.scp is in examples/aligned_output/CH/train/mfcc/config/raw_mfcc.0.scp

**Comment by c9412600** [comment]
I changed the v1.1.0 version，but a new error appeared.
No matter if I run bin/mfa_validate_dataset command or bin/mfa_train_and_align command,the following error will appear
Generating base features (mfcc)...
Traceback (most recent call last):
  File "aligner/command_line/validate_dataset.py", line 78, in <module>
I
  File "aligner/command_line/validate_dataset.py", line 34, in validate_corpus
  File "aligner/validator.py", line 183, in __init__
  File "aligner/validator.py", line 191, in setup
  File "aligner/features/config.py", line 153, in generate_features
  File "aligner/features/config.py", line 141, in generate_base_features
  File "aligner/corpus.py", line 817, in combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/kaldi/Documents/MFA/CH/corpus_data/split1/feats.0.scp'

**Comment by c9412600** [comment]
The error details are as follows：


Setting up corpus information...
Creating dictionary information...
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstcompile)
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstarcsort)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstcompile)
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstarcsort)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kaldi/zhchen/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
Setting up corpus_data directory...
Generating base features (mfcc)...
Traceback (most recent call last):
  File "aligner/command_line/validate_dataset.py", line 78, in <module>
  File "aligner/command_line/validate_dataset.py", line 34, in validate_corpus
  File "aligner/validator.py", line 183, in __init__
  File "aligner/validator.py", line 191, in setup
  File "aligner/features/config.py", line 153, in generate_features
  File "aligner/features/config.py", line 141, in generate_base_features
  File "aligner/corpus.py", line 817, in combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/kaldi/Documents/MFA/CH/corpus_data/split1/feats.0.scp'
[37644] Failed to execute script validate_dataset

**Comment by OscarVanL** [comment]
I am having exactly the same error, that `GLIBCXX_3.4.21` is missing and then that `feats.0.scp` can't be found.

It seems to be OS-specific, I have a Red Hat Enterprise Linux Server 7.8 installation where this error happens, then on Ubuntu 18.04 it doesn't happen.

Did you ever find a fix for this?

**Comment by MMingabc** [comment]
installing OpenBLAS solved this problem in my case.
