### ISSUE TITLE
[30191] Failed to execute script train_and_align

### ISSUE THREAD

**Issue by zzw922cn** [MontrealCorpusTools/Montreal-Forced-Aligner#165]
Creating dictionary information...
Using previous MFCCs
Number of speakers in corpus: 1, average number of utterances per speaker: 3014.0
Monophone training already done, using previous final.mdl
Initializing triphone training...
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 169, in <module>
  File "aligner/command_line/train_and_align.py", line 116, in align_corpus_no_dict
  File "aligner/aligner/trainable.py", line 83, in train_tri
  File "aligner/aligner/base.py", line 330, in _init_tri
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alpha/Documents/MFA/dingdangf007_wav_lab_for_MFA/tri/0.occs' -> '/Users/alpha/Documents/MFA/dingdangf007_wav_lab_for_MFA/tri/1.occs'
[30191] Failed to execute script train_and_align

**Comment by RickyL-2000** [comment]
I met the same problem, have you dealt with it?

**Comment by zzw922cn** [comment]
Not yet, I have not triedMFA since then...

**Comment by latheeshvm** [comment]
Facing the same issue
