### ISSUE TITLE
mfa-align error

### ISSUE THREAD

**Issue by mataym** [MontrealCorpusTools/Montreal-Forced-Aligner#168]
when i want to alighn with mfa-align script, i have an error. the script  with paremeter and error info  as follows:
bin/mfa_align   ./corpus ./lexicon/dict.txt ./pretrained_models/g2p_model.zip ./myparsed  
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 2158.0
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 120, in align_corpus
  File "aligner/models.py", line 148, in validate
  File "aligner/models.py", line 108, in meta
KeyError: 'features'
[6814] Failed to execute script align
how to solve this problem?

**Comment by carankt** [comment]
For aligning, I believe there is a mistake in the cmd used to run MFA. You should rather use something like this 
`bin/mfa_align ./corpus ./lexicon/dict.txt ./pretrained_models/english.zip ./myparsed`

instead of passing the g2p_model.zip pass the pre-trained model of the language you want to align. 

hopefully, it should solve your error
