### ISSUE TITLE
German model + German lexicon: no words found in the dictionary

### ISSUE THREAD

**Issue by zgoda** [MontrealCorpusTools/Montreal-Forced-Aligner#174]
I'm trying to use German model (Prosodylab) with Prosodylab dictionary but I keep getting dictionary errors:

```
$ bin/mfa_validate_dataset /home/jarek/tmp/german /home/jarek/tmp/mfa/lexicon/german.txt german
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/validate_dataset.py", line 78, in <module>
  File "aligner/command_line/validate_dataset.py", line 30, in validate_corpus
  File "aligner/dictionary.py", line 153, in __init__
aligner.exceptions.DictionaryFileError: The specified path for the dictionary (No words were found in the dictionary path /home/jarek/tmp/mfa/lexicon/german.txt) is not a file.
[35443] Failed to execute script validate_dataset
```

The lexicon file is there and definitely has the content exactly as in Prosodylab repo. Corpus contains one WAV file dowscaled with sox to 16 bit:

```
$ ls -l /home/jarek/tmp/german/
razem 860
-rw-rw-r-- 1 jarek jarek      9 wrz  7 15:07 out.lab
-rw-rw-r-- 1 jarek jarek 873644 wrz  7 15:06 out.wav
$ file /home/jarek/tmp/german/out.wav 
/home/jarek/tmp/german/out.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 96000 Hz
```

Providing full path to model zip file does not change anything.

This is 1.1.0-B2, how do I use this thing with German data?

**Comment by zgoda** [comment]
Generated dictionary using g2p model and it works so far.
