### ISSUE TITLE
have anyone meet the same error?

### ISSUE THREAD

**Issue by freenowill** [MontrealCorpusTools/Montreal-Forced-Aligner#175]
Initializing training for sat1...
Initializing speaker-adapted triphone training...
Initialization complete!
  0%|                                                                  | 0/34 [00:00<?, ?it/s]Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 131, in <module>
  File "aligner/command_line/train_and_align.py", line 70, in align_corpus
  File "aligner/aligner/trainable.py", line 81, in train
  File "aligner/trainers/sat.py", line 122, in train
Exception: There was an error training in iteration 1, please check the logs.
[13645] Failed to execute script train_and_align

**Comment by Jackson-Kang** [comment]
Hi, @freenowill.

I got same error, a minutes ago.

Did you got the answer?

**Comment by freenowill** [comment]
> Hi, @freenowill.
> 
> I got same error, a minutes ago.
> 
> Did you got the answer?

My solution is using my own train_config.yaml and I didn't do the step of speaker-adapted.

**Comment by Jackson-Kang** [comment]
Thank you for sharing your experiences.

My solution is editing and rebuilding the source from github.

In my case, the problem was from unsupported codec.
I changed wav format using ffmpeg, and it finally worked.

Hope that this information are helpful.
Thank you!

**Comment by romadomaa** [comment]
> Thank you for sharing your experiences.
> 
> My solution is editing and rebuilding the source from github.
> 
> In my case, the problem was from unsupported codec.
> I changed wav format using ffmpeg, and it finally worked.
> 
> Hope that this information are helpful.
> Thank you!

hi!

which version you rebuilding??
i have one question...

**Comment by AnitaLiu98** [comment]
same question, any solution?

**Comment by Charlottecuc** [comment]
Same question, any solution?
