### ISSUE TITLE
about v2.0.0

### ISSUE THREAD

**Issue by Ithrael** [MontrealCorpusTools/Montreal-Forced-Aligner#196]
I install MFA by  python setup.py install, and I exec `mfa align align_input/ pretrained_models/english_dictionary.txt pretrained_models/english.zip out_textgrid/` 

![image](https://user-images.githubusercontent.com/38208715/102688870-d7221600-4234-11eb-9e1c-00ad489e2273.png)

`Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
Creating dictionary information...
Traceback (most recent call last):
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/bin/mfa", line 33, in <module>
    sys.exit(load_entry_point('Montreal-Forced-Aligner==2.0.0a1', 'console_scripts', 'mfa')())
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/mfa.py", line 226, in main
    run_align_corpus(args, acoustic_languages)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/align.py", line 139, in run_align_corpus
    align_corpus(args)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/align.py", line 80, in align_corpus
    a = PretrainedAligner(corpus, dictionary, acoustic_model, align_config,
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/pretrained.py", line 55, in __init__
    super(PretrainedAligner, self).__init__(corpus, dictionary, align_config, temp_directory,
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/base.py", line 40, in __init__
    self.setup()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/pretrained.py", line 74, in setup
    super(PretrainedAligner, self).setup()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/base.py", line 43, in setup
    self.dictionary.write()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/dictionary.py", line 485, in write
    self._write_fst_binary(disambig=disambig)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/dictionary.py", line 708, in _write_fst_binary
    subprocess.call([thirdparty_binary('fstcompile'), '--isymbols={}'.format(phones_file_path),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/bin/../lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by Ithrael** [comment]
The env is  Macos python3.8.1   
there are two file 8.lab and 8.wav in dir align_input

**Comment by Ithrael** [comment]
`Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
Creating dictionary information...
Traceback (most recent call last):
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/bin/mfa", line 33, in <module>
    sys.exit(load_entry_point('Montreal-Forced-Aligner==2.0.0a1', 'console_scripts', 'mfa')())
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/mfa.py", line 226, in main
    run_align_corpus(args, acoustic_languages)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/align.py", line 139, in run_align_corpus
    align_corpus(args)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/command_line/align.py", line 80, in align_corpus
    a = PretrainedAligner(corpus, dictionary, acoustic_model, align_config,
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/pretrained.py", line 55, in __init__
    super(PretrainedAligner, self).__init__(corpus, dictionary, align_config, temp_directory,
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/base.py", line 40, in __init__
    self.setup()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/pretrained.py", line 74, in setup
    super(PretrainedAligner, self).setup()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/aligner/base.py", line 43, in setup
    self.dictionary.write()
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/dictionary.py", line 485, in write
    self._write_fst_binary(disambig=disambig)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/lib/python3.8/site-packages/Montreal_Forced_Aligner-2.0.0a1-py3.8.egg/montreal_forced_aligner/dictionary.py", line 708, in _write_fst_binary
    subprocess.call([thirdparty_binary('fstcompile'), '--isymbols={}'.format(phones_file_path),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/Users/wangchong/Desktop/proj_venv/venv_mfa2.0/bin/../lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by mmcauliffe** [comment]
Did you download the kaldi binaries (`mfa thirdparty download`)?  You can validate them with `mfa thirdparty validate`.  I'll add some explicit checking, but that should fix the issue.

**Comment by Ithrael** [comment]
thx, you solve my question
