### ISSUE TITLE
No lda.mat with `mfa train` (v2.0.0a2)

### ISSUE THREAD

**Issue by dlukes** [MontrealCorpusTools/Montreal-Forced-Aligner#201]
When I try to align using only my data set (`mfa train`), I get the following error when initializing LDA training, which indicates an `lda.mat` file is missing:

<details>

```
Traceback (most recent call last):
  File "/home/lukes/miniconda3/envs/mfa/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 292, in main
    run_train_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 109, in run_train_corpus
    align_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 68, in align_corpus
    a.train()
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 67, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/lda.py", line 61, in init_training
    lda_acc_stats(self.train_directory, self.data_directory, previous_trainer.align_directory, self,
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing.py", line 1399, in lda_acc_stats
    shutil.copyfile(os.path.join(directory, 'lda.mat'), os.path.join(config.corpus.split_directory(), 'lda.mat'))
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lukes/Documents/MFA/ortofon-v2-in/lda/lda.mat'
```

</details>

Digging into the logs, `lda/log/lda_est.log` ends with the following:

```
ERROR (est-lda[5.5]:Read():transform/lda-estimate.cc:193) LdaEstimate::Read, dimension or classes count mismatch, 72, 91,  vs. 0, 0
kaldi::KaldiFatalError
```

Do I need to somehow tweak [the default config](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration.html#default-training-config-file) in order for that `lda.mat` file to be properly generated?

**Comment by mmcauliffe** [comment]
Looking into this now, I am seeing some errors in logs for LDA, so I'll do some digging and fix it up, but it looks like in the mean time you've got it worked around with a custom config?

**Comment by dlukes** [comment]
Thanks for looking into this! Yes, I figured I should get a passable alignment with just monophones + triphones, and so far it looks like I might :) But if you get to the bottom of this, I'll definitely re-run it with the full config.

**Comment by mmcauliffe** [comment]
This should be working now with the latest release.

**Comment by laetokang** [comment]
I also do mfa train, but I haven't solved the error yet. Can you tell me how to fix the error? @dlukes

**Comment by dlukes** [comment]
If you're getting the error using v2.0.0a2, I would suggest trying to update to the latest version. If you're getting the error using the latest version, then please open a new issue, so that it can be addressed properly.
