### ISSUE TITLE
Document possible need to tweak subset config when aligning using only the data set

### ISSUE THREAD

**Issue by dlukes** [MontrealCorpusTools/Montreal-Forced-Aligner#202]
The section in the docs on [aligning using only the data set](https://montreal-forced-aligner.readthedocs.io/en/latest/aligning.html#align-using-only-the-data-set) should probably have a warning box explaining that the user might have to use a custom config with the `subset` keys tweaked, because the [default training config](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration.html#default-training-config-file) will allow them to align at most 30,000 recordings (= the `subset` value for the last training stage) :)

(Or even less if they're forced to comment out the later stages because of errors, e.g. #201 in my case.)

**Comment by mmcauliffe** [comment]
Oh yes, that's a good point, I'll look into making sure final alignment does the whole dataset.  Oversight from when the final config didn't have a subset parameter set, but it should do that regardless of whether it's just trained on a subset.

**Comment by dlukes** [comment]
Sounds great!

**Comment by dlukes** [comment]
I've hit a related bug (let me know if you'd rather if I opened another issue though!) -- [the docs](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration.html#monophone-configuration) suggest setting `subset: 0` in the config to use the full corpus. But when I set `training.monophone.subset` to 0, I get the following error at that stage:

<details>

```
All required kaldi binaries were found!
Setting up corpus information...
Parsing dictionary without pronunciation probabilties without silence probabilties
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Initializing training for mono...
Traceback (most recent call last):
  File "/home/lukes/miniconda3/envs/mfa/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 292, in main
    run_train_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 109, in run_train_corpus
    align_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 68, in align_corpus
    a.train()
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 67, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/monophone.py", line 80, in init_training
    num_gauss = self.get_num_gauss()
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/monophone.py", line 59, in get_num_gauss
    num = int(matches.groups()[0])
AttributeError: 'NoneType' object has no attribute 'groups'
```

</details>

And when I set `training.triphone.subset` to 0, I get the following error at that stage:

<details>

```
All required kaldi binaries were found!
Setting up corpus information...
Parsing dictionary without pronunciation probabilties without silence probabilties
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Initializing training for mono...
Initializing alignment improvement calculations
Initialization complete!
100%|███| 39/39 [27:54<00:00, 42.94s/it]
Initializing training for tri...
Traceback (most recent call last):
  File "/home/lukes/miniconda3/envs/mfa/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 292, in main
    run_train_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 109, in run_train_corpus
    align_corpus(args)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 68, in align_corpus
    a.train()
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 67, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/home/lukes/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/triphone.py", line 113, in init_training
    os.rename(occs_path, os.path.join(self.train_directory, '1.occs'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/lukes/Documents/MFA/ortofon-v2-in/tri/0.occs' -> '/home/lukes/Documents/MFA/ortofon-v2-in/tri/1.occs'
```

</details>

(I didn't get further than that because of #201, as I've said before.)

What works is to set subset to some concrete number greater than the number of segments in the corpus in both cases:

<details>

```
All required kaldi binaries were found!
Setting up corpus information...
Parsing dictionary without pronunciation probabilties without silence probabilties
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Initializing training for mono...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initializing alignment improvement calculations
Initialization complete!
100%|██| 39/39 [1:45:57<00:00, 163.02s/it]
Initializing training for tri...
Warning: Subset specified is larger than the dataset, using full corpus for this training block.
Initialization complete!
100%|██| 34/34 [24:20<00:00, 42.95s/it]
There were 863 segments/files not aligned. Please see /cnk/local/ssd/ortofon-v2/ortofon-v2-out/unaligned.txt for more details on why alignment failed for these files.
Saved model to /cnk/local/ssd/ortofon-v2/acoustics_models.zip
```

</details>

**Comment by mmcauliffe** [comment]
Ah, ok, so the workaround temporarily is to remove the subset key entirely, that'll set it to `None` which will use the whole dataset.  I'll fix the bug to make sure values less than and equal to 0 use the full dataset.

**Comment by mmcauliffe** [comment]
Overhauled the subset logic in the latest release, so these issues should be taken care of now.
