### ISSUE TITLE
There were phones in the dictionary that do not have acoustic models

### ISSUE THREAD

**Issue by vcombey** [MontrealCorpusTools/Montreal-Forced-Aligner#203]
Hi, I don't understand how tu run the aligner in french,
I downloaded the french dictionary here: https://raw.githubusercontent.com/MontrealCorpusTools/mfa-models/master/dictionary/fr.dict
and the french acoustic model here: https://github.com/MontrealCorpusTools/mfa-models/blob/master/acoustic/french.zip

and I ran
```./montreal-forced-aligner/bin/mfa_align /tmp/.tmpkhmOzQ ./fr.dict ./montreal-forced-aligner/pretrained_models/french.zip /tmp/.tmpsLnf45```

but that leads to 
```Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
/usr/src/app/aligner/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 88, in align_corpus
  File "aligner/models.py", line 129, in validate
aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models:
[678] Failed to execute script align```


I then tried with the  french_prosodylab acoustic model, now there are no errors, but no TextGrid output either.

```./montreal-forced-aligner/bin/mfa_align /tmp/.tmpkhmOzQ ./dict/french.txt ./montreal-forced-aligner/pretrained_models/french_prosodylab.zip```


by the way, all the links to the pre-trained models are broken in the 'stable' doc and the links to the pronunciation dictionary in the 'latest' doc

**Comment by vcombey** [comment]
actually with another audio file I get the TextGrid output. So it is maybe just the audio that is too hard for the aligner ?

**Comment by mmcauliffe** [comment]
For the fr.dict online, it's actually the french_prosodylab.zip (FR_FR) or french_qc.zip (CA_FR) that you'll have to use.  These use the prosodylab phone set, whereas the `french.zip` acoustic model uses the GlobalPhone French phone set (you can generate a dictionary to be used with this via the G2P capabilities).  See https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html for more information on the phone sets.  I'm more confused that another audio file managed to align properly.

**Comment by mmcauliffe** [comment]
I'll fix up the links in the latest version for the dictionaries, thanks for pointing that out!

**Comment by vcombey** [comment]
actually this is with the  french_prosodylab acoustic model that I got a TexGrid file.
But, half of the time, I don't get the alignement.
When the first word is missing from the transcription for example or when a word is written badly.
Is this expected behavior ?
