### ISSUE TITLE
Key Error in get_wav_duration during pretrained alignment

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#214]
Howdy! I have more information about the Key Errors I am receiving in v2.0.

```

Traceback (most recent call last):
  File "/home/nrbenway/miniconda3/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 290, in main
    run_align_corpus(args, acoustic_languages)
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 147, in run_align_corpus
    align_corpus(args)
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 94, in align_corpus
    a.export_textgrids(args.output_directory)
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 92, in export_textgrids
    convert_ali_to_textgrids(self.align_config, output_directory, ali_directory, self.dictionary,
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing.py", line 1035, in convert_ali_to_textgrids
    ctm_to_textgrid(word_ctm, phone_ctm, output_directory, corpus, dictionary)
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/textgrid.py", line 97, in ctm_to_textgrid
    maxtime = corpus.get_wav_duration(filename)
  File "/home/nrbenway/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 378, in get_wav_duration
    rec = self.segments[utt].split(' ')[0]
KeyError: XKZ_340_Post_raw_40.wav
```

My file names following this general pattern: `XKZ_340_Post_raw_40.wav`. A minority of files have an additional segment: `XKZ_340_Post_raw_40_A.wav`. The key error seems to arise when processing files with this additional segment, and the code exits because it is looking for a filename containing the first 5 elements of the name + extension, instead of the full set of 6 elements + extension. Finding and removing the `_A` suffix from files in the corpus seems to fix the issue.

**Comment by mmcauliffe** [comment]
Oh this is an interesting one.  So internally, MFA splits out multichannel wav files into `_A.wav` and `_B.wav` files and then strips them later when combining into a single textgrid, so it's likely related to that.  I'll think about a better way of detecting those files names being in the source corpus rather than assuming that they're multichannel files.
