### ISSUE TITLE
MFA 1.0.1 ISSUEs

### ISSUE THREAD

**Issue by cuongnguyengit** [MontrealCorpusTools/Montreal-Forced-Aligner#216]
root@cec217adb03e:/workspace/cuongnm55# ./code/montreal-forced-aligner/bin/mfa_train_and_align ./indir/ ./code/montreal-forced-aligner/pretrained_models/dict_w2c.txt ./outdir/ -j 8 -o ./code/montreal-forced-aligner/pretrained_models/abc.zip -i -q
train_and_align.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 171, in <module>
  File "aligner/command_line/train_and_align.py", line 67, in align_corpus
  File "aligner/aligner/base.py", line 85, in __init__
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/indir/train/mfcc/raw_mfcc.0.scp'

I can't train and align for my data, Please tell me how to fix that?

**Comment by zhouzyc** [comment]
相同问题，请问解决了吗？

**Comment by mmcauliffe** [comment]
I can't really support version 1.0, it's pretty brittle, and so much time has passed.  You can check `~/Documents/MFA/{name}/mfcc/make_mfccs.0.log` to see if there's anything about the files.

I'm going to close this, but if the similar issue you encountered was in MFA 2.X, then please open a new issue.
