### ISSUE TITLE
Cannot find some binaries on Linux (MFA version 2.0)

### ISSUE THREAD

**Issue by katashaku** [MontrealCorpusTools/Montreal-Forced-Aligner#221]
Hi! I'm new to MFA. I just installed it according to the online documentation and there were no problems. I also used "mfa thirdparty validate" to check the binaries and got "All required kaldi binaries were found!". However, when I tried to follow the alignment example [here](https://montreal-forced-aligner.readthedocs.io/en/latest/example.html) ("mfa align ..."), it gave me the following:

All required kaldi binaries were found!
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 111.0
Parsing dictionary without pronunciation probabilties without silence probabilties
Creating dictionary information...
Traceback (most recent call last):
  File "/home/lspmc/miniconda3/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 290, in main
    run_align_corpus(args, acoustic_languages)
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 147, in run_align_corpus
    align_corpus(args)
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 81, in align_corpus
    a = PretrainedAligner(corpus, dictionary, acoustic_model, align_config,
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 56, in __init__
    super(PretrainedAligner, self).__init__(corpus, dictionary, align_config, temp_directory,
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 40, in __init__
    self.setup()
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 75, in setup
    super(PretrainedAligner, self).setup()
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 43, in setup
    self.dictionary.write()
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/dictionary.py", line 500, in write
    self._write_fst_binary(disambig=disambig)
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/dictionary.py", line 724, in _write_fst_binary
    compile_proc = subprocess.Popen([thirdparty_binary('fstcompile'), '--isymbols={}'.format(phones_file_path),
  File "/home/lspmc/miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 12, in thirdparty_binary
    raise ThirdpartyError("Could not find '{}'.  Please ensure that you have downloaded the correct binaries.".format(binary_name))
montreal_forced_aligner.exceptions.ThirdpartyError: Could not find 'fstcompile'.  Please ensure that you have downloaded the correct binaries.

It seems that it cannot find the "fstcompile" binary. I guess it's a kaldi binary? But it says "All required kaldi binaries were found!" at the beginning... Does anyone know what to do? Thanks a lot!

**Comment by nrgslp** [comment]
Make sure that fstcompile is on your path, e.g.:

`export PATH=$PATH:/home/.../kaldi/tools/openfst-1.6.7/bin`

**Comment by mmcauliffe** [comment]
It looks you might be in the base conda environment instead the one that openfst was installed to (which is where `fstcompile` is from).  On reading back through the installation docs, I noticed I never explicitly said to activate the new environment, so I put that in: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html

Try out those instructions (you'll have to use `pip install` again once you're in the aligner environment) and see if that fixes the issue.

**Comment by katashaku** [comment]
Thanks for the help! I followed the suggestions from @mmcauliffe and the problem was solved! Thanks!

**Comment by yt605155624** [comment]
文本前端的处理在 https://paddleparakeet.readthedocs.io/en/latest/cn_text_frontend.html 可以找到
