### ISSUE TITLE
unable to align

### ISSUE THREAD

**Issue by samara0430** [MontrealCorpusTools/Montreal-Forced-Aligner#228]
when i pass the cmd listed below, i am having following errors. Please tell where am i wrong
lib/align ~/my_proj/proj-ppggmm/lab_and_wav ~/my_proj/Montreal-Forced-Aligner-1.0/eng.dict ~/my_proj/Montreal-Forced-Aligner-1.0/dist/montreal-forced-aligner/pretrained_models/english.zip ~/my_proj/output
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 40.0
/home/sneha/my_proj/Montreal-Forced-Aligner-1.0/dist/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 88, in setup
  File "aligner/dictionary.py", line 412, in write
  File "aligner/dictionary.py", line 639, in _write_fst_binary
  File "subprocess.py", line 557, in call
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'fstcompile'
[10674] Failed to execute script align

Thanks.

**Comment by mmcauliffe** [comment]
This looks to be version 1.0, right? Did you compile it from source yourself?  If so, make sure you pulled in Kaldi binaries using the thirdparty scripts, but you can also just add the relevant binary paths.  You might want to try 2.0, the installation instructions should be more straightforward: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html
