### ISSUE TITLE
2.0.0.a4 failing during lda training

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#229]
Howdy! I'm having difficulty training this corpus, even though validate/mono training runs to completion. Any thoughts from the community would be apreciated!

The command:
`mfa train /mnt/c/Apps-SU/Rhotic-Corpus-zCondor-sync/gt-rhotics/ /mnt/c/Apps-SU/Rhotic-Corpus-zExtras/MFA/gt-rhotics_CMU_full.dict /home/nrbenway/Documents/gt-rhotics-out/trained_regdict2/ --num_jobs 8 -o /home/.../Documents/gt-rhotics-out/model_regdict.zip -t /home/.../Documents/MFA/job2/ -c`

Print out
```
All required kaldi binaries were found!
/home/.../Documents/MFA/job2/gt-rhotics/train_and_align.log
INFO - Cleaning old directory!
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 36, average number of utterances per speaker: 297.52777777777777
INFO - Number of speakers in corpus: 36, average number of utterances per speaker: 297.52777777777777
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
Calculating CMVN...
INFO - Initializing training for mono...
/home/.../Documents/MFA/thirdparty/bin/feat-to-dim 'ark,s,cs:apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/utt2spk.0 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/cmvn.0.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/feats.0.scp ark:- | add-deltas ark:- ark:- |' -
add-deltas ark:- ark:-
apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/utt2spk.0 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/cmvn.0.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/feats.0.scp ark:-
WARNING (feat-to-dim[5.5]:Close():util/kaldi-io.cc:515) Pipe apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/utt2spk.0 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/cmvn.0.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/split8/feats.0.scp ark:- | add-deltas ark:- ark:- | had nonzero return status 36096
INFO - Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [03:21<00:00,  5.17s/it]
INFO - Training complete!
INFO - Generating alignments using mono models using 5000 utterances...
INFO - Initializing training for tri...
INFO - Initialization complete!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [02:43<00:00,  4.81s/it]
INFO - Training complete!
INFO - Generating alignments using tri models using 10000 utterances...
INFO - Initializing training for lda...
Traceback (most recent call last):
  File "/home/.../miniconda3/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 337, in main
    run_train_corpus(args)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 95, in align_corpus
    a.train()
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 78, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/trainers/lda.py", line 93, in init_training
    self._setup_tree(previous_trainer.align_directory)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/trainers/triphone.py", line 59, in _setup_tree
    tree_stats(self.train_directory, align_directory,
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/alignment.py", line 679, in tree_stats
    run_mp(tree_stats_func, jobs, config.log_directory)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/helper.py", line 89, in run_mp
    parse_logs(log_directory)
  File "/home/.../miniconda3/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 202, in parse_logs
    raise KaldiProcessingError(error_logs)
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```
acc_tree.log
```
/home/.../Documents/MFA/thirdparty/bin/acc-tree-stats --ci-phones=1:2:3:4:5:6:7:8:9:10:11:12:13:14:15 /home/.../Documents/MFA/job2/gt-rhotics/tri_ali/final.mdl 'ark,s,cs:apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/utt2spk.1 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/cmvn.1.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp ark:- |' ark:/home/.../Documents/MFA/job2/gt-rhotics/tri_ali/ali.1 /home/.../Documents/MFA/job2/gt-rhotics/lda/1.treeacc 
apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/utt2spk.1 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/cmvn.1.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp ark:- 
LOG (apply-cmvn[5.5]:main():featbin/apply-cmvn.cc:162) Applied cepstral mean normalization to 0 utterances, errors on 0
LOG (acc-tree-stats[5.5]:main():bin/acc-tree-stats.cc:118) Accumulated stats for 0 files, 0 failed due to no alignment, 0 failed for other reasons.
LOG (acc-tree-stats[5.5]:main():bin/acc-tree-stats.cc:121) Number of separate stats (context-dependent states) is 0
WARNING (acc-tree-stats[5.5]:Close():util/kaldi-io.cc:515) Pipe apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/utt2spk.1 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/cmvn.1.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp ark:- | had nonzero return status 256
ERROR (acc-tree-stats[5.5]:~SequentialTableReaderArchiveImpl():util/kaldi-table-inl.h:678) TableReader: error detected closing archive 'apply-cmvn --utt2spk=ark:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/utt2spk.1 scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/cmvn.1.scp scp:/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp ark:- |'
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```

lda_est.log
```
/home/.../Documents/MFA/thirdparty/bin/est-lda --write-full-matrix=/home/.../Documents/MFA/job2/gt-rhotics/lda/full.mat --dim=40 /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.mat /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.0.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.1.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.2.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.3.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.4.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.5.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.6.acc /home/.../Documents/MFA/job2/gt-rhotics/lda/lda.7.acc 
ERROR (est-lda[5.5]:Read():transform/lda-estimate.cc:193) LdaEstimate::Read, dimension or classes count mismatch, 584, 91,  vs. 0, 0
kaldi::KaldiFatalError
```

**Comment by mmcauliffe** [comment]
The mainline repo has some updates as part of debugging another person's issues.  I'll try to release 2.0.0a5 tonight and see if that addresses this.  I'm a little confused since it looks like it might not be finding the correct features in `/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp `.  But maybe the more recent changes will fix this too.

**Comment by mmcauliffe** [comment]
New version is up, if you wouldn't mind upgrading and trying it out again?

**Comment by nrgslp** [comment]
Yup, `/home/.../Documents/MFA/job2/gt-rhotics/corpus_data/subset_10000/feats.1.scp ` is empty, as is `feats.2.scp` and `feats.3.scp`. The rest seem to have generated properly. Looking into it....

**Comment by mmcauliffe** [comment]
What's the issue with the audio? Is it anything on MFA's side?

**Comment by Jueun0505** [comment]
![스크린샷 2021-07-30 오후 3 29 12](https://user-images.githubusercontent.com/88170875/127610508-c0ba4a9b-bedf-4b5e-99e8-1aac2e44d5d1.png)

Hi!
I have a similar problem. Could someone have a look at this error please?

**Comment by nrgslp** [comment]
Sorry for letting this slip - the issue with my audio was that it was recorded at a very low sampling rate but later upsampled to 22050. So there was just no information over 4kHz, which was causing those files to be empty.

**Comment by laetokang** [comment]
I also got the same error as @Jueun0505 . In the case of data I have, those sample frequency is 16 kHz. But when I do mfa train, the above error occurs. how do I fix it?
