### ISSUE TITLE
MFA 2.0 mfa train failed

### ISSUE THREAD

**Issue by weixsong** [MontrealCorpusTools/Montreal-Forced-Aligner#241]
Hi, 

I installed MFA 2.0  by "pip install montreal-forced-aligner", and install the Kaldi dependency by "mfa thirdparty download"

But when I do train and alignment, I got some errors:

```
INFO - Cleaning old directory!
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 2600.0
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 2600.0
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
INFO - Initializing training for mono...
INFO - Generating base features (mfcc)...
Traceback (most recent call last):
  File "/root/anaconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 341, in main
    run_train_corpus(args)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 95, in align_corpus
    a.train()
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 78, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/monophone.py", line 65, in init_training
    self._setup_for_init(identifier, temporary_directory, corpus, dictionary)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/base.py", line 155, in _setup_for_init
    self.feature_config.generate_features(self.corpus, logger=self.logger)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 238, in generate_features
    self.generate_base_features(corpus, logger=logger, compute_cmvn=cmvn)
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 175, in generate_base_features
    corpus.combine_feats()
  File "/root/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 435, in combine_feats
    with open(lengths_path, 'r') as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/MFA_Corpus/corpus_data/split1/utterance_lengths.0.scp'
```

It seems that Kaldi failed to extract the correct features. 

Anyone know how to solve this issue?

**Comment by Mddct** [comment]
How to deal with this? Meet Same Problem

**Comment by wangzhaolei** [comment]
I meet the same problem,too
