### ISSUE TITLE
Can't get MFA to work on LibriSpeech example from documentation.

### ISSUE THREAD

**Issue by JonasRSV** [MontrealCorpusTools/Montreal-Forced-Aligner#242]
Platform Ubuntu 18.04
Python Version: Python3.6

I am trying to follow the tutorial https://montreal-forced-aligner.readthedocs.io/en/latest/example.html to align LibriSpeech. But I get the following error

```bash
.venv ❯ ./data/montreal-forced-aligner/bin/mfa_align \
  ${FRIDAY_DATA}/librispeech/LibriSpeech/train-clean-100 \
  ${FRIDAY_DATA}/librispeech/word_phoneme_lexicon.txt \
  english \                                               
  ${FRIDAY_DATA}/librispeech/LibriSpeech/train-clean-100-aligned \
  -t /tmp
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 140, in validate_args
  File "aligner/command_line/align.py", line 135, in align_included_model
  File "aligner/command_line/align.py", line 85, in align_corpus
  File "aligner/corpus.py", line 543, in speaker_utterance_info
ZeroDivisionError: division by zero
[25054] Failed to execute script align
```

I downloaded mfa_align from the release page here: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases

And I symlinked my own python as suggested in https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/109 

For the specific steps I have taken, see: https://github.com/JonasRSV/Friday/blob/main/mm/docs/pipelines/deepMetricLearning.md

**Comment by JonasRSV** [comment]
I believe my librispeech was incorrectly formatted since I downloaded the original dataset and not the formatted one from the example
