### ISSUE TITLE
a align issue in MFA 2.0.0a5

### ISSUE THREAD

**Issue by 752377941** [MontrealCorpusTools/Montreal-Forced-Aligner#248]
All required kaldi binaries were found!
/home/zhiyu/Documents/MFA/AISHELL3/align.log
INFO - Cleaning old directory!
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 218, average number of utterances per speaker: 403.8302752293578
INFO - Number of speakers in corpus: 218, average number of utterances per speaker: 403.8302752293578
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
INFO - Done with setup!
Generating base features (mfcc)...
Traceback (most recent call last):
  File "/home/zhiyu/.conda/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 339, in main
    run_align_corpus(args, unknown, acoustic_languages)
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 159, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 98, in align_corpus
    a.align()
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 89, in align
    self.acoustic_model.feature_config.generate_features(self.corpus)
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 238, in generate_features
    self.generate_base_features(corpus, logger=logger, compute_cmvn=cmvn)
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/features/config.py", line 175, in generate_base_features
    corpus.combine_feats()
  File "/home/zhiyu/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 435, in combine_feats
    with open(lengths_path, 'r') as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhiyu/Documents/MFA/AISHELL3/corpus_data/split3/utterance_lengths.0.scp'

**Comment by weixsong** [comment]
Hi, I meet the same issue, this is because you used the pre-build Kaldi dependency libraries, if you build the Kaldi and copy the libraries, the issue could be solved.

**Comment by mmcauliffe** [comment]
Could you provide a bit more details on the system set up and the workaround?  What platform/version?  If it's an issue with the prebuilt binaries, then I'm assuming it's a older system version than what I built the binaries with.

**Comment by CrazyCharles6** [comment]
Hi, how was this problem solved in the end?

**Comment by CrazyCharles6** [comment]
> Hi, I meet the same issue, this is because you used the pre-build Kaldi dependency libraries, if you build the Kaldi and copy the libraries, the issue could be solved.

Hi, how to build the Kaldi and coy libraries?
