### ISSUE TITLE
Where is the trained model?

### ISSUE THREAD

**Issue by Sixtease** [MontrealCorpusTools/Montreal-Forced-Aligner#254]
I have trained a model with mfa train. Now I want to use that model to align some data but I don't know where to look for the trained model. The export directory only contains alignments of my training data and supplying the final.mdl files in ~/Documents/MFA doesn't work either.

**Comment by mmcauliffe** [comment]
You can rerun the command with the `-o` flag point to where to save the model, see https://montreal-forced-aligner.readthedocs.io/en/latest/aligning.html#cmdoption-output-model-path (should be quick since the files should all be cached).  Probably a good idea to output the model by default to the root output directory though, so I'll see about making that change.

**Comment by Sixtease** [comment]
Unfortunately, an error occurred:

```
Traceback (most recent call last):
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 341, in main
    run_train_corpus(args)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 99, in align_corpus
    a.save(args.output_model_path)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 57, in save
    self.training_config.values()[-1].save(path)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/base.py", line 372, in save
    acoustic_model.add_meta_file(self)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/models.py", line 91, in add_meta_file
    yaml.dump(aligner.meta, f)
  File "/home/sixtease/miniconda3/envs/vanilla-mfa/lib/python3.8/site-packages/montreal_forced_aligner/trainers/base.py", line 339, in meta
    data = {'phones': sorted(self.dictionary.nonsil_phones),
AttributeError: 'NoneType' object has no attribute 'nonsil_phones'
```

This didn't happen when training without the `-o` flag.

**Comment by mmcauliffe** [comment]
Hmm, that's odd.  What are the two commands you used?  I'll try to reproduce it.  In the meantime, there should be an "acoustic_model.zip" in the final "_ali" folder in the temporary directory (by default `~/Documents/MFA/...`), that's the one that would be repackaged for full output.

**Comment by Sixtease** [comment]
`mfa train -o model --config_path config.yaml train-50k/ dict.txt export`
and
`mfa train --config_path config.yaml train-50k/ dict.txt export` :-)

This is my config:

```
beam: 10
retry_beam: 40

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 10

training:
  - monophone:
      num_iterations: 40
      max_gaussians: 1000
      subset: 0
      boost_silence: 1.25

  - triphone:
      num_iterations: 35
      num_leaves: 2000
      max_gaussians: 10000
      cluster_threshold: -1
      subset: 0
      boost_silence: 1.25
      power: 0.25

  - lda:
      num_leaves: 2500
      max_gaussians: 15000
      subset: 0
      num_iterations: 35
      features:
          splice_left_context: 3
          splice_right_context: 3
```
