### ISSUE TITLE
Initializing training for tri...   montreal_forced_aligner.exceptions.KaldiProcessingError. 

### ISSUE THREAD

**Issue by Ithrael** [MontrealCorpusTools/Montreal-Forced-Aligner#257]
Mfa v2.0.0.5

(aligner) root@2b48e04971aa:~/train# mfa train --config_path config/basic_train.yaml align_input/ dict_tiny.txt result_tiny  --clean flag
All required kaldi binaries were found!
/root/Documents/MFA/align_input/train_and_align.log
INFO - Cleaning old directory!
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
Calculating CMVN...
INFO - Initializing training for mono...
WARNING - Subset specified is larger than the dataset, using full corpus for this training block.
INFO - Initialization complete!
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [12:31<00:00, 19.27s/it]
INFO - Training complete!
INFO - Generating alignments using mono models using 5000 utterances...
INFO - Initializing training for tri...
WARNING - Subset specified is larger than the dataset, using full corpus for this training block.
Traceback (most recent call last):
  File "/opt/conda/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 341, in main
    run_train_corpus(args)
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 143, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 95, in align_corpus
    a.train()
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 78, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/triphone.py", line 130, in init_training
    self._setup_tree(align_directory)
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/trainers/triphone.py", line 107, in _setup_tree
    parse_logs(self.log_directory)
  File "/opt/conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 202, in parse_logs
    raise KaldiProcessingError(error_logs)
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.

basic_train.yaml
![image](https://user-images.githubusercontent.com/38208715/112275781-f066b280-8cba-11eb-9ecd-18248a4a9a03.png)

Please

**Comment by Ithrael** [comment]
![image](https://user-images.githubusercontent.com/38208715/112275748-e1800000-8cba-11eb-9b14-4b5ea61a85f3.png)

**Comment by mmcauliffe** [comment]
What are the contents of the /root/Documents/MFA/align_input/train_and_align.log file?

**Comment by Ithrael** [comment]
I can't find this file
![image](https://user-images.githubusercontent.com/38208715/112433782-b01c3880-8d7d-11eb-9b04-af45c43e5768.png)

**Comment by Ithrael** [comment]
I use v2.0.0.8a  
/root/Documents/MFA/align_input/train_and_align.log
![image](https://user-images.githubusercontent.com/38208715/112563291-063bbb00-8e14-11eb-84b8-f78ddd92e9eb.png)

**Comment by xiaofeng1020** [comment]
Hi,I encountered the same problem, did you solve it?
Thank you!

**Comment by mmcauliffe** [comment]
Shouldn't be an issue as of recent releases.
