### ISSUE TITLE
module 'pynini' has no attribute 'acceptor'

### ISSUE THREAD

**Issue by austin-365** [MontrealCorpusTools/Montreal-Forced-Aligner#258]
I ran `mfa g2p mandarin_pinyin_g2p order/ ./out.txt`, but i got this. Do anyone know how can I handle it? Thank you very much.

Traceback ```
(most recent call last):
  File "/home/zhang/anaconda3/envs/align/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 343, in main
    run_g2p(args, g2p_languages)
  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/command_line/g2p.py", line 121, in run_g2p
    generate_dictionary(args)
  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/command_line/g2p.py", line 48, in generate_dictionary
    gen.output(args.output_path)
  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/g2p/generator.py", line 215, in output
    results = self.generate()
  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/g2p/generator.py", line 206, in generate
    raise exc
Exception: ['Traceback (most recent call last):\n', '  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/g2p/generator.py", line 90, in run\n    rep = self.rewriter.rewrite(word)\n', '  File "/home/zhang/anaconda3/envs/align/lib/python3.8/site-packages/montreal_forced_aligner/g2p/generator.py", line 44, in rewrite\n    pynini.acceptor(i, token_type=self.input_token_type) @ self.fst\n', "AttributeError: module 'pynini' has no attribute 'acceptor'\n"]

**Comment by mmcauliffe** [comment]
Can you try upgrading pynini via the following command: `conda upgrade -c conda-forge openfst pynini ngram baumwelch`?  The latest version of MFA upgrades pynini, which has some breaking API changes from the version that I used when first implementing it.  See also the note in installation: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#all-platforms

**Comment by austin-365** [comment]
ooh, Thank you! After recompiling Montreal-Forced-Aligner project, it works.
