### ISSUE TITLE
LibriTTS align. You provided the "cs" option but are not calling with keys in sorted order

### ISSUE THREAD

**Issue by SolomidHero** [MontrealCorpusTools/Montreal-Forced-Aligner#266]
Hello I am processing alignment for a LibriTTS train-clean-100 part. My directory before `mfa align` has structure below:
```
LibriTTS_train/
    1000/
        1000_88888_99999_00001.wav  # 16kHz wav
        1000_88888_99999_00001.lab   # text
        ...
    1234/
        ...
    ...
```

To reproduce I used only set of several speakers ([2989 302 307 311 3112 3168 32 3214 322 3235]).

Before `mfa align` I used `mfa g2p` with appropriate models downloaded and got phoneme dictionary. Command I ran after and its output (it fails):
`$ mfa align {input_dir} {phoneme_dict_path} {acoustic_model_path} {output_dir}`:

<details>
<summary> stdout </summary>

```pytb
All required kaldi binaries were found!
/root/Documents/MFA/LibriTTS_train/align.log
INFO - Setting up corpus information...
loading from source
INFO - Number of speakers in corpus: 10, average number of utterances per speaker: 60.5
INFO - Number of speakers in corpus: 10, average number of utterances per speaker: 60.5
INFO - Parsing dictionary without pronunciation probabilties without silence probabilties
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
INFO - Calculating CMVN...
INFO - Done with setup!
INFO - Performing first-pass alignment...
INFO - Calculating fMLLR for speaker adaptation...
Traceback (most recent call last):
  File "/content/miniconda/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 339, in main
    run_align_corpus(args, unknown, acoustic_languages)
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 159, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 98, in align_corpus
    a.align()
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/aligner/pretrained.py", line 99, in align
    calc_fmllr(self.align_directory, self.align_config.data_directory,
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/alignment.py", line 830, in calc_fmllr
    run_non_mp(calc_fmllr_func, jobs, log_directory)
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessing/helper.py", line 66, in run_non_mp
    parse_logs(log_directory)
  File "/content/miniconda/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", line 202, in parse_logs
    raise KaldiProcessingError(error_logs)
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```
</details>

Log for fmllr:

<details>
<summary> ~/Documents/MFA/LibriTTS_train/align/log/fmllr.final.0.log </summary>

```bash
/root/Documents/MFA/thirdparty/bin/ali-to-post ark:/root/Documents/MFA/LibriTTS_train/align/ali.0 ark:/root/Documents/MFA/LibriTTS_train/align/post.0 
LOG (ali-to-post[5.5]:main():bin/ali-to-post.cc:73) Converted 302 alignments.
/root/Documents/MFA/thirdparty/bin/weight-silence-post 0.0 6 /root/Documents/MFA/LibriTTS_train/align/final.mdl ark:/root/Documents/MFA/LibriTTS_train/align/post.0 ark:/root/Documents/MFA/LibriTTS_train/align/weight.0 
LOG (weight-silence-post[5.5]:main():bin/weight-silence-post.cc:95) Done 302 posteriors.
/root/Documents/MFA/thirdparty/bin/gmm-est-fmllr --verbose=4 --fmllr-update-type=full --spk2utt=ark:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/spk2utt.0 /root/Documents/MFA/LibriTTS_train/align/final.mdl 'ark,s,cs:apply-cmvn --utt2spk=ark:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/utt2spk.0 scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/cmvn.0.scp scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/feats.0.scp ark:- | add-deltas ark:- ark:- |' ark,s,cs:/root/Documents/MFA/LibriTTS_train/align/weight.0 ark:/root/Documents/MFA/LibriTTS_train/align/trans.0 
add-deltas ark:- ark:- 
apply-cmvn --utt2spk=ark:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/utt2spk.0 scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/cmvn.0.scp scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/feats.0.scp ark:- 
LOG (gmm-est-fmllr[5.5]:ComputeFmllrMatrixDiagGmmFull():transform/fmllr-diag-gmm.cc:262) fMLLR objf improvement is 10.0828 per frame over 45294 frames.
LOG (gmm-est-fmllr[5.5]:main():gmmbin/gmm-est-fmllr.cc:143) For speaker 2989, auxf-impr from fMLLR is 10.0828, over 45294 frames.
LOG (gmm-est-fmllr[5.5]:ComputeFmllrMatrixDiagGmmFull():transform/fmllr-diag-gmm.cc:262) fMLLR objf improvement is 7.55816 per frame over 7273 frames.
LOG (gmm-est-fmllr[5.5]:main():gmmbin/gmm-est-fmllr.cc:143) For speaker 311, auxf-impr from fMLLR is 7.55816, over 7273 frames.
LOG (apply-cmvn[5.5]:main():featbin/apply-cmvn.cc:162) Applied cepstral mean normalization to 302 utterances, errors on 0
LOG (gmm-est-fmllr[5.5]:ComputeFmllrMatrixDiagGmmFull():transform/fmllr-diag-gmm.cc:262) fMLLR objf improvement is 6.6155 per frame over 64892 frames.
LOG (gmm-est-fmllr[5.5]:main():gmmbin/gmm-est-fmllr.cc:143) For speaker 32, auxf-impr from fMLLR is 6.6155, over 64892 frames.
ERROR (gmm-est-fmllr[5.5]:FindKeyInternal():util/kaldi-table-inl.h:2106) You provided the "cs" option but are not calling with keys in sorted order: 3235_11599_000002_000000 < 32_4137_000048_000000: rspecifier is ark,s,cs:apply-cmvn --utt2spk=ark:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/utt2spk.0 scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/cmvn.0.scp scp:/root/Documents/MFA/LibriTTS_train/corpus_data/split3/feats.0.scp ark:- | add-deltas ark:- ark:- |
kaldi::KaldiFatalError
```
</details>

Also, I found alignment process further if use of `-s 4` parameter for `mfa align`. I think it is not wanted behaviour (since in example string `32` lexicographically less `3235` and such thoughs)

**Comment by mmcauliffe** [comment]
Hmm, interesting, I'll try to replicate and see if I can come with a solution for this.  I was thinking for a solving a separate issue of breaking it out by speaker-based archives rather than arbitrary job combinations, so I think that would solve this issue too anyway.

**Comment by keonlee9420** [comment]
Hi @SolomidHero and @mmcauliffe, I leave this comment to share some observations from a similar error that I got. After checking the current issue with #224, it turned out to be that Kaldi struggled with sorting speakers, especially when the speaker id has a different length. Fortunately, some contributions seem to solve a portion of the problem, but I guess the case where the speaker id consists only of numbers is remaining to be solved. 

As an example from my case, I got the following error when I used a speaker id from 1 to 280: 
`ERROR (gmm-est-fmllr[5.5]:FindKeyInternal():util/kaldi-table-inl.h:2106) You provided the "cs" option but are not calling with keys in sorted order: 167_0_167_3201-3600_clip_3321_31_121 < 16_9_16_0001-0400_clip_288_856_903`
Also, I found that all the speaker ids whose lengths are less than three were sorted incorrectly, while the others sharing the same length were sorted correctly, e.g., 253, 260, 268.

I used 2.0.0a13 version.

I hope this founding can provide insight for resolving the issue :)

**Comment by mmcauliffe** [comment]
Ok I think I've fixed this now, switched utterances to use dashes instead of underscores, since that was the key difference between what was working and the LibriTTS case.  If you could try updating to version 2.0.0a14 and giving it a shot.  You'll probably need to run `--clean` with the command to clear out the temporary cached files.

**Comment by fish0131** [comment]
Sorry for annoyance
how to replace underscores with dashes, where the code I should fix?
