### ISSUE TITLE
Validation error: frame info from .wav file

### ISSUE THREAD

**Issue by mfrebo** [MontrealCorpusTools/Montreal-Forced-Aligner#303]
When running `mfa validate corpus_directory dictionary_path`, I get the following error:
![image](https://user-images.githubusercontent.com/85804001/123937390-66537780-d996-11eb-85b0-6feb04038f15.png)

It looks like the problem comes from base.py at line 23: `frames = inf.frames`: the last line of the error message suggests that `.frames` is not an attribute of the .wav sound file.

However, the method wave.getnframes() returns a number which might be what base.py is looking for:
![image](https://user-images.githubusercontent.com/85804001/123939060-06f66700-d998-11eb-8e7f-941b629797d9.png)
 
The .wav file has been generated with pydub can be read in Praat.

**Comment by lucasgautheron** [comment]
According to the error and the source, [mfa uses SoundFile to process the wavs](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/corpus/base.py#L36), but the problem remained:

```python
>>> import soundfile as sf
>>> s = sf.SoundFile('outputs/BN_1000-1100.wav')
>>> s.read()
array([ 0.01446533,  0.01107788, -0.00622559, ...,  0.01141357,
        0.04022217,  0.04766846])
>>> s.frames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/acristia/anaconda3/lib/python3.8/site-packages/soundfile.py", line 808, in __getattr__
    raise AttributeError(
AttributeError: 'SoundFile' object has no attribute 'frames'
>>>
```

But the problem has been resolved by upgrade soundfile to 0.10.3.post1.
Maybe this should be reflected into the setup requirements: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/setup.py#L76
