### ISSUE TITLE
ValueError: math domain error when use Dictionaries with pronunciation probability

### ISSUE THREAD

**Issue by yt605155624** [MontrealCorpusTools/Montreal-Forced-Aligner#305]
Hi I use MFA 1.0.1 in THCHS-30 (a Chinese datasets)
my lexicon are like follows:
![image](https://user-images.githubusercontent.com/24568452/124123962-7492b800-daaa-11eb-9188-2acdf0e880dc.png)
my *.lab are like follows:
![image](https://user-images.githubusercontent.com/24568452/124124042-8d02d280-daaa-11eb-9bb6-7c25354de7a7.png)
then I run the MFA, and get following error:
`Setting up corpus information...
Creating dictionary information...
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 171, in <module>
  File "aligner/command_line/train_and_align.py", line 67, in align_corpus
  File "aligner/aligner/base.py", line 85, in __init__
  File "aligner/aligner/base.py", line 88, in setup
  File "aligner/dictionary.py", line 410, in write
  File "aligner/dictionary.py", line 701, in _write_fst_text
ValueError: math domain error
[22656] Failed to execute script train_and_align`

could you please tell me how to solve this?

**Comment by yt605155624** [comment]
oh ，it's my be some probability is equal to 0.0

**Comment by mmcauliffe** [comment]
Oh interesting, yeah I don't think I have any explicit correction for that, so yeah I'll add some dithering to it before it takes the log.

**Comment by nonusg** [comment]
The same problem, anyone solved?

**Comment by nonusg** [comment]
I'm trying to validate russian corpus, and caught the same error.
