### ISSUE TITLE
train_and_aligned_error help!

### ISSUE THREAD

**Issue by c9412600** [MontrealCorpusTools/Montreal-Forced-Aligner#340]
Hi,I'm using the version of 0.8.1 ,but I have some error when I runing the code, please help me! Thanks
`Creating dictionary information...
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 6840.0
Using previous MFCCs
Traceback (most recent call last):
  File "aligner\command_line\train_and_align.py", line 136, in <module>
  File "aligner\command_line\train_and_align.py", line 53, in align_corpus
  File "aligner\aligner\trainable.py", line 144, in train_mono
  File "aligner\aligner\trainable.py", line 109, in _init_mono
  File "aligner\aligner\base.py", line 135, in get_num_gauss_mono
AttributeError: 'NoneType' object has no attribute 'groups'
Failed to execute script train_and_align
`

**Comment by c9412600** [comment]
please help me to solve it

**Comment by mmcauliffe** [comment]
Hi, 0.8.1 is quite old, so I don't know how much I can support that. I would recommend either upgrading to the latest version: https://montreal-forced-aligner.readthedocs.io/en/latest/getting_started.html#getting-started-ref, or use the latest stable release of the 1.X series: https://montreal-forced-aligner.readthedocs.io/en/stable/
