### ISSUE TITLE
mfa install error

### ISSUE THREAD

**Issue by rsettlage** [MontrealCorpusTools/Montreal-Forced-Aligner#366]
Hi,

we are having an error in the install.  We installed it fine last week, but this week are getting an error with what looks like a variable being created using a internal function as the name?

```
Traceback (most recent call last):
  File "/home/ajwalker/.conda/envs/aligner/bin/mfa", line 5, in <module>
    from montreal_forced_aligner.command_line.mfa import main
  File "/home/ajwalker/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/__init__.py", line 3, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "/home/ajwalker/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "/home/ajwalker/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 16, in <module>
    from montreal_forced_aligner.abc import MfaWorker, ModelExporterMixin, TrainerMixin
  File "/home/ajwalker/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 44, in <module>
    MetaDict = dict[str, Any]
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
```

**Comment by mmcauliffe** [comment]
Can you create a new environment for it with Python 3.9 instead of 3.8?  There some functionality in the latest release that takes advantage of some aspects of 3.9.  I'm confused why it wouldn't try to upgrade to 3.9 or give some sort of warning, I'll look into how conda does pinning of python versions again.

**Comment by rsettlage** [comment]
Will do, thanks.  This user is using conda, I personally have made the switch to micromamba.  I may try that as well.

**Comment by rsettlage** [comment]
That seems to have fixed it.

**Comment by mmcauliffe** [comment]
Ok cool, I think I may have a way to support 3.8 again, so I'll try that out regardless to prevent this from potentially popping up again.

**Comment by OpeyemiOsakuade** [comment]
I have updated to python 3.9.
But I keep getting the error below when I run the final cell 

# FINALLY, align phonemes and speech
!source {INSTALL_DIR}/miniconda3/bin/activate aligner; \
mfa align ./wav librispeech-lexicon.txt ./english.zip ./sample_aligned
# output files are at ./ljs_aligned
!echo "See output files at ./ljs_aligned"


@rsettlage @mmcauliffe  Did you get this error?




INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 358.0
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
ERROR - There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/tmp/mfa/miniconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/mfa.py", line 875, in main
    run_align_corpus(args, unknown)
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align.py", line 93, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align.py", line 38, in align_corpus
    aligner.align()
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 239, in align
    self.setup()
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 164, in setup
    self.load_corpus()
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 802, in load_corpus
    self.generate_features()
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 98, in generate_features
    self.mfcc()
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 313, in mfcc
    run_mp(mfcc_func, jobs, log_directory)
  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/utils.py", line 420, in run_mp
    raise exc
Exception: ['Traceback (most recent call last):\n', '  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/utils.py", line 330, in run\n    result = self.function(*arguments)\n', '  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/features.py", line 129, in mfcc_func\n    mfcc_base_command = [thirdparty_binary("compute-mfcc-feats"), "--verbose=2"]\n', '  File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/utils.py", line 76, in thirdparty_binary\n    raise ThirdpartyError(binary_name)\n', "montreal_forced_aligner.exceptions.ThirdpartyError: \x1b[31mThirdpartyError\x1b[0m: Could not find '\x1b[31mcompute-mfcc-feats\x1b[0m'. Please ensure that you have downloaded the correct binaries.\n"]
