### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/chunjiao_0310/corpus_data/split1/feats.pinyin-lexicon-r.0.scp'

### ISSUE THREAD

**Issue by Tian14267** [MontrealCorpusTools/Montreal-Forced-Aligner#410]
**Debugging checklist**

**Describe the issue**
system:   **docker**  -- ubuntu
version:  **Montreal-Forced-Aligner  2.0.0b7**
operate:  mfa train ....
Bug detail:
```
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no
                   weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Found old run with 1 rather than the current 3, setting to 1.  If you would like to use 3, re-run the
                command with --clean.
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 497.0
INFO - Parsing dictionary "pinyin-lexicon-r" without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
INFO - Setting up training data...
INFO - Generating base features (mfcc)...
Traceback (most recent call last):
  File "/root/anaconda3/envs/t2s/bin/mfa", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 797, in main
    run_train_acoustic_model(args, unknown)
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 251, in run_train_acoustic_model
    train_acoustic_model(args, unknown_args)
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 156, in train_acoustic_model
    a = TrainableAligner(
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 65, in __init__
    super(TrainableAligner, self).__init__(
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 92, in __init__
    self.setup()
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 100, in setup
    self.corpus.initialize_corpus(self.dictionary, self.align_config.feature_config)
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 728, in initialize_corpus
    self.generate_features()
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 794, in generate_features
    self.combine_feats()
  File "/root/anaconda3/envs/t2s/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 835, in combine_feats
    with open(path, "r") as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/chunjiao_0310/corpus_data/split1/feats.pinyin-lexicon-r.0.scp'
```

I run it in docker.
How can I solve this problem ?

**Comment by EricFuma** [comment]
I think this is not a bug. The Error info means that you didn't create the mfcc feature successfully,  just check the log directory in `split1`, may giving some useful info, like `error while loading shared libraries`

**Comment by GaryGao99** [comment]
@Tian14267  It will be output error info if you use --disable_mp. Please see #452
