### ISSUE TITLE
[BUG] acoustic models trained using v2.0.0b9 don't work on v2.0.0rc3

### ISSUE THREAD

**Issue by echodroff** [MontrealCorpusTools/Montreal-Forced-Aligner#422]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

The acoustic models trained using v2.0.0b9 no longer work on v2.0.0rc3. 

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? czech, hungarian -- any of the Common Voice/VoxCommunis ones (https://osf.io/t957v/), but *not* any of the primary MFA ones like English or German Prosodylab
   * How many files/speakers? 1 file, 1 speaker
   * Are you using lab files or TextGrid files for input? we've tried both
   
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? The ones from the VoxCommunis set (https://osf.io/t957v/) 
   * If it's a custom dictionary, what is the phoneset? IPA (https://osf.io/t957v/)
   
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? No, it's the VoxCommunis set (https://osf.io/t957v/)
   * If it's a model you've trained, what data was it trained on? Common Voice, trained using MFA v2.0.0b9

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

No new folder appears in Documents/MFA; this error is printed to the terminal:

(aligner_new) Admins-MBP-2:~ eleanorchodroff$ mfa align --clean Desktop/test/ czech_ipa_clean czech_cv Desktop/output/
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x10141f970>>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 99, in history_save_handler
    raise self.exception
  File "/opt/miniconda3/envs/aligner_new/bin/mfa", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 919, in main
    run_align_corpus(args, unknown)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 101, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 31, in align_corpus
    aligner = PretrainedAligner(
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 145, in __init__
    super().__init__(**kw)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/alignment/base.py", line 45, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 941, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 74, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 102, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 367, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 203, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/multispeaker.py", line 110, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/alignment/mixins.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/mixins.py", line 327, in __init__
    phone_set_type = PhoneSetType[phone_set_type]
  File "/opt/miniconda3/envs/aligner_new/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: None

**Desktop (please complete the following information):**
 - OS: Mac OSX, also tried on Windows
 - Version: Mac OSX Monterey 12.1
 - Any other details about the setup (Cloud, Docker, etc) NA

**Additional context**
NA

**Comment by mmcauliffe** [comment]
Should be fixed in 2.0.0rc4!

**Comment by Robinysh** [comment]
Can anyone confirm the bug has been fixed in 2.0.0rc4? Im having the same issue on 2.0.0.rc5
