### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SunchinSekian** [MontrealCorpusTools/Montreal-Forced-Aligner#425]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[ ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * How many files/speakers?
   * Are you using lab files or TextGrid files for input?
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

Traceback (most recent call last):
  File "/home/wzynb/miniconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/wzynb/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 918, in main
    check_third_party()
  File "/home/wzynb/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/utils.py", line 72, in check_third_party
    raise ThirdpartyError("compute-mfcc-feats")
montreal_forced_aligner.exceptions.ThirdpartyError: ThirdpartyError: Could not find 'compute-mfcc-feats'. Please ensure that you have installed MFA's conda dependencies and
   are in the correct environment.

**Comment by mmcauliffe** [comment]
Is kaldi installed in your aligner environment?  Can you run `compute-mfcc-feats` by itself and see if there's a more informative error message?
