### ISSUE TITLE
[BUG] Win10 OSError: sndfile library not found

### ISSUE THREAD

**Issue by EzerbelCN** [MontrealCorpusTools/Montreal-Forced-Aligner#426]
**Env**

OS: Windows10
MFA: v2.0.0b11 

![image](https://user-images.githubusercontent.com/66873183/162420101-e2778d35-3bc3-4969-a33a-6c5f587080c2.png)

**Des**
failed to import soundfile 

**Traceback**
```
Traceback (most recent call last):
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\MayaDev\PycharmProjects\MFATools\root\src\test\test2.py", line 4, in <module>
    from montreal_forced_aligner.alignment import  PretrainedAligner
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\__init__.py", line 4, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\acoustic_modeling\__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\acoustic_modeling\base.py", line 19, in <module>
    from montreal_forced_aligner.alignment import AlignMixin
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\alignment\__init__.py", line 6, in <module>
    from montreal_forced_aligner.alignment.adapting import AdaptingAligner
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\alignment\adapting.py", line 16, in <module>
    from montreal_forced_aligner.alignment.pretrained import PretrainedAligner
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\alignment\pretrained.py", line 15, in <module>
    from montreal_forced_aligner.alignment.base import CorpusAligner
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\alignment\base.py", line 27, in <module>
    from montreal_forced_aligner.corpus.acoustic_corpus import AcousticCorpusPronunciationMixin
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\__init__.py", line 9, in <module>
    from montreal_forced_aligner.corpus.acoustic_corpus import (
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 17, in <module>
    from montreal_forced_aligner.corpus.base import CorpusMixin
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 15, in <module>
    from montreal_forced_aligner.corpus.classes import (
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\classes.py", line 23, in <module>
    import librosa
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\librosa\core\__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\librosa\core\audio.py", line 8, in <module>
    import soundfile as sf
  File "E:\Dev\miniconda3\envs\aligner\lib\site-packages\soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library 'E:\Dev\miniconda3\envs\aligner\lib\site-packages\_soundfile_data\libsndfile64bit.dll': error 0x7e

```
**Is it not supported to use PretrainedAligner on Win10?**

somebody help me, please~~~

**Comment by mmcauliffe** [comment]
Something seems messed up in the conda installation.  I would recommend just remaking the environment (either through ``conda create -n aligner montreal-forced-aligner`` or doing a different name for the environment).  If you're still hitting this, I'm not too sure why the libsndfile dll isn't on your path, maybe do a search for it to see if it's with the rest of the conda dlls?

**Comment by EzerbelCN** [comment]
I have remade the environment through `conda create -n aligner montreal-forced-aligner`  for times,

and tried a new name `mfaligner`, etc,

still no  "libsndfile.dll" is found, 

but the align function of command line tool always works well.

Some debug screen-shots here:

![image](https://user-images.githubusercontent.com/66873183/162562220-7ee3def7-b1b9-4829-b758-0e51a2709633.png)

It seems like the procedure is looking for a file named "sndfile.dll" from os env path,

Yes, a dll named "sndfile.dll" not "libsndfile.dll".

I googled , but only downloaded a "libsndfile.dll", it will not help.

I just want to use the function of force-align in my code for smaller pkg size.

If there is any further step to explore the problem?

Thanks.

**Comment by mmcauliffe** [comment]
Can you try the work around in https://github.com/conda-forge/pysoundfile-feedstock/issues/13#issuecomment-868995841? It sounds like this situation crops up from time to time.

**Comment by EzerbelCN** [comment]
@mmcauliffe 

I made an env by cond-forge, and only install librosa 0.8.0, python 3.8
tried this code below:
![image](https://user-images.githubusercontent.com/66873183/162613990-bfe041c9-79e3-4c35-b233-1b1ef8e7f280.png)
It is the same as what happened in the mfaligner env(which made with conda too,   librosa installed , win10).

Just add the path:  `E:\Dev\miniconda3\envs\librosaEnv\Library\bin`  into OS env path, librosa will run successfully.

![image](https://user-images.githubusercontent.com/66873183/162614128-05a3df3e-e01c-4937-9e5c-5116e9ae08d2.png)


It seems like ,if you build your librosa env without conda, the librosa works well without this issue(Windows I mean).

But if you want to use conda to build an env with liborsa on windows, 

you should manually add the path to OS env path,

 its path likes "X:\conda\envs\envName\library\bin".
