### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by unrea1-sama** [MontrealCorpusTools/Montreal-Forced-Aligner#430]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

I installed latest MFA via:
```
conda config --add channels conda-forge
conda install montreal-forced-aligner
```
When I train a new acoustic model from my corpus by running:
`mfa train wav_mono_24k_16b_norm-6db/ biaobei_pingyin-fa_dict.txt biaobei_model.zip biaobei_aligned/ --verbose --clean -t temp`, mfa reports an error:
```
DEBUG - Set up logger for MFA version: 2.0.0b9
DEBUG - Cleaned previous run
DEBUG - Loaded dictionary in 0.07864785194396973
INFO - Setting up corpus information...
DEBUG - Loading from source with multiprocessing
DEBUG - Finished adding jobs!
DEBUG - Waiting for workers to finish...
DEBUG - Parsed corpus directory with 3 jobs in 28.48127555847168 seconds
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 9998.0
DEBUG - Loaded corpus in 28.482479572296143
DEBUG - Set up lexicon word set in 0.0007152557373046875
DEBUG - Wrote lexicon information in 4.649134159088135
DEBUG - Set dictionaries for speakers in 0.10019469261169434
INFO - Setting up training data...
DEBUG - Initialized jobs in 0.0001850128173828125
DEBUG - Wrote corpus information in 15.330731868743896
DEBUG - Created corpus split directory in 1.6855835914611816
INFO - Generating base features (mfcc)...
ERROR - There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "~/miniconda/bin/mfa", line 11, in <module>
    sys.exit(main())
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/command_line/mfa.py", line 884, in main
    run_train_acoustic_model(args, unknown)
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 115, in run_train_acoustic_model
    train_acoustic_model(args, unknown_args)
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 44, in train_acoustic_model
    trainer.train(generate_final_alignments)
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 263, in train
    self.setup()
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 154, in setup
    self.load_corpus()
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 806, in load_corpus
    self.generate_features()
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 99, in generate_features
    self.combine_feats()
  File "~/miniconda/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 423, in combine_feats
    with open(path, "r") as inf:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/wav_mono_24k_16b_norm-6db_train_acoustic_model/wav_mono_24k_16b_norm-6db/split1/feats.biaobei_pingyin-fa_dict.0.scp'
```

1. Corpus structure
   * I used a Chinese corpus. It contains 9998 audios from one speaker. Text files containing transcripts are provided as input.
2. Dictionary
   * A custom dictionary is used.
4. Acoustic model
   * The acoustic model is trained on my Chinese corpus.

**Log file**

train_acoustic_model.log
```2022-04-17 20:04:18,189 - train_acoustic_model - DEBUG - Set up logger for MFA version: 2.0.0b9
2022-04-17 20:04:18,190 - train_acoustic_model - DEBUG - Cleaned previous run
2022-04-17 20:04:18,289 - train_acoustic_model - DEBUG - Loaded dictionary in 0.07864785194396973
2022-04-17 20:04:18,289 - train_acoustic_model - INFO - Setting up corpus information...
2022-04-17 20:04:18,289 - train_acoustic_model - DEBUG - Loading from source with multiprocessing
2022-04-17 20:04:21,645 - train_acoustic_model - DEBUG - Finished adding jobs!
2022-04-17 20:04:42,989 - train_acoustic_model - DEBUG - Waiting for workers to finish...
2022-04-17 20:04:46,771 - train_acoustic_model - DEBUG - Parsed corpus directory with 3 jobs in 28.48127555847168 seconds
2022-04-17 20:04:46,771 - train_acoustic_model - INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 9998.0
2022-04-17 20:04:46,771 - train_acoustic_model - DEBUG - Loaded corpus in 28.482479572296143
2022-04-17 20:04:46,772 - train_acoustic_model - DEBUG - Set up lexicon word set in 0.0007152557373046875
2022-04-17 20:04:51,422 - train_acoustic_model - DEBUG - Wrote lexicon information in 4.649134159088135
2022-04-17 20:04:51,522 - train_acoustic_model - DEBUG - Set dictionaries for speakers in 0.10019469261169434
2022-04-17 20:04:51,522 - train_acoustic_model - INFO - Setting up training data...
2022-04-17 20:04:51,523 - train_acoustic_model - DEBUG - Initialized jobs in 0.0001850128173828125
2022-04-17 20:05:06,853 - train_acoustic_model - DEBUG - Wrote corpus information in 15.330731868743896
2022-04-17 20:05:08,539 - train_acoustic_model - DEBUG - Created corpus split directory in 1.6855835914611816
2022-04-17 20:05:08,540 - train_acoustic_model - INFO - Generating base features (mfcc)...
2022-04-17 20:05:08,740 - train_acoustic_model - ERROR - There was an error in the run, please see the log.
```

make_mfcc.0.log
```
~/miniconda/bin/copy-feats: error while loading shared libraries: libfst.so.6: cannot open shared object file: No such file or directory
~/miniconda/bin/compute-mfcc-feats: error while loading shared libraries: libfst.so.6: cannot open shared object file: No such file or directory
~/miniconda/bin/feat-to-len: error while loading shared libraries: libfst.so.6: cannot open shared object file: No such file or directory
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 20.04

**Comment by unrea1-sama** [comment]
I fixed this problem by running `conda update -c conda-forge kaldi`. I wonder if there's any version mismatch of dependencies.

**Comment by mmcauliffe** [comment]
The latest MFA should pull the latest Kaldi version, which had a lot of fixes for how BLAS was linked.  Not sure if that's what was causing the issues with libfst not being found, but updating MFA and Kaldi should fix it.
