### ISSUE TITLE
Intervals are not sorted in time when exporting textgrid [BUG]

### ISSUE THREAD

**Issue by WelkinYang** [MontrealCorpusTools/Montreal-Forced-Aligner#456]
**Debugging checklist**

[Yes] Have you updated to latest MFA version?
[Yes] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Errors when exporting TextGrids

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Mandarin
   * How many files/speakers? 49999 for 100 speakers
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? No
   * If it's a custom dictionary, what is the phoneset? A mandarin phoneset
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
INFO - Exporting TextGrids to ./aligned_corpus...
INFO - Collecting phone and word alignments from alignment lattices...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 49987/49998 [00:38<00:00, 1295.20it/s]  0%|                                                                                                                                           | 0/49998 [00:00<?, ?it/s]Process ExportTextGridProcessWorker-2775:
Process ExportTextGridProcessWorker-2777:
Process ExportTextGridProcessWorker-2773:
Process ExportTextGridProcessWorker-2774:
Process ExportTextGridProcessWorker-2771:
Process ExportTextGridProcessWorker-2770:
Process ExportTextGridProcessWorker-2776:
Process ExportTextGridProcessWorker-2772:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=0.78, end=0.92, label='@ch')), (Interval(start=0.91, end=1.07, label='@ou4'))]
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 991, in run
    export_textgrid(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=0.39, end=0.58, label='qi3')), (Interval(start=0.57, end=0.7, label='de5'))]
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=1.27, end=1.53, label='zheng4')), (Interval(start=1.52, end=1.74, label='shi4'))]
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 187, in export_textgrid
    tg.save(output_path, includeBlankSpaces=True, format=output_format, reportingMode="error")
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"

During handling of the above exception, another exception occurred:

praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=1.43, end=1.63, label='huan4')), (Interval(start=1.62, end=1.84, label='zhe3'))]
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 461, in save
    self.validate(reportingMode)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=0.29, end=0.48, label='sa4')), (Interval(start=0.47, end=0.71, label='xian1'))]
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
Traceback (most recent call last):
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/textgrid.py", line 545, in validate
    isValid = isValid and tier.validate(reportingMode)

During handling of the above exception, another exception occurred:

praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=2.39, end=2.56, label='hen3')), (Interval(start=2.55, end=2.8, label='nan2'))]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=1.34, end=1.42, label='@p')), (Interval(start=1.41, end=1.57, label='@i3'))]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/data_classes/interval_tier.py", line 654, in validate
    errorReporter(
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/praatio/utilities/utils.py", line 30, in reportException
    raise exception(text)
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
praatio.utilities.errors.TextgridStateError: Intervals are not sorted in time: [(Interval(start=0.09, end=0.13, label='hh')), (Interval(start=0.12, end=0.16, label='eh1'))]
Traceback (most recent call last):
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"

During handling of the above exception, another exception occurred:

  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
  File "/usr/local/anaconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 998, in run
    f"Error writing to {output_path}: \n\n{self.textgrid_errors[output_path]}\n"
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'
AttributeError: 'ExportTextGridProcessWorker' object has no attribute 'textgrid_errors'

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by WelkinYang** [comment]
seems the end time for some phonemes is bigger than the start time of their next phoneme

**Comment by WelkinYang** [comment]
https://groups.google.com/g/kaldi-help/c/FNwBcZWQEyc?pli=1
As you can see in the conversation between this person and dan, he also encountered the problem of the end time being greater than the start time when using lattice.
