### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by yrsn509** [MontrealCorpusTools/Montreal-Forced-Aligner#459]
**Debugging checklist**

[ ] Have you updated to latest MFA version?
[√] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

when I'm Training MFA models, after finishing "Collecting phone and word alignments from alignment lattices...“， it suddenly stuck in the final step and reported the BUG.

Traceback (most recent call last):
  File "C:\Users\yrsn509\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\yrsn509\AppData\Local\Programs\Python\Python39\lib\site-packages\montreal_forced_aligner\alignment\multiprocessing.py", line 1167, in run
    export_textgrid(
  File "C:\Users\yrsn509\AppData\Local\Programs\Python\Python39\lib\site-packages\montreal_forced_aligner\textgrid.py", line 183, in export_textgrid
    if tier.entryList[-1][1] > tg.maxTimestamp:
IndexError: list index out of range

**For Reproducing your issue**
1. Open cmd and input conda activate command
2. Input this command "mfa train data/wav/EILEEN/split/ MFA/pinyin_eng.dict MFA/EILEEN.zip data/TextGrid/EILEEN/ --clean"
   (The dictionary is attached with the repo, I don't know whether it's the MFA original)
3. Wait for training, and it costs for 2 hours or so.
4. Bug comes out

1. Corpus structure
   * What language is the corpus in?   Mandarin
   * How many files/speakers?             1 Speaker, 21809 wavs
   * Are you using lab files or TextGrid files for input? 
     Yes, I have wavs and labs and using them for training, but after the bug it just has 200 TextGrid files output

5. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
   I don't know..
  
6. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?
   No, I used my own datasets serving as model.

**Log file**
[train_acoustic_model.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/8837296/train_acoustic_model.log)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows 10
 - Any other details about the setup (Cloud, Docker, etc)
 - Train through Conda Environment

**Screenshots**
![08d39dc43e6f42b4fa078cca3bc473a](https://user-images.githubusercontent.com/62604868/171991466-9ecdfa61-f9a3-4a91-a059-c8371858bdbe.png)

**Comment by torphix** [comment]
Same error but with english corpus VCTK to be precise

**Comment by Oreoluwa1234** [comment]
Hi @mmcauliffe , I am having same error, i don't know what to do.
Please help a friend.

**Comment by mmcauliffe** [comment]
@Oreoluwa1234 can you make a new issue with more details for what you're running into, along with updating to either the latest 3.0 alpha or installing one of the stable versions listed here: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#installing-older-versions-of-mfa?
