### ISSUE TITLE
[BUG] issue with pretrained model (hungarian_cv)

### ISSUE THREAD

**Issue by echodroff** [MontrealCorpusTools/Montreal-Forced-Aligner#496]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Alignment with the hungarian_cv acoustic model and dictionary throws an immediate error in the console. No files (not even the folder) is generated in the MFA folder. Both the acoustic model and dictionary were downloaded via the 'mfa model download' command. 'mfa validate' runs, but on closer inspection of the log file there seem to be a lot of nulls with potential characters(?). 'mfa align' and 'mfa adapt' that throw the error.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Hungarian
   * How many files/speakers? 1
   * Are you using lab files or TextGrid files for input? TextGrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? hungarian_cv
   * If it's a custom dictionary, what is the phoneset? NA
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? hungarian_cv
   * If it's a model you've trained, what data was it trained on?

**Log file**
**No log file generated for the align or adapt commands. (See additional context section for console output.)**

**Log file from mfa validate:**
2022-08-03 11:41:59,979 - hungarian_test_validate_pretrained - DEBUG - Beginning run for validate_pretrained on hungarian_test
2022-08-03 11:41:59,980 - hungarian_test_validate_pretrained - DEBUG - Using multiprocessing with 3
2022-08-03 11:41:59,980 - hungarian_test_validate_pretrained - DEBUG - Set up logger for MFA version: 2.0.5
2022-08-03 11:41:59,980 - hungarian_test_validate_pretrained - DEBUG - Cleaned previous run
2022-08-03 11:41:59,980 - hungarian_test_validate_pretrained - WARNING - Skipped the following configuration keys: pitch
2022-08-03 11:42:00,965 - hungarian_test_validate_pretrained - INFO - Setting up corpus information...
2022-08-03 11:42:00,966 - hungarian_test_validate_pretrained - DEBUG - Could not load from temp
2022-08-03 11:42:00,966 - hungarian_test_validate_pretrained - INFO - Loading corpus from source files...
2022-08-03 11:42:24,007 - hungarian_test_validate_pretrained - DEBUG - Processing queue: 0.09319299999999942
2022-08-03 11:42:24,510 - hungarian_test_validate_pretrained - DEBUG - Parsed corpus directory with 3 jobs in 0.11132499999999901 seconds
2022-08-03 11:42:24,524 - hungarian_test_validate_pretrained - INFO - Found 1 speaker across 1 file, average number of utterances per speaker: 1.0
2022-08-03 11:42:25,918 - hungarian_test_validate_pretrained - INFO - Initializing multiprocessing jobs...
2022-08-03 11:42:25,919 - hungarian_test_validate_pretrained - WARNING - Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs.
2022-08-03 11:42:25,927 - hungarian_test_validate_pretrained - INFO - Creating corpus split for feature generation...
2022-08-03 11:42:25,932 - hungarian_test_validate_pretrained - INFO - Generating base features (mfcc)...
2022-08-03 11:42:25,933 - hungarian_test_validate_pretrained - INFO - Generating MFCCs...
2022-08-03 11:42:33,970 - hungarian_test_validate_pretrained - INFO - Calculating CMVN...
2022-08-03 11:42:34,002 - hungarian_test_validate_pretrained - INFO - Creating corpus split with features...
2022-08-03 11:42:34,011 - hungarian_test_validate_pretrained - INFO - Skipping transcription testing
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - 
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - ====ACOUSTIC MODEL INFO====
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - Acoustic model root directory: /Users/eleanorchodroff/Documents/MFA/extracted_models/acoustic
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - Acoustic model dirname: /Users/eleanorchodroff/Documents/MFA/extracted_models/acoustic/hungarian_cv
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - Acoustic model meta path: /Users/eleanorchodroff/Documents/MFA/extracted_models/acoustic/hungarian_cv/meta.yaml
2022-08-03 11:42:34,028 - hungarian_test_validate_pretrained - DEBUG - Acoustic model meta information:
2022-08-03 11:42:34,032 - hungarian_test_validate_pretrained - DEBUG - architecture: gmm-hmm
base_phone_regex: null
features:
  allow_downsample: true
  allow_upsample: true
  feature_type: mfcc
  frame_shift: 10
  high_frequency: 7800
  low_frequency: 20
  pitch: false
  sample_frequency: 16000
  snip_edges: true
  use_energy: false
  uses_cmvn: true
  uses_deltas: false
  uses_speaker_adaptation: false
  uses_splices: true
  uses_voiced: false
multilingual_ipa: false
oov_phone: spn
optional_silence_phone: sil
other_noise_phone: sp
phone_set_type: null
phone_type: triphone
phones: !!set
  "a\u02D0": null
  b: null
  "b\u02D0": null
  c: null
  "c\u02D0": null
  d: null
  "d\u02D0": null
  "e\u02D0": null
  f: null
  "f\u02D0": null
  h: null
  "h\u02D0": null
  i: null
  "i\u02D0": null
  j: null
  "j\u02D0": null
  k: null
  "k\u02D0": null
  l: null
  "l\u02D0": null
  m: null
  "m\u02D0": null
  n: null
  "n\u02D0": null
  o: null
  "o\u02D0": null
  p: null
  "p\u02D0": null
  r: null
  "r\u02D0": null
  s: null
  "s\u02D0": null
  t: null
  ts: null
  "ts\u02D0": null
  "t\u0283": null
  "t\u0283\u02D0": null
  "t\u02D0": null
  u: null
  "u\u02D0": null
  v: null
  "v\u02D0": null
  y: null
  "y\u02D0": null
  z: null
  "z\u02D0": null
  "\xF8": null
  "\xF8\u02D0": null
  "\u0251": null
  "\u025B": null
  "\u025F": null
  "\u025F\u02D0": null
  "\u0261": null
  "\u0261\u02D0": null
  "\u0272": null
  "\u0272\u02D0": null
  "\u0283": null
  "\u0283\u02D0": null
  "\u0292": null
train_date: '2021-12-19 16:45:52.122252'
version: 2.0.0b9

2022-08-03 11:42:34,033 - hungarian_test_validate_pretrained - DEBUG - 
2022-08-03 11:42:34,033 - hungarian_test_validate_pretrained - INFO - Finished initializing!
2022-08-03 11:42:34,039 - hungarian_test_validate_pretrained - DEBUG - Duration calculation took 0.006009101867675781
2022-08-03 11:42:34,039 - hungarian_test_validate_pretrained - DEBUG - Ignored count calculation took 7.867813110351562e-06
2022-08-03 11:42:34,039 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,039 - hungarian_test_validate_pretrained - INFO - [1m******[0m
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO - [1mCorpus[0m
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO - [1m******[0m
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [32m1[0m sound files
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [32m1[0m text files
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [32m1[0m speakers
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [32m1[0m utterances
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [32m0.873[0m seconds total duration
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [1mSound file read errors[0m
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [1m======================[0m
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -     There were [32mno[0m issues reading sound files.
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,040 - hungarian_test_validate_pretrained - INFO -   [1mFeature generation[0m
2022-08-03 11:42:34,041 - hungarian_test_validate_pretrained - INFO -   [1m==================[0m
2022-08-03 11:42:34,041 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,044 - hungarian_test_validate_pretrained - INFO -     There were [32mno[0m utterances missing features.
2022-08-03 11:42:34,044 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,044 - hungarian_test_validate_pretrained - INFO -   [1mFiles without transcriptions[0m
2022-08-03 11:42:34,044 - hungarian_test_validate_pretrained - INFO -   [1m============================[0m
2022-08-03 11:42:34,044 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -     There were [32mno[0m sound files missing transcriptions.
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -   [1mTranscriptions without sound files[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -   [1m==================================[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -     There were [32mno[0m transcription files missing sound files.
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - [1m**********[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - [1mDictionary[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - [1m**********[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -   [1mOut of vocabulary words[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO -   [1m=======================[0m
2022-08-03 11:42:34,045 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO -     There were [33mno[0m missing words from the dictionary. If you plan on using the a model trained on this dataset to align 
      other datasets in the future, it is recommended that there be at least some missing words.
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO -   [1mAcoustic model compatibility[0m
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO -   [1m============================[0m
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO -     There were [32mno[0m phones in the dictionary without acoustic models.
2022-08-03 11:42:34,048 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:42:34,049 - hungarian_test_validate_pretrained - INFO - Compiling training graphs...
2022-08-03 11:42:42,773 - hungarian_test_validate_pretrained - DEBUG - Compiling training graphs took 8.724432229995728
2022-08-03 11:42:42,776 - hungarian_test_validate_pretrained - DEBUG - Performing first-pass alignment...
2022-08-03 11:42:42,776 - hungarian_test_validate_pretrained - INFO - Generating alignments...
2022-08-03 11:42:51,810 - hungarian_test_validate_pretrained - DEBUG - Alignment round took 9.03394103050232
2022-08-03 11:42:51,813 - hungarian_test_validate_pretrained - DEBUG - Analyzing alignment information
2022-08-03 11:43:00,991 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:43:00,992 - hungarian_test_validate_pretrained - INFO - [1m*********[0m
2022-08-03 11:43:00,992 - hungarian_test_validate_pretrained - INFO - [1mAlignment[0m
2022-08-03 11:43:00,992 - hungarian_test_validate_pretrained - INFO - [1m*********[0m
2022-08-03 11:43:00,992 - hungarian_test_validate_pretrained - INFO - 
2022-08-03 11:43:00,992 - hungarian_test_validate_pretrained - INFO -   [32m0[0m utterances were too short to be aligned
2022-08-03 11:43:00,993 - hungarian_test_validate_pretrained - INFO -   [32m0[0m utterances that need a larger beam to align
2022-08-03 11:43:01,001 - hungarian_test_validate_pretrained - INFO -   [32m1[0m utterances were successfully aligned
2022-08-03 11:43:01,001 - hungarian_test_validate_pretrained - DEBUG - Average per frame likelihood for alignment: -62.13499999999999
2022-08-03 11:43:01,002 - hungarian_test_validate_pretrained - DEBUG - Compiling information took 9.188853025436401
2022-08-03 11:43:01,002 - hungarian_test_validate_pretrained - INFO - Done! Everything took 61.02481007575989 seconds

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] OSX
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] macOS Big Sur, v 11.6
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
(aligner2) Eleanors-iPro:~ eleanorchodroff$ mfa align --clean --verbose ~/Desktop/hungarian_test hungarian_cv hungarian_cv ~/Desktop/hungarian_out/
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x104c039a0>>
Traceback (most recent call last):
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 103, in history_save_handler
    raise self.exception
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/bin/mfa", line 11, in <module>
    sys.exit(main())
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 1067, in main
    run_align_corpus(args, unknown)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 106, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 31, in align_corpus
    aligner = PretrainedAligner(
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 65, in __init__
    super().__init__(**kw)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/alignment/base.py", line 68, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1020, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 93, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 98, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 465, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 287, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/multispeaker.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/mixins.py", line 927, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/alignment/mixins.py", line 82, in __init__
    super().__init__(**kwargs)
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/mixins.py", line 467, in __init__
    phone_set_type = PhoneSetType[phone_set_type]
  File "/Users/eleanorchodroff/opt/miniconda3/envs/aligner2/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: None

**Comment by kingfener** [comment]
I meet the same error. and I fix it by : 

in file :  xxxx/site-packages/montreal_forced_aligner/dictionary/mixins.py
         line : 467
        phone_set_type  = "PINYIN".  # in sert this line before " if not isinstance(phone_set_type, PhoneSetType):"
        if not isinstance(phone_set_type, PhoneSetType):
