### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable Failed to execute script align

### ISSUE THREAD

**Issue by zhangyaqiang** [MontrealCorpusTools/Montreal-Forced-Aligner#50]
I have used mfa_align for a week , it's has no problem , but yesterday  it suddenly couldn't work.This is error message:

```
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 146, in validate_args
  File "aligner/command_line/align.py", line 69, in align_corpus
TypeError: 'NoneType' object is not subscriptable
Failed to execute script align
```
I didn't change anything, what's the problem?

**Comment by mmcauliffe** [comment]
That's pretty puzzling.  One thing you can try is to delete the temporary directory for the directory you're aligning.  It looks like it's having an issue loading information from previous runs.

**Comment by zhangyaqiang** [comment]
It works after I delete the temporary directory, thanks.

**Comment by alpoktem** [comment]
Hi, I am having the same problem. It gives the error when the directory with the audiofiles is in specific locations. It works under the montreal-forced-aligner directory for example. 
It used to work without problems before. What should I delete?

**Comment by zhangyaqiang** [comment]
Delete /Documents/MFA is fine.

**Comment by alpoktem** [comment]
OK! Got it thanks!

**Comment by lorenlugosch** [comment]
I ran into this issue too. Deleting the temporary directory worked for me as well.

**Comment by OscarVanL** [comment]
Deleting ~/Documents/MFA worked for me too

**Comment by hwhw97** [comment]
Deleting ~/Documents/MFA worked for me too, thanks!
