### ISSUE TITLE
using --reference_directory get error

### ISSUE THREAD

**Issue by xiaozhah** [MontrealCorpusTools/Montreal-Forced-Aligner#518]
mfa align ./input mandarin_pinyin mandarin ./tg1 --overwrite --clean
mfa align ./input mandarin_pinyin mandarin ./tg --reference_directory ./tg1 --overwrite --clean

Then got this:
```
ERROR - There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: reference_phone_interval.begin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\mfa-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 1062, in main
    run_align_corpus(args, unknown)
  File "C:\ProgramData\Miniconda3\lib\site-packages\montreal_forced_aligner\command_line\align.py", line 107, in run_align_corpus
    align_corpus(args, unknown_args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\montreal_forced_aligner\command_line\align.py", line 52, in align_corpus
    aligner.load_reference_alignments(args.reference_directory)
  File "C:\ProgramData\Miniconda3\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 207, in load_reference_alignments
    conn.execute(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: reference_phone_interval.begin
[SQL: INSERT INTO reference_phone_interval DEFAULT VALUES]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by mmcauliffe** [comment]
What's the format of the reference alignments?  They should be TextGrids like what would be exported from MFA, but it seems like one or more of the phone intervals does not  have a start time.

**Comment by Approximetal** [comment]
> What's the format of the reference alignments? They should be TextGrids like what would be exported from MFA, but it seems like one or more of the phone intervals does not have a start time.

I have the same error, and I found here https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/9a1034580502558aabc6b86bbfc52e1b53730395/montreal_forced_aligner/corpus/acoustic_corpus.py#L266 does not return anyting that results reference_intervals empty.

What is the format of reference dictionary? Does it need the same speaker name?

**Comment by Eie1** [comment]
hi，xiaozhah，could I ask that if you have resolved this problem？

**Comment by Eie1** [comment]
and have you also can get alignment_analysis.csv？thanks very much if you can reply

**Comment by xiaozhah** [comment]
Not success to try the reference_directory, so I manually exported the FA results to *.TextGrid and then calculated the mean and std of absolute duration at the phoneme and word level, as well as the hit accuracy with a tolerance of 25ms.

**Comment by Eie1** [comment]
Thanks for replying，good luck！

**Comment by Eie1** [comment]
dear friend，have you trained the model in multilingual situation？I want to use this tool in multilingual situation.
Thanks for replying very much

**Comment by Eie1** [comment]
dear friend，have you test NeuFA and compare it with mfa？I want to choose one and use  in multilingual situation.
Thanks for your helping.

**Comment by xiaozhah** [comment]
I do not recommend using NeuFA, as it may not consistently perform well. Instead, I suggest training an HMM (MFA) model for each speaker and utilizing wav2vec2 as a feature extractor to predict the phoneme sequence. By employing backtracking, you can obtain accurate alignment. This approach yields higher accuracy compared to performing MFA on multiple speakers directly. (ref: https://pytorch.org/audio/main/tutorials/forced_alignment_tutorial.html)

**Comment by Eie1** [comment]
Thanks for your helping. are you Chinese people？could we add friends on WeChat if it's convenient. my WeChat is ：LHN15839379732

**Comment by Eie1** [comment]
dear friend，do you according to  the way  in a large part to align in https://pytorch.org/audio/main/tutorials/forced_alignment_tutorial.html，or only refer partially this method such as getting features by that？Cause I read this page and find it is used for aligning.

Thanks for your replying.Good wishes！

**Comment by JaneStuart-Smith** [comment]
Hi MFA folks, and maybe @mmcauliffe:

I've run `mfa_adapt ` to improve alignment for Scottish children's speech, adapting from `english_us_arpa`, which has done the best job so far. I've got a set of adapted acoustic models, and am trying to use [alignment evaluation](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/implementations/alignment_evaluation.html), to select the 'best' according to the metrics.

I hand-corrected a test dataset of MFA-aligned TextGrids, and put them into a reference directory (ref_dir).
 
I then ran this:
`mfa align --clean input_dir english_us_arpa acoustic_model.zip output_dir --reference_directory ref_dir`
(input_dir and output_dir specify MFA input [TextGrids/.wavs] and output [will be TextGrids]).

MFA is always able to identify all the speakers/utterances, and align and export the TextGrids to the output_dir without a problem. But - as reported at the top of this issue - there is an error when loading the reference files.  I think it is the same error as above, but I paste it here, just in case:
![image (11)](https://github.com/user-attachments/assets/d85fa44e-8519-4df1-8c11-32f0ea473f11)
![image (12)](https://github.com/user-attachments/assets/5b930eba-eb06-481a-858d-3816f61cd567)

With advice from JamesT and MassimoL, I have double-checked the TextGrids in the ref_dir (which are formatted exactly the same as in input_dir, but differ only in that the boundaries are manually corrected). I can confirm that: all phone intervals look correctly filled (in praat), with correct ARPA symbols, there are no stray boundaries, etc. (i.e. I can't visually locate any issue with the start-time of any phone interval). Apparently the TextGrids can also be loaded correctly using  `textgrid `and `praatio` .

However, I still can't get the ref_dir to load.  

Do you have any suggestions for solving the issue, so that I can get the metrics, and discover which acoustic model is optimal?  

I am wondering if there might be an issue if the words/phone labels/boundaries in the ref_dir don't match exactly with those in the input_dir; some of the corrected TextGrids needed e.g. additional phones. Must e.g. the 'words' tier text of the input_dir be exactly the same as that of the ref_dir?

with many thanks, Jane
