### ISSUE TITLE
[BUG] PermissionError

### ISSUE THREAD

**Issue by T1uTiu** [MontrealCorpusTools/Montreal-Forced-Aligner#535]
When I just use any command, even "mfa -version", there is permissionerror.

Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\Scripts\mfa-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 1031, in main
    check_third_party()
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\lib\site-packages\montreal_forced_aligner\utils.py", line 160, in check_third_party
    p = subprocess.run([thirdparty_binary(fn), "--help"], capture_output=True, text=True)
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files (x86)\Anaconda\envs\diffsinger\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] access deny。

**Comment by mmcauliffe** [comment]
One thing to try would be to uninstall the system anaconda installation, go through the [miniconda installation](https://docs.anaconda.com/free/miniconda/), which should install to `C:\Users\username\miniconda3`, and then follow the rest of the instructions https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#general-installation.  That should allow for running conda via the normal command line via "cmd.exe" from start menu.

Other debugging steps, in the environment prompt try running `where compute-mfcc-feats.exe`, if it doesn't print anything, then Kaldi was likely not installed correctly, so I'd recommend just recreating the environment `conda create -n aligner -c conda-forge montreal-forced-aligner` (maybe MFA was installed via pip rather than conda?).  If it's a permission issue from some administrator elevation at some point, then a differently named environment might be necessary (`conda create -n aligner2 -c conda-forge montreal-forced-aligner`).  It should be possible to run the anaconda prompt as administrator generally though via right clicking it in the start menu, or tracking down where the exe is.  Generally though, I'd avoid this and try to get it installed via a User installation of miniconda since MFA doesn't require access to system files and it's best not to grant those permissions if they're not necessary.
