### ISSUE TITLE
[BUG] Postgres error about `extension "vector" is not available`

### ISSUE THREAD

**Issue by JoFrhwld** [MontrealCorpusTools/Montreal-Forced-Aligner#552]
**Debugging checklist**

[x] Have you updated to latest MFA version?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

From a fresh conda install, `mfa align...` returns a very long error that seems to reference Postgres.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? English
   * How many files/speakers? 1
   * Are you using lab files or TextGrid files for input? Textgrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? english_us_arpa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? english_us_arpa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

[to_align.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10680146/to_align.log)

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 12.6.1
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
Add any other context about the problem here

```
❯ mfa align ~/Documents/misc_repos/vowelentines_day/to_align english_us_arpa english_us_arpa test_align
ERROR - There was an error in the run, please see the log.
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x14971bc40>>
Traceback (most recent call last):
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 93, in history_save_handler
    raise self.exception
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/bin/mfa", line 11, in <module>
    sys.exit(mfa_cli())
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 113, in align_corpus_cli
    aligner.align()
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 411, in align
    self.initialize_database()
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 226, in initialize_database
    conn.execute(sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS vector"))
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/joseffruehwald/opt/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.NotSupportedError: (psycopg2.errors.FeatureNotSupported) extension "vector" is not available
DETAIL:  Could not open extension control file "/Users/joseffruehwald/opt/miniconda3/envs/aligner/share/extension/vector.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.

[SQL: CREATE EXTENSION IF NOT EXISTS vector]
(Background on this error at: https://sqlalche.me/e/20/tw8g)
```

**Comment by mmcauliffe** [comment]
The does seem odd, since it looks like postgres is pointing to the right environment location.  As a test can you create a new environment from scratch and make sure ports don't conflict?

1. `conda create -n mfa python=3.10 montreal-forced-aligner -c conda-forge`
2. `mfa configure --database_port 5433`

If it still isn't working, then maybe try removing the `~/Documents/MFA/pg_mfa_gloabal` as well?

Also if you can attach the `~/Documents/MFA/pg_init_log_global.txt` and `~/Documents/pg_log_global.txt`, that might help narrow down what's going wrong.

**Comment by JoFrhwld** [comment]
Tried a few things and still got the same errors. The `pg_log`s after each step were the same, so I'll stick them up here at the top in case that speeds things up:

After first attempt:

- [pg_init_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10686327/pg_init_log_global.txt)
- [pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10686328/pg_log_global.txt)

After second attempt

- [pg_init_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10686333/pg_init_log_global.txt)
- [pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10686334/pg_log_global.txt)

## First attempt

Blew away `~/Documents/MFA` and previous conda environment, reinstalled just according to the readthedocs:

```
conda create -n aligner -c conda-forge montreal-forced-aligner
conda activate aligner
mfa model download acoustic english_us_arpa
mfa model download dictionary english_us_arpa
mfa align ~/Documents/misc_repos/vowelentines_day/to_align english_us_arpa english_us_arpa test_align
```

Got the same errors

## Second attempt

Blew away `~/Documents/MFA` and re-installed according to your comment:

```
conda create -n mfa python=3.10 montreal-forced-aligner -c conda-forge
conda activate mfa
mfa configure --database_port 5433
mfa model download acoustic english_us_arpa
mfa model download dictionary english_us_arpa
mfa align ~/Documents/misc_repos/vowelentines_day/to_align english_us_arpa english_us_arpa test_align
```

Got the same errors.

## Third attempt

I deleted `pg_mfa_global/` and retried alignment

```
rm -rf ~/Doccuments/MFA/pg_mfa_global
mfa align ~/Documents/misc_repos/vowelentines_day/to_align english_us_arpa english_us_arpa test_align
```

Same errors again. I haven't attached the pg logs for this attempt because it was just the same output concatenated after the the logs from the second attempt.

**Comment by mmcauliffe** [comment]
Right, that makes sense, 2.1 was the big shift to postgres and having the pgvector externsion.  Can you verify A) your miniconda path to the environment is `/Users/joseffruehwald/opt/miniconda3/envs/aligner` and B) that the `vector.control` file is not in the `/Users/joseffruehwald/opt/miniconda3/envs/aligner/share/extension/` folder?

**Comment by JoFrhwld** [comment]
Starting from fresh, it looks like this (yes to the miniconda path, no `vector.control` existing)

```
conda create -n aligner -c conda-forge montreal-forced-aligner
conda activate aligner
which mfa
# /Users/joseffruehwald/opt/miniconda3/envs/aligner/bin/mfa
ls /Users/joseffruehwald/opt/miniconda3/envs/aligner/share/extension | grep vector
# 
```

**Comment by mmcauliffe** [comment]
Ok, this should be fixed up if you run `conda update pgvector montreal-forced-aligner`.

**Comment by JoFrhwld** [comment]
I was able to get it to work on x86_64, modulo a warning that the acoustic model was out of date, and an error *after* the textgrid got written that the server was "terminated abnormally".  I'll leave the info here for reference although it isn't that big a deal for now. I'll open a separate issue with the logs I got for the arm installation.

----

The way I installed:

```
CONDA_SUBDIR=osx-64 conda create -n mfa_x86 montreal-forced-aligner -c conda-forge
conda activate mfa_x86
mfa model download acoustic english_us_arpa
mfa model download dictionary english_us_arpa
```

The error after textgrids were written:

```
INFO - Finished exporting TextGrids to test_align!
INFO - Done! Everything took 90.066 seconds
Traceback (most recent call last):
  File "/Users/joseffruehwald/opt/miniconda3/envs/mfa_x86/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 991, in _finalize_fairy
    fairy._reset(
  File "/Users/joseffruehwald/opt/miniconda3/envs/mfa_x86/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1437, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/joseffruehwald/opt/miniconda3/envs/mfa_x86/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 657, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

The alignment log file looks fine. The`pg_log_global.txt` has a line that says
```
2023-02-09 16:06:07.822 EST [73774] FATAL:  terminating connection due to administrator command
```

[pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10701524/pg_log_global.txt)
