### ISSUE TITLE
[BUG] sqllachemy error, database does not exist during dictionary creation from custom g2p

### ISSUE THREAD

**Issue by rbracco** [MontrealCorpusTools/Montreal-Forced-Aligner#565]
**Debugging checklist**

[X] Have you updated to latest MFA version?
[X] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
I generated a custom g2p dict with `mfa train_g2p lexicon.txt custom_g2p` which producted a custom_english_g2p.zip file, which took about 30 minutes, and all messages indicated success. I then attempted to generate a dictionary with 
`mfa g2p --clean audio_data custom_g2p.zip custom_dict.txt` following the [docs here](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/dictionary_generating.html#mfa-g2p) 

I also tried the same command removing the `.zip` and both commands result in the following error (full stack trace below) `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: FATAL:  database "rob" does not exist`

I'm a new user, not sure if this is a bug or I'm doing something wrong, and I'm happy to provide any information that might help diagnose the issue.

```
ERROR - There was an error in the run, please see the log.
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f249ac45360>>
Traceback (most recent call last):
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 93, in history_save_handler
    raise self.exception
  File "/home/rob/anaconda3/envs/mfa-aligner/bin/mfa", line 11, in <module>
    sys.exit(mfa_cli())
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/g2p.py", line 76, in g2p_cli
    g2p.setup()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/g2p/generator.py", line 744, in setup
    self._load_corpus()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 1262, in _load_corpus
    self.inspect_database()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 146, in inspect_database
    self.initialize_database()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 237, in initialize_database
    with self.db_engine.connect() as conn:
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2410, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1270, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/rob/anaconda3/envs/mfa-aligner/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: FATAL:  database "rob" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**For Reproducing your issue**

1. Corpus structure
   * English data, very small corpus as I'm just trying to get stuff working
   * Audios are MP3, transcripts are .txt
2. Dictionary
   N/A
3. Acoustic model
   N/A

**Log file**

```
2023-02-14 09:48:26.480 EST [1818819] LOG:  database system is shut down
2023-02-14 09:59:55.616 EST [10830] LOG:  starting PostgreSQL 15.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 11.3.0-19) 11.3.0, 64-bit
2023-02-14 09:59:55.616 EST [10830] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2023-02-14 09:59:55.616 EST [10830] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5433"
2023-02-14 09:59:55.617 EST [10837] LOG:  database system was shut down at 2023-02-14 09:48:26 EST
2023-02-14 09:59:55.620 EST [10830] LOG:  database system is ready to accept connections
2023-02-14 09:59:55.803 EST [10865] ERROR:  zero-length delimited identifier at or near """" at character 17
2023-02-14 09:59:55.803 EST [10865] STATEMENT:  CREATE DATABASE "";
2023-02-14 09:59:55.805 EST [10866] FATAL:  database "rob" does not exist
2023-02-14 09:59:55.808 EST [10830] LOG:  received fast shutdown request
2023-02-14 09:59:55.808 EST [10830] LOG:  aborting any active transactions
2023-02-14 09:59:55.809 EST [10830] LOG:  background worker "logical replication launcher" (PID 10840) exited with exit code 1
2023-02-14 09:59:55.809 EST [10835] LOG:  shutting down
2023-02-14 09:59:55.809 EST [10835] LOG:  checkpoint starting: shutdown immediate
2023-02-14 09:59:55.809 EST [10835] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.001 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2023-02-14 09:59:55.837 EST [10830] LOG:  database system is shut down
```

**Desktop (please complete the following information):**
 - Linux (Ubuntu 20.04.5 LTS)

**Additional context**

**Comment by mmcauliffe** [comment]
If you use `./audio_data` instead of `audio_data` or a full path, do you still get the error?  I thought I had fixed it for the case of these relative paths, but maybe not.

**Comment by rbracco** [comment]
Thanks for the response and suggestion, I can confirm that I still get the same error when using `./audio_data` and when using the full path. I also tried the same thing for the other arguments and the error was always the same: `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: FATAL:  database "rob" does not exist`. I believe I found the cause but I'm not sure why it's only happening to me and how we can prevent it for others.

### Summary of What I Found

For some reason, self.identifier is not set in the DatabaseMixin, this causes the database creation to fail, but that error message is suppressed by the code. The code then attempts to connect to a db that doesn't exist. Manually passing a string with the db name in place of self.identifier (in the subprocess.call that creates the db) appears to temporarily solve the problem. 

### Full Notes

I followed the stack trace up to MFA and it looks like in the DatabaseMixin, the `initialize_database` method (code included below) appears to have some issues. First the `exist_check` is computed on line 235, but isn't used until line 242 and in the meantime a database connection is established, that's where my error is. A second issue is that the subprocess that creates the DB pipes errors to NULL so that they are suppressed. Upon removing that I get 

```
createdb: error: database creation failed: ERROR:  zero-length delimited identifier at or near """"
LINE 1: CREATE DATABASE "";
```

Which means `self.identifier` is "". In my error message it appears to be looking for a database called 'rob'. I first tried setting `self.identifier` to 'rob' in `initialize_database` but it caused `AttributeError: can't set attribute 'identifier'` so I then manually changed the `subprocess.call` to be

```
retcode = subprocess.call(
            [
                "createdb",
                f"--port={GLOBAL_CONFIG.current_profile.database_port}",
                "rob",
                # Replaced self.identifier with "rob" above,
            ],
        )
```

and it then appears to work.


```
def initialize_database(self) -> None:
        """
        Initialize the database with database schema
        """
        if self.database_initialized:
            return
        retcode = subprocess.call(
            [
                "createdb",
                f"--port={GLOBAL_CONFIG.current_profile.database_port}",
                self.identifier,
            ],
            stderr=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
        )
        breakpoint()
        exist_check = retcode != 0
        with self.db_engine.connect() as conn:
            conn.execute(sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS vector"))
            conn.execute(sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
            conn.execute(sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS pg_stat_statements"))
            conn.commit()
        self.database_initialized = True
        if exist_check:
            if GLOBAL_CONFIG.current_profile.clean:
                self.clean_working_directory()
                sqlalchemy.orm.session.close_all_sessions()

                MfaSqlBase.metadata.drop_all(self.db_engine)
            else:
                return

        os.makedirs(self.output_directory, exist_ok=True)

        MfaSqlBase.metadata.create_all(self.db_engine)
```

**Comment by rbracco** [comment]
Okay, now I understand why the exist_check and code suppression are how they are, the database is only created once so 
A. if you don't suppress the errors you'll get `error: database creation failed: ERROR:  database "rob" already exists` every time which is annoying. 
B. The logic surrounding exist_check makes sense.

**Comment by mmcauliffe** [comment]
Can you try updating to the latest 2.2? The migration to use pathlib should
result in properly set identifiers (where for corpora it's the name of the
folder, but for some reason using os.path it was giving empty base names
for relative paths)

**Comment by rbracco** [comment]
I can confirm that everything worked in 2.2, closing the issue, thank you for your help.
