### ISSUE TITLE
wave.Error: unknown format: 3

### ISSUE THREAD

**Issue by Kedersha** [MontrealCorpusTools/Montreal-Forced-Aligner#57]
Hi! We recorded some WAVs on Audacity (44.1kHz, mono, 32 bit) and the aligner/possibly Python is not happy about them. We've tried changing the bitrate to 24, to no avail. Any suggestions?

Thanks!

(in case it's needed, here's our command line output when we try to run the MFA:)

```
montreal-forced-aligner user$ bin/mfa_align [corpus] [dictionary] [english model] [output]
Setting up corpus information...
Traceback (most recent call last):
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/command_line/align.py", line 186, in <module>
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/command_line/align.py", line 146, in validate_args
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/command_line/align.py", line 84, in align_corpus
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/corpus.py", line 309, in __init__
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/corpus.py", line 151, in get_sample_rate
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wave.py", line 499, in open
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wave.py", line 163, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wave.py", line 143, in initfp
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wave.py", line 260, in _read_fmt_chunk
wave.Error: unknown format: 3
Failed to execute script align
montreal-forced-aligner user$ 

```

**Comment by mmcauliffe** [comment]
I would try using 16 bit, I've seen this a couple of times, and comes from the limited support the base wave package has for actual wave files, but 16 bit should be standard and supported.

If it's still giving issues from doing that in Audacity, maybe try opening/saving in Praat (default save for Praat is 16 bit), since I can verify that works.

**Comment by Kedersha** [comment]
Fantastic, we'll try that. Thanks!

**Comment by gaurav-pendhari** [comment]
Try using 16  bit with wave.open function .You will be able to get all the required parameters.
Refer the sample code for reference .


wf = wave.open('filename.wav')

wf.getnchannels() 
# number of channels

wf.getframerate() 
# frame rate (number of frames per second)

wf.getnframes() 
# total number of frames (length of signal)

wf.getsampwidth() 
# number of bytes per frame

**Comment by fnunnari** [comment]
Same problem here: `wave.Error: unknown format: 3` on a file created with Audacity.
Saving with 16 bit doesn't work.
Is it possible to get the wav files in the correct format using `sox`?
