### ISSUE TITLE
[BUG] Crash Upon Attempting to Tokenize Japanese CommonVoice Corpus

### ISSUE THREAD

**Issue by cmlong02** [MontrealCorpusTools/Montreal-Forced-Aligner#572]
**Debugging checklist**

[✓] Have you updated to latest MFA version?
[✓] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

After using Whisper to separate the CommonVoice into speakers and generate .lab files, I attempted to tokenize the corpus in preparation for forced alignment. This results in the following crash:

```
(aligner) C:\Users\caleb>mfa tokenize C:\Users\caleb\Desktop\cv-corpus-12.0-2022-12-07\ja japanese_mfa C:\Users\caleb\Desktop\Output
DEBUG - Beginning run for ja
DEBUG - Using "global" profile
DEBUG - Using multiprocessing with 24
DEBUG - Set up logger for MFA version: 2.2.0
DEBUG - Cleaned previous run
INFO - Setting up corpus information...
DEBUG - Could not load from temp
INFO - Loading corpus from source files...
 96%|█████████████████████████████████████████████████████████████████████▊   | 53140/55576 [00:36<00:00, 10671.75it/s]DEBUG - Waiting for workers to finish...
100%|██████████████████████████████████████████████████████████████████████████| 55576/55576 [00:42<00:00, 1307.22it/s]
DEBUG - Parsed corpus directory with 24 jobs in 42.693 seconds
ERROR - There was an error in the run, please see the log.
waiting for server to shut down.... done
server stopped
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x000002922180E4D0>>
Traceback (most recent call last):
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 95, in history_save_handler
    raise self.exception
  File "C:\Users\caleb\miniconda3\envs\aligner\Scripts\mfa-script.py", line 10, in <module>
    sys.exit(mfa_cli())
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\tokenize.py", line 68, in tokenize_cli
    tokenizer.setup()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\tokenization\tokenizer.py", line 139, in setup
    self._load_corpus()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 1276, in _load_corpus
    self._load_corpus_from_source_mp()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\text_corpus.py", line 131, in _load_corpus_from_source_mp
    self._finalize_load(session, import_data)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 586, in _finalize_load
    session.execute(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\orm\session.py", line 2229, in execute
    return self._execute_internal(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\orm\session.py", line 2133, in _execute_internal
    result = conn.execute(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1837, in _execute_context
    return self._exec_insertmany_context(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2103, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2100, in _exec_insertmany_context
    dialect.do_execute(cursor, sub_stmt, sub_params, context)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.ProgramLimitExceeded) index row requires 157584 bytes, maximum size is 8191

[SQL: INSERT INTO utterance (id, begin, "end", channel, num_frames, text, oovs, normalized_text, normalized_character_text, in_subset, ignored, file_id, speaker_id, job_id) VALUES (%(id__0)s, %(begin__0)s, %(end__0)s, %(channel__0)s, %(num_frames__0)s, %(t ... 268282 characters truncated ... 999)s, %(in_subset__999)s, %(ignored__999)s, %(file_id__999)s, %(speaker_id__999)s, %(job_id__999)s)]
[parameters: {'normalized_text__0': '', 'text__0': '私は彼らの行いのすべてのを教えた。', 'id__0': 14001, 'normalized_character_text__0': '', 'file_id__0': 14001, 'job_id__0': 1, 'oovs__0': '', 'speaker_id__0': 280, 'in_subset__0': False, 'channel__0': 0, 'begin__0': 0, 'num_frames__0': None, 'ignored__0': False, 'end__0': -1, 'normalized_text__1': '', 'text__1': 'スミスの死後、ブリガム・ヤングは彼らの使用を承認した。', 'id__1': 14002, 'normalized_character_text__1': '', 'file_id__1': 14002, 'job_id__1': 1, 'oovs__1': '', 'speaker_id__1': 280, 'in_subset__1': False, 'channel__1': 0, 'begin__1': 0, 'num_frames__1': None, 'ignored__1': False, 'end__1': -1, 'normalized_text__2': '', 'text__2': 'おじいさんはその意味を、にやりとした表情でほのめかします。', 'id__2': 14003, 'normalized_character_text__2': '', 'file_id__2': 14003, 'job_id__2': 1, 'oovs__2': '', 'speaker_id__2': 280, 'in_subset__2': False, 'channel__2': 0, 'begin__2': 0, 'num_frames__2': None, 'ignored__2': False, 'end__2': -1, 'normalized_text__3': '', 'text__3': '彼は近くの競馬場までキャプテンを迎えに行った。', 'id__3': 14004, 'normalized_character_text__3': '', 'file_id__3': 14004, 'job_id__3': 1, 'oovs__3': '', 'speaker_id__3': 280 ... 13900 parameters truncated ... 'oovs__996': '', 'speaker_id__996': 280, 'in_subset__996': False, 'channel__996': 0, 'begin__996': 0, 'num_frames__996': None, 'ignored__996': False, 'end__996': -1, 'normalized_text__997': '', 'text__997': '音楽の性質は、アンビエントスピードメタルでした。', 'id__997': 14998, 'normalized_character_text__997': '', 'file_id__997': 14998, 'job_id__997': 1, 'oovs__997': '', 'speaker_id__997': 280, 'in_subset__997': False, 'channel__997': 0, 'begin__997': 0, 'num_frames__997': None, 'ignored__997': False, 'end__997': -1, 'normalized_text__998': '', 'text__998': 'サングラスと帽子をかぶった男性がマイクに向かって歌っています', 'id__998': 14999, 'normalized_character_text__998': '', 'file_id__998': 14999, 'job_id__998': 1, 'oovs__998': '', 'speaker_id__998': 280, 'in_subset__998': False, 'channel__998': 0, 'begin__998': 0, 'num_frames__998': None, 'ignored__998': False, 'end__998': -1, 'normalized_text__999': '', 'text__999': '建設は、マーサー・ティドビルの外れから始まりました。', 'id__999': 15000, 'normalized_character_text__999': '', 'file_id__999': 15000, 'job_id__999': 1, 'oovs__999': '', 'speaker_id__999': 280, 'in_subset__999': False, 'channel__999': 0, 'begin__999': 0, 'num_frames__999': None, 'ignored__999': False, 'end__999': -1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**For Reproducing your issue**

1. Corpus structure
   * What language is the corpus in?
       * Japanese
   * How many files/speakers?
      * 43,399
   * Are you using lab files or TextGrid files for input?
      * .lab
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
       * japanese_mfa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10762284/pg_log_global.txt)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux]
     - Windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc
     - Windows 11 Education Edition
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
This occurred when attempting to tokenize the Japanese Common Voice Corpus 12.0

**Comment by mmcauliffe** [comment]
Ah right, I think I've seen something like this elsewhere when there are `.txt` files that are too big in the corpus directory.  If you have any of those, try moving them out of the corpus directory, and I'll switch it over to only look at files with a sound file pair.

**Comment by cmlong02** [comment]
Thank you for the swift response! There were the .tsv files that came with the corpus; I deleted them and ran it again, giving this result:

```
(aligner) C:\Users\caleb>mfa tokenize C:\Users\caleb\Desktop\cv-corpus-12.0-2022-12-07\ja japanese_mfa Desktop\Output\
DEBUG - Beginning run for ja
DEBUG - Using "global" profile
DEBUG - Using multiprocessing with 24
DEBUG - Set up logger for MFA version: 2.2.0
DEBUG - Cleaned previous run
INFO - Setting up corpus information...
DEBUG - Could not load from temp
INFO - Loading corpus from source files...
 99%|███████████████████████████████████████████████████████████████████████▉ | 54792/55576 [00:11<00:00, 28312.51it/s]DEBUG - Waiting for workers to finish...
100%|██████████████████████████████████████████████████████████████████████████| 55576/55576 [00:16<00:00, 3378.39it/s]
DEBUG - Parsed corpus directory with 24 jobs in 16.544 seconds
ERROR - There was an error in the run, please see the log.
waiting for server to shut down.... done
server stopped
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x000001E8F105E4D0>>
Traceback (most recent call last):
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 95, in history_save_handler
    raise self.exception
  File "C:\Users\caleb\miniconda3\envs\aligner\Scripts\mfa-script.py", line 10, in <module>
    sys.exit(mfa_cli())
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\tokenize.py", line 68, in tokenize_cli
    tokenizer.setup()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\tokenization\tokenizer.py", line 139, in setup
    self._load_corpus()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 1276, in _load_corpus
    self._load_corpus_from_source_mp()
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\text_corpus.py", line 131, in _load_corpus_from_source_mp
    self._finalize_load(session, import_data)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\base.py", line 586, in _finalize_load
    session.execute(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\orm\session.py", line 2229, in execute
    return self._execute_internal(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\orm\session.py", line 2133, in _execute_internal
    result = conn.execute(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 1837, in _execute_context
    return self._exec_insertmany_context(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2103, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\base.py", line 2100, in _exec_insertmany_context
    dialect.do_execute(cursor, sub_stmt, sub_params, context)
  File "C:\Users\caleb\miniconda3\envs\aligner\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.ProgramLimitExceeded) index row requires 157584 bytes, maximum size is 8191

[SQL: INSERT INTO utterance (id, begin, "end", channel, num_frames, text, oovs, normalized_text, normalized_character_text, in_subset, ignored, file_id, speaker_id, job_id) VALUES (%(id__0)s, %(begin__0)s, %(end__0)s, %(channel__0)s, %(num_frames__0)s, %(t ... 268282 characters truncated ... 999)s, %(in_subset__999)s, %(ignored__999)s, %(file_id__999)s, %(speaker_id__999)s, %(job_id__999)s)]
[parameters: {'begin__0': 0, 'file_id__0': 15001, 'in_subset__0': False, 'end__0': -1, 'speaker_id__0': 131, 'channel__0': 0, 'id__0': 15001, 'normalized_character_text__0': '', 'text__0': 'あなたは不正直であることでさえ正直でありませんでした。', 'num_frames__0': None, 'normalized_text__0': '', 'job_id__0': 1, 'oovs__0': '', 'ignored__0': False, 'begin__1': 0, 'file_id__1': 15002, 'in_subset__1': False, 'end__1': -1, 'speaker_id__1': 131, 'channel__1': 0, 'id__1': 15002, 'normalized_character_text__1': '', 'text__1': '雇用期間の停止期間に及ぶ補償金も受け取った。', 'num_frames__1': None, 'normalized_text__1': '', 'job_id__1': 1, 'oovs__1': '', 'ignored__1': False, 'begin__2': 0, 'file_id__2': 15003, 'in_subset__2': False, 'end__2': -1, 'speaker_id__2': 131, 'channel__2': 0, 'id__2': 15003, 'normalized_character_text__2': '', 'text__2': '彼女はブラウナウ近くの小さな村、ランスホーフェンへ移り住んだ。', 'num_frames__2': None, 'normalized_text__2': '', 'job_id__2': 1, 'oovs__2': '', 'ignored__2': False, 'begin__3': 0, 'file_id__3': 15004, 'in_subset__3': False, 'end__3': -1, 'speaker_id__3': 131, 'channel__3': 0, 'id__3': 15004, 'normalized_character_text__3': '' ... 13900 parameters truncated ... 'id__996': 15997, 'normalized_character_text__996': '', 'text__996': 'でも、世間から評価されているので、私は目を伏せるのだ。', 'num_frames__996': None, 'normalized_text__996': '', 'job_id__996': 1, 'oovs__996': '', 'ignored__996': False, 'begin__997': 0, 'file_id__997': 15998, 'in_subset__997': False, 'end__997': -1, 'speaker_id__997': 131, 'channel__997': 0, 'id__997': 15998, 'normalized_character_text__997': '', 'text__997': '最初の毛虫はすぐにちぎれます。', 'num_frames__997': None, 'normalized_text__997': '', 'job_id__997': 1, 'oovs__997': '', 'ignored__997': False, 'begin__998': 0, 'file_id__998': 15999, 'in_subset__998': False, 'end__998': -1, 'speaker_id__998': 131, 'channel__998': 0, 'id__998': 15999, 'normalized_character_text__998': '', 'text__998': 'その暮らしは牧師館、教会所属地のワイルドモァ・フェンで営まれた。', 'num_frames__998': None, 'normalized_text__998': '', 'job_id__998': 1, 'oovs__998': '', 'ignored__998': False, 'begin__999': 0, 'file_id__999': 16000, 'in_subset__999': False, 'end__999': -1, 'speaker_id__999': 131, 'channel__999': 0, 'id__999': 16000, 'normalized_character_text__999': '', 'text__999': '地域の学校のクリスマスパージェントのレビュー。', 'num_frames__999': None, 'normalized_text__999': '', 'job_id__999': 1, 'oovs__999': '', 'ignored__999': False}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
[pg_log_global.txt](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/10762698/pg_log_global.txt)

**Comment by mmcauliffe** [comment]
Hmm, it still looks like it's trying to insert a something formatted like the TSVs in there, can you see if there's any files with `*.txt` that might have the same info, maybe generated as part of whatever you did with whisper?
