### ISSUE TITLE
[BUG] MFA 2.2.4 - sqlalchemy.exc.OperationalError: index row over maximum size

### ISSUE THREAD

**Issue by HikaruNoTsubasa** [MontrealCorpusTools/Montreal-Forced-Aligner#586]
**Debugging checklist**

- [x] Have you updated to latest MFA version?
MFA version 2.2.4
- [x] Have you tried rerunning the command with the `--clean` flag?
always using `--clean`

**Describe the issue**
Hello, I started using MFA from version 2.0.6 and was able to successfully align most of the audio and text files. However, since upgrading to the next version, it has not been working properly, even with the current version 2.2.4.

When I run `mfa validate` or `mfa align`, I almost always encounter errors related to SQL. Please refer to the log content below for more details.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
     * Chinese
   * How many files/speakers?
     * 1file or 2+ files/1speaker
   * Are you using lab files or TextGrid files for input?
     * .txt file
2. Dictionary
  mandarin_taiwan_mfa
3. Acoustic model
  mandarin_mfa

**Log file**
`Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f0b320bf4f0>>
Traceback (most recent call last):
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 97, in history_save_handler
    raise self.exception
  File "/home/sai/miniconda3/envs/aligner/bin/mfa", line 11, in <module>
    sys.exit(mfa_cli())
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/validate.py", line 113, in validate_corpus_cli
    validator.validate()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 595, in validate
    self.setup()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 548, in setup
    self._load_corpus()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 1280, in _load_corpus
    self._load_corpus_from_source_mp()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1030, in _load_corpus_from_source_mp
    self._finalize_load(session, import_data)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/corpus/base.py", line 586, in _finalize_load
    session.execute(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2133, in _execute_internal
    result = conn.execute(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1837, in _execute_context
    return self._exec_insertmany_context(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2103, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2100, in _exec_insertmany_context
    dialect.do_execute(cursor, sub_stmt, sub_params, context)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.ProgramLimitExceeded) index row requires 14256 bytes, maximum size is 8191`

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: WSL2 -  Ubuntu 22.04

**Comment by mmcauliffe** [comment]
How long are you audio files?  Since you're using mandarin, have you done any tokenization of the text?  The training pass used tokenization from https://github.com/explosion/spacy-pkuseg/, so I would recommend that if you have not tokenized it.  I want to do a pass over the mandarin models soon, once I have Japanese in a good place, and that update should include tokenization automatically.

**Comment by HikaruNoTsubasa** [comment]
The length of my audio file is approximately 30 to 40 minutes, and the method of text segmentation is to separate each Chinese character with a line break (\n).

> Note: This type of operation can work properly in MFA 2.0.6.

**Comment by mmcauliffe** [comment]
Can you try upgrading to 2.2.5 and rerunning? I've removed the index that was likely causing this issue.

**Comment by HikaruNoTsubasa** [comment]
> Can you try upgrading to 2.2.5 and rerunning? I've removed the index that was likely causing this issue.

Hello, I'm currently using version 2.2.6 of MFA and the original error has been resolved. However, a problem similar to #587 has appeared, and the error log is as follows.
---
```ERROR    There was an error in the run, please see the log.
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7fe59c6a94b0>>
Traceback (most recent call last):
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 102, in history_save_handler
    raise self.exception
  File "/home/sai/miniconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/validate.py", line 113, in validate_corpus_cli
    validator.validate()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 602, in validate
    self.train()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 529, in train
    trainer.train()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 494, in train
    self.train_iteration()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 466, in train_iteration
    self.align_iteration()
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 439, in align_iteration
    self.align_utterances(training=True)
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/mixins.py", line 436, in align_utterances
    for utterance, log_likelihood in run_kaldi_function(
  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/utils.py", line 753, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 1 encountered an error:
Traceback (most recent call last):

  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 89, in run
    yield from self._run()

  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 957, in _run
    self.check_call(align_proc)

  File "/home/sai/miniconda3/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 116, in check_call
    raise KaldiProcessingError([self.log_path])

montreal_forced_aligner.exceptions.KaldiProcessingError: KaldiProcessingError:

There were 1 job(s) with errors when running Kaldi binaries.
See the log files below for more information.
/home/sai/Documents/MFA/output/monophone/log/align.1.1.log
/home/sai/miniconda3/envs/aligner/bin/gmm-boost-silence --boost=1.25 1 /home/sai/Documents/MFA/output/monophone/1.mdl -
LOG (gmm-boost-silence[5.5.1016]:main():gmmbin/gmm-boost-silence.cc:93) Boosted weights for 5 pdfs, by factor of 1.25
/home/sai/miniconda3/envs/aligner/bin/gmm-align-compiled --transition-scale=1.0 --acoustic-scale=0.1 --self-loop-scale=0.1 --beam=6 --retry-beam=40 --careful=false --write-per-frame-acoustic-loglikes=ark:/home/sai/Documents/MFA/output/monophone/like.1.1.ark - ark,s,cs:/home/sai/Documents/MFA/output/monophone/fsts.1.1.ark 'ark,s,cs:add-deltas scp,s,cs:"/home/sai/Documents/MFA/output/output/split1/feats.1.1.scp" ark:- |' ark:/home/sai/Documents/MFA/output/monophone/ali.1.1.ark ark,t:-
LOG (gmm-boost-silence[5.5.1016]:main():gmmbin/gmm-boost-silence.cc:103) Wrote model to -
add-deltas scp,s,cs:/home/sai/Documents/MFA/output/output/split1/feats.1.1.scp ark:-
LOG (gmm-align-compiled[5.5.1016]:main():gmmbin/gmm-align-compiled.cc:127) 1-1
WARNING (gmm-align-compiled[5.5.1016]:AlignUtteranceWrapper():decoder/decoder-wrappers.cc:617) Retrying utterance 1-1 with beam 40
WARNING (gmm-align-compiled[5.5.1016]:AlignUtteranceWrapper():decoder/decoder-wrappers.cc:626) Did not successfully decode file 1-1, len = 244098
LOG (gmm-align-compiled[5.5.1016]:main():gmmbin/gmm-align-compiled.cc:135) Overall log-likelihood per frame is -nan over 0 frames.
LOG (gmm-align-compiled[5.5.1016]:main():gmmbin/gmm-align-compiled.cc:137) Retried 1 out of 1 utterances.
LOG (gmm-align-compiled[5.5.1016]:main():gmmbin/gmm-align-compiled.cc:139) Done 0, errors on 1
