### ISSUE TITLE
The global MFA database server does not exist, initializing it first.

### ISSUE THREAD

**Issue by Tang19999991** [MontrealCorpusTools/Montreal-Forced-Aligner#595]
The global MFA database server does not exist, initializing it first.

Traceback (most recent call last):
  File "/home/siying/anaconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(mfa_cli())
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 142, in mfa_cli
    start_server()
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/utils.py", line 408, in start_server
    initialize_server()
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/utils.py", line 308, in initialize_server
    initdb_proc = subprocess.Popen(
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/siying/anaconda3/envs/aligner/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'initdb'

This error occurs when I process "mfa align" or "mfa train" command. It seems I need to initialize the aligner but I have no idea what to do...

**Comment by Fhrozen** [comment]
@mmcauliffe I observe the same error when using conda + pip in version 2.2.15. It would be helpful to know where these programs belong, to which pip package/framework, so it can be checked if there are correctly installed.
It this belongs to SQLAlchemy or another package?
