### ISSUE TITLE
[BUG] The global MFA database server does not exist, initializing it first.

### ISSUE THREAD

**Issue by orantake** [MontrealCorpusTools/Montreal-Forced-Aligner#598]
```
The global MFA database server does not exist, initializing it first.
pg_ctl stdout: 
pg_ctl stderr: initdb: error: cannot be run as root
initdb: hint: Please log in (using, e.g., "su") as the (unprivileged) user that will own the server process.

Traceback (most recent call last):
  File "/home/work/miniconda/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 142, in mfa_cli
    start_server()
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/utils.py", line 408, in start_server
    initialize_server()
  File "/home/work/miniconda/envs/aligner/lib/python3.10/site-packages/montreal_forced_aligner/command_line/utils.py", line 320, in initialize_server
    raise DatabaseError(
montreal_forced_aligner.exceptions.DatabaseError: DatabaseError:

There was an error encountered starting the global MFA database server, please see /root/Documents/MFA/pg_init_log_global.txt for more details and/or look at the logged errors above.

```

After updating previous issue in #589, now the new error message arose.

**Comment by yyz845935161** [comment]
I have meet this error，but It hasn't been resolved yet
