### ISSUE TITLE
permission denied when write phone dict

### ISSUE THREAD

**Issue by 1nlplearner** [MontrealCorpusTools/Montreal-Forced-Aligner#605]
install mfa from docker

Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 102, in history_save_handler
    raise self.exception
  File "/env/bin/mfa", line 8, in <module>
    sys.exit(mfa_cli())
  File "/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 113, in train_acoustic_model_cli
    trainer.export_model(output_model_path)
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 484, in export_model
    self.export_lexicon(
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/dictionary/multispeaker.py", line 1363, in export_lexicon
    with mfa_open(path, "w") as f:
  File "/env/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/helper.py", line 75, in mfa_open
    file = open(path, mode, encoding=encoding, newline=newline)
PermissionError: [Errno 13] Permission denied: 'audio_cut/phone_dict.dict'

**Comment by seongminp** [comment]
I had the same error using the latest Docker image. Try running the command after cd-ing into user home:
```
cd /home/mfauser
# Do whatever
```
