### ISSUE TITLE
There were phones in the dictionary that do not have acoustic models

### ISSUE THREAD

**Issue by Jackiexiao** [MontrealCorpusTools/Montreal-Forced-Aligner#61]
```
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 32289.0
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 146, in validate_args
  File "aligner/command_line/align.py", line 88, in align_corpus
  File "aligner/models.py", line 129, in validate
aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models: 
Failed to execute script align
```
I check the `meta.yaml` and every phones in the dictionary is in `meta.yaml`

**Comment by Yael-Tiktalk** [comment]
Hi Jackiexiao 
I got the same bug and I checked meta.yaml and all the phones in the dictionary are in meta.yaml. 
Can you please explain how did you solve that problem?

In my case, I had to trained the MFA for having AM for my language, because there is no pre-trained AM for my language. Also I've used MFA for the alignment task many times and it worked just fine with my AM, so I don't understand why do I get this bug now.

Would appreciate your help!
Thank you.

**Comment by snami100** [comment]
Hello, I got the same problem with german models.
Did someone got a hint? Or maybe a solution?

Thanks in advance

**Comment by neriomoran** [comment]
Hello, Im getting the same problem with german models.!

**Comment by neriomoran** [comment]
DEBUG - Loading from source with multiprocessing
DEBUG - Finished adding jobs!
DEBUG - Waiting for workers to finish...
DEBUG - Parsed corpus directory with 15 jobs in 2.6933255195617676 seconds
INFO - Number of speakers in corpus: 1, average number of utterances per speaker: 1000.0
INFO - Parsing dictionary "dictionary_0000" without pronunciation probabilities without
                silence probabilities
PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models: eins1 and ~0
0 minutes and 4 seconds elapsed.

**Comment by bkmackay** [comment]
Hi, has anyone found out what the issue is here/ how to fix it? I'm also having problems with the German acoustic model

**Comment by mmcauliffe** [comment]
Are you still getting this on the latest version?  It should have been fixed in [2.0.0b10](https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_2.0.html#b10)

**Comment by bkmackay** [comment]
Yeah I've got 2.0.0rc3, it can't seem to find the acoustic models for any of the phones:


  Acoustic model compatibility
  ============================

    36 phones not in acoustic model
    39869 ignored pronunciations

    Phones missing acoustic models:

        aɪ, aʊ, aː, eː, iː, l̩, m̩, n̩, oː, pf, tʃ, uː, y, yː, ç, ø, øː, ŋ, œ, œː, ɐ, ɑː, ɒː, ɔ, ɔʏ, ɔː, ə, ɛ, ɛː, ɡ, ɪ,
       ʁ, ʃ, ʊ, ʏ, and ʔ

**Comment by Florent-Dueme** [comment]
Hi all, 

No solution have been found apparently? I have the same issue with the german model. Or rather I get a warning instead of an exception:

WARNING - There were 313437 pronunciations in the dictionary thatwere ignored for containing one of 61 phones not present in the trained acoustic model.  Please run `mfa validate` to get more details.

But then the textgrids are just random, and all the phones are replaced by "spn". I'm also using version 2.0.0rc3
