### ISSUE TITLE
[BUG] mfa validate Exception: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by abaddon-moriarty** [MontrealCorpusTools/Montreal-Forced-Aligner#611]
**Debugging checklist**

[X] Have you updated to latest MFA version?
[X] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Currently following the [Use Case 1 Steps](https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#aligning-a-speech-corpus-with-existing-pronunciation-dictionary-and-acoustic-model). Running the `mfa validate` command. Exception arises as the server closes, after the model is done training. I'm not sure where the issue comes from.

`mfa validate --clean ./mfa_data/my_corpus/ french_mfa french_mfa`

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? French
   * How many files/speakers? 1 speaker 4 files
   * Are you using lab files or TextGrid files for input? .txt files 
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? [French MFA dictionary v2.0.0a](https://mfa-models.readthedocs.io/en/latest/dictionary/French/French%20MFA%20dictionary%20v2_0_0a.html#french-mfa-dictionary-v2-0-0a) 
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?  [French MFA acoustic model v2.0.0a](https://mfa-models.readthedocs.io/en/latest/acoustic/French/French%20MFA%20acoustic%20model%20v2_0_0a.html#french-mfa-acoustic-model-v2-0-0a) 
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

This is the traceback (attaching the full log if needed)
```
 INFO     Done! Everything took 578.834 seconds
 INFO     Stopping the global MFA database server...
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\munau\.conda\envs\French1Voices\lib\site-packages\sqlalchemy\pool\base.py", line 991, in _finalize_fairy
    fairy._reset(
  File "C:\Users\munau\.conda\envs\French1Voices\lib\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\munau\.conda\envs\French1Voices\lib\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
[validate4.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/11180566/validate4.log)

The pg_log_global.txt contains the following:

```
2023-04-07 19:05:29.996 CEST [23176] LOG:  starting PostgreSQL 15.2, compiled by Visual C++ build 1929, 64-bit
2023-04-07 19:05:30.000 CEST [23176] LOG:  listening on Unix socket "C:/Users/munau/Documents/MFA/pg_mfa_global_socket/.s.PGSQL.5432"
2023-04-07 19:05:30.043 CEST [6904] LOG:  database system was shut down at 2023-04-07 18:51:18 CEST
2023-04-07 19:05:30.071 CEST [23176] LOG:  database system is ready to accept connections
2023-04-07 19:06:44.543 CEST [8180] LOG:  duration: 6187.863 ms  statement: UPDATE word SET count=0
2023-04-07 19:10:30.016 CEST [1432] LOG:  checkpoint starting: time
2023-04-07 19:15:00.219 CEST [1432] LOG:  checkpoint complete: wrote 20684 buffers (63.1%); 0 WAL file(s) added, 0 removed, 32 recycled; write=270.064 s, sync=0.065 s, total=270.204 s; sync files=157, longest=0.002 s, average=0.001 s; distance=518729 kB, estimate=518729 kB
2023-04-07 19:15:09.225 CEST [23176] LOG:  received fast shutdown request
2023-04-07 19:15:09.227 CEST [23176] LOG:  aborting any active transactions
2023-04-07 19:15:09.227 CEST [19136] FATAL:  terminating connection due to administrator command
2023-04-07 19:15:09.227 CEST [8180] FATAL:  terminating connection due to administrator command
2023-04-07 19:15:09.232 CEST [23176] LOG:  background worker "logical replication launcher" (PID 5728) exited with exit code 1
2023-04-07 19:15:09.247 CEST [1432] LOG:  shutting down
2023-04-07 19:15:09.248 CEST [1432] LOG:  checkpoint starting: shutdown immediate
2023-04-07 19:15:09.283 CEST [1432] LOG:  checkpoint complete: wrote 82 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.025 s, total=0.037 s; sync files=56, longest=0.002 s, average=0.001 s; distance=469 kB, estimate=466903 kB
2023-04-07 19:15:09.322 CEST [23176] LOG:  database system is shut down
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] Windows 11
 - Any other details about the setup (Cloud, Docker, etc) The command runs on files which are on a OneDrive ?

**Additional context**

**Comment by mmcauliffe** [comment]
Thanks for reporting this, it won't affect anything internal to MFA, as it's just complaining about a maintenance worker in postgresql being interrupted, but if you'd like to get rid of them you can manage the server lifecycle yourself via `mfa configure --disable_auto_server` (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/index.html#cmdoption-mfa-configure-enable_auto_server), and using the `mfa server` commands here: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/server/index.html#managing-mfa-database-servers.  I'll look into ways to prevent/silence the error though, but again, shouldn't affect any of the MFA commands you run.
