### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by zuihaodeyujian** [MontrealCorpusTools/Montreal-Forced-Aligner#620]
**Debugging checklist**

[yes ] Have you updated to latest MFA version?
[ yes] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
The installation failed using both the pip and conda commands;
method1:
conda create -n aligner -c conda-forge montreal-forced-aligner
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::appdirs-1.4.4-pyh9f0ad1d_0'.
FileNotFoundError(2, "No such file or directory: '/home/guona/.conda/envs/aligner/bin/python3.1'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/home/guona/.conda/envs/aligner/bin/python3.1'")
method 2:
conda create -n aligner kaldi pynini
conda activate aligner
pip install montreal-forced-aligner
(aligner) guona@node01:~$ mfa
Traceback (most recent call last):
  File "/home/guona/.conda/envs/aligner/bin/mfa", line 5, in <module>
    from montreal_forced_aligner.command_line.mfa import mfa_cli
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/__init__.py", line 6, in <module>
    import montreal_forced_aligner.command_line as command_line
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/__init__.py", line 12, in <module>
    from montreal_forced_aligner.command_line.diarize_speakers import diarize_speakers_cli
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/diarize_speakers.py", line 12, in <module>
    from montreal_forced_aligner.diarization.speaker_diarizer import SpeakerDiarizer
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/diarization/speaker_diarizer.py", line 59, in <module>
    from montreal_forced_aligner.diarization.multiprocessing import (
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/diarization/multiprocessing.py", line 15, in <module>
    import hdbscan
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/guona/.conda/envs/aligner/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 9, in <module>
    from sklearn.base import BaseEstimator, ClusterMixin
ModuleNotFoundError: No module named 'sklearn.base'

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
   * How many files/speakers?
   * Are you using lab files or TextGrid files for input?
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [Ubuntu 16.04.1]
 - montreal-forced-aligner=2.2.9

**Additional context**
Please guide me on the specific installation details, thank you!

**Comment by harshita19244** [comment]
How was the error resolved? My install is failing with this error
