### ISSUE TITLE
[BUG] mfa diarize will fail with error missing attribute

### ISSUE THREAD

**Issue by Whyki** [MontrealCorpusTools/Montreal-Forced-Aligner#622]
**Debugging checklist**

[x] Have you updated to latest MFA version?  Yes, v 2.2.9
[x] Have you tried rerunning the command with the `--clean` flag? Yes running from fresh docker. 

**Describe the issue**
When trying to use `mfa diarize` on corpus, it fails with AttributeError. 

Command used:
```
 mfa diarize train_data_diarize /home/mfauser/Documents/MFA/pretrained_models/ivector/multilingual_mfa.zip train_data_diarize_out
```
Console output:
```
server started
 WARNING  Skipped the following configuration keys: ivector_dimension
 INFO     Setting up corpus information...
 INFO     Loading corpus from source files...
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21,109/100  [ 0:00:00 < 0:00:00 , 2,421 it/s ]
 INFO     Found 1 speaker across 21128 files, average number of utterances per speaker: 21128.0
 INFO     Initializing multiprocessing jobs...
 WARNING  Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs. Use the --single_speaker flag if you would like to split utterances across jobs regardless of their speaker.
 INFO     Creating corpus split for feature generation...
  88% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━ 37,382/42,256  [ 0:00:02 < 0:00:01 , 50,431 it/s ]
 INFO     Generating MFCCs...
  67% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14,243/21,128  [ 0:06:13 < 0:03:04 , 37 it/s ]
  88% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 18,667/21,128  [ 0:08:13 < 0:01:05 , 38 it/s ]
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 21,127/21,128  [ 0:09:18 < 0:00:01 , 39 it/s ]
 INFO     Calculating CMVN...
 INFO     Generating final features...
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 21,116/21,128  [ 0:00:36 < 0:00:01 , 600 it/s ]
 INFO     Creating corpus split with features...
  78% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16,568/21,128  [ 0:00:01 < 0:00:01 , 55,230 it/s ]
 INFO     Extracting ivectors...
  71% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14,968/21,128  [ 0:03:08 < 0:01:09 , 90 it/s ]
  74% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15,553/21,128  [ 0:03:14 < 0:01:01 , 92 it/s ]
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 21,126/21,128  [ 0:04:23 < 0:00:01 , 86 it/s ]
 INFO     Collecting ivectors...
  96% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 20,326/21,128  [ 0:00:05 < 0:00:01 , 13,541 it/s ]
 INFO     Computing speaker ivectors...
 INFO     Collecting speaker ivectors...
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:00:00 < -:--:-- , ? it/s ]
 INFO     Generating initial speaker labels...
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 21,127/21,128  [ 0:09:01 < 0:00:01 , 40 it/s ]
 INFO     Breaking up large speakers...
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:00:14 < -:--:-- , ? it/s ]
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:00:16 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.
 INFO     Stopping the global MFA database server...
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f650776ebf0>>
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 97, in history_save_handler
    raise self.exception
  File "/env/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params) 
  File "/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/diarize_speakers.py", line 115, in diarize_speakers_cli
    classifier.cluster_utterances()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/diarization/speaker_diarizer.py", line 1079, in cluster_utterances
    self.cluster_utterances_mfa()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/diarization/speaker_diarizer.py", line 1002, in cluster_utterances_mfa
    self.initialize_mfa_clustering()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/diarization/speaker_diarizer.py", line 749, in initialize_mfa_clustering
    self.breakup_large_clusters()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/diarization/speaker_diarizer.py", line 938, in breakup_large_clusters
    label = self._unknown_speaker_break_up_count   
AttributeError: 'SpeakerDiarizer' object has no attribute '_unknown_speaker_break_up_count'

AttributeError: 'SpeakerDiarizer' object has no attribute '_unknown_speaker_break_up_count'
```

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   *  Czech 
   *  Unknown number of speakers, try to diarize corpus https://mfa-models.readthedocs.io/en/latest/corpus/Czech/VoxPopuli%20Czech.html#VoxPopuli%20Czech
   * Using lab files. 
2. Dictionary
   * N/A
   * N/A
3. Acoustic model
   *using pretrained ivectors  https://mfa-models.readthedocs.io/en/latest/ivector/Multilingual/Multilingual%20MFA%20ivector%20extractor%20v2_1_0.html#Multilingual%20MFA%20ivector%20extractor%20v2_1_0

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - Linux, Docker

**Comment by Whyki** [comment]
Hey, you are just amazing with the speed of bug fixes! Less than 2 hours to have release candidate :-) :+1:

**Comment by mmcauliffe** [comment]
This is me every issue: ![alt text](https://i.imgflip.com/5mxp9f.png?a467040)
