### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChosenOne23** [MontrealCorpusTools/Montreal-Forced-Aligner#631]
The global MFA database server does not exist, initializing it first.
Exception in thread Thread-1 (_readerthread):
Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\aligner\lib\threading.py", line 1016, in _bootstrap_inner
  File "D:\Software\Anaconda3\envs\aligner\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Software\Anaconda3\envs\aligner\lib\threading.py", line 953, in run
    self.run()
  File "D:\Software\Anaconda3\envs\aligner\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\subprocess.py", line 1515, in _readerthread
    self._target(*self._args, **self._kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\subprocess.py", line 1515, in _readerthread
    buffer.append(fh.read())
  File "D:\Software\Anaconda3\envs\aligner\lib\codecs.py", line 322, in decode
    buffer.append(fh.read())
  File "D:\Software\Anaconda3\envs\aligner\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 67: invalid start byte
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 282: invalid start byte
pg_ctl stdout: None
pg_ctl stderr: None
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\aligner\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\Anaconda3\envs\aligner\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Software\Anaconda3\envs\aligner\Scripts\mfa.exe\__main__.py", line 7, in <module>
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\rich_click\rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 140, in mfa_cli
    start_server()
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\utils.py", line 408, in start_server
    initialize_server()
  File "D:\Software\Anaconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\utils.py", line 320, in initialize_server
    raise DatabaseError(
montreal_forced_aligner.exceptions.DatabaseError: DatabaseError:

There was an error encountered starting the global MFA database server, please see C:\Users\林锦濠\Documents\MFA\pg_init_log_global.txt for more details and/or look at the logged errors above.

**Comment by ChosenOne23** [comment]
i use conda to install mfa, the language i use is chinese.

**Comment by mmcauliffe** [comment]
Can you set the following environment variable (via something like https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0): 

```
PYTHONUTF8=1
```

It seems like the console you're running MFA in is causing Python to use a non-UTF8 codec, but the above variable should override that.

**Comment by ChosenOne23** [comment]
> Can you set the following environment variable (via something like https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0):
> 
> ```
> PYTHONUTF8=1
> ```
> 
> It seems like the console you're running MFA in is causing Python to use a non-UTF8 codec, but the above variable should override that.

it didn't work
