### ISSUE TITLE
[BUG] required sqlite

### ISSUE THREAD

**Issue by phamkhactu** [MontrealCorpusTools/Montreal-Forced-Aligner#651]
Thanks for excellent repo.

I have followed tutorial for alignment. I used docker.
But I run comand:
```
mfa align Librispeech/ english_us_mfa english_mfa ./aligned_librispeech
```
I get errors:
```
 ERROR    There was an error in the run, please see the log.                                                                   
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f4c26c28a10>>
Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/montreal_forced_aligner/command_line/mfa.py", line 97, in history_save_handler
    raise self.exception
  File "/env/bin/mfa", line 8, in <module>
    sys.exit(mfa_cli())
             ^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/montreal_forced_aligner/command_line/align.py", line 113, in align_corpus_cli
    aligner.align()
  File "/env/lib/python3.11/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 413, in align
    super().align()
  File "/env/lib/python3.11/site-packages/montreal_forced_aligner/alignment/base.py", line 365, in align
    self.collect_alignments()
  File "/env/lib/python3.11/site-packages/montreal_forced_aligner/alignment/base.py", line 923, in collect_alignments
    subprocess.check_call(
  File "/env/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/env/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
```
Thank you very much!

**Comment by mmcauliffe** [comment]
Can you double check that `sqlite3 --help` returns a help message?

**Comment by phamkhactu** [comment]
> Can you double check that `sqlite3 --help` returns a help message?

yeah, 
The message is: ```bash: sqlite3: command not found```

**Comment by mmcauliffe** [comment]
Can you try running `conda install sqlite`? Not sure why it didn't get picked up with the new version, a fresh install gets it properly for me...

**Comment by mmcauliffe** [comment]
Oh wait this is on docker, I think know what to fix.

**Comment by mmcauliffe** [comment]
Ok the latest dockerfile should have this fixed.

**Comment by phamkhactu** [comment]
@mmcauliffe  Thank you, I've just run the command, but I think maybe I'm wrong in my step to test train func in align 

```
mfa train Librispeech english_us_mfa.dict ~/Documents/test
```
I get error:
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: word.id
[SQL: INSERT INTO word (id, mapping_id, word, count, word_type, included, dictionary_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: [(1, 0, '<eps>', 0, 'silence', 1, 2), (2, 1, "'a", 0, 'clitic', 1, 2), (3, 2, "'d", 0, 'clitic', 1, 2), (4, 3, "'em", 0, 'clitic', 1, 2), (5, 4, "'in", 0, 'clitic', 1, 2), (6, 5, "'ll", 0, 'clitic', 1, 2), (7, 6, "'m", 0, 'clitic', 1, 2), (8, 7, "'n", 0, 'clitic', 1, 2)  ... displaying 10 of 79065 total bound parameter sets ...  (79064, 79063, '<s>', 0, 'disambiguation', 1, 2), (79065, 79064, '</s>', 0, 'disambiguation', 1, 2)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```
Thank you.
