### ISSUE TITLE
FileNotFoundError when using binaries

### ISSUE THREAD

**Issue by rafaelvalle** [MontrealCorpusTools/Montreal-Forced-Aligner#68]
I'm getting a `FileNotFoundError` when running the linux binary. 
The `/home/scratch.adlr-gcf/rafaelvalle/temp/` folder has a config and a log folders but nothing else.

```
~/montreal-forced-aligner$ ./bin/mfa_align /home/scratch.adlr-gcf/audio_denoising/datasets/LJSpeech-1.0/wavs /home/scratch.adlr-gcf/audio_denoising/datasets/librispeech_lexicon/librispeech-lexicon.txt english /home/scratch.adlr-gcf/audio_denoising/datasets/LJSpeech-1.0/wav_alignments -t /home/scratch.adlr-gcf/rafaelvalle/temp/
Setting up corpus information...
30 wav file(s) were ignored because neither a .lab file or a .TextGrid file could be found, please see /home/scratch.adlr-gcf/rafaelvalle/temp/wavs/logging/corpus.log for more information
Number of speakers in corpus: 1, average number of utterances per speaker: 13100.0
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 144, in validate_args
  File "aligner/command_line/align.py", line 139, in align_included_model
  File "aligner/command_line/align.py", line 93, in align_corpus
  File "aligner/aligner/pretrained.py", line 71, in __init__
  File "aligner/aligner/pretrained.py", line 117, in setup
  File "aligner/aligner/base.py", line 80, in setup
  File "aligner/corpus.py", line 970, in initialize_corpus
  File "aligner/corpus.py", line 848, in create_mfccs
  File "aligner/corpus.py", line 859, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/rafaelvalle/temp/wavs/train/mfcc/raw_mfcc.0.scp'
Failed to execute script align
```

**Comment by rafaelvalle** [comment]
Problem is the following: `copy-feats: error while loading shared libraries: libcblas.so.3: cannot open shared object file: No such file or directory`
Closing issue.
