### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zj990712** [MontrealCorpusTools/Montreal-Forced-Aligner#692]
mfa validate /home/yuyin/MFA/corpus /home/yuyin/MFA/dictionary.txt
 INFO     Setting up corpus information...                                      
 INFO     Found 1 speaker across 5 files, average number of utterances per      
          speaker: 5.0                                                          
 INFO     Initializing multiprocessing jobs...                                  
 WARNING  Number of jobs was specified as 3, but due to only having 1 speakers, 
          MFA will only use 1 jobs. Use the --single_speaker flag if you would  
          like to split utterances across jobs regardless of their speaker.     
 INFO     Text already normalized.                                              
 ERROR    There was an error in the run, please see the log.                    
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7fcb2ae150d0>>
Traceback (most recent call last):
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/command_line/mfa.py", line 99, in history_save_handler
    raise self.exception
  File "/home/yuyin/anaconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
             ^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/command_line/validate.py", line 112, in validate_corpus_cli
    validator.validate()
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 505, in validate
    self.setup()
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 475, in setup
    self.write_lexicon_information()
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/dictionary/multispeaker.py", line 1555, in write_lexicon_information
    os.makedirs(d.temp_directory, exist_ok=True)
                ^^^^^^^^^^^^^^^^
  File "/home/yuyin/anaconda3/envs/aligner/lib/python3.11/site-packages/montreal_forced_aligner/db.py", line 505, in temp_directory
    return self.root_temp_directory.joinpath(f"{self.id}_{self.name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'joinpath'

**Comment by Zj990712** [comment]
How to solve this problem

**Comment by mmcauliffe** [comment]
Can you try running it with the `--clean` flag? It looks like there's something wrong with how the cached files.

**Comment by Zj990712** [comment]
Thank you very much for your response; this issue has been resolved according to your answer.
