### ISSUE TITLE
[BUG]can use command:mfa align corpus dict  acoustic out，but can not use python __main__.py align corpus dict  acoustic out

### ISSUE THREAD

**Issue by Eie1** [MontrealCorpusTools/Montreal-Forced-Aligner#697]
**Debugging checklist**

[ ] Have you updated to latest MFA version?
yes
[ ] Have you tried rerunning the command with the `--clean` flag?
yes

**Describe the issue**
I successfully install mfa command line environment , and also  install mfa git code environment 
I can run mfa align --clean corpus dict acoustic out, and get textgrid result
but I can not use python __main__.py align corpus dict acoustic out(I want to debug code in my Mac), the following is the error,  Looking forward to your reply, sincerely yours:

INFO     Setting up corpus information...                                                                                            
 INFO     Loading corpus from source files...                                                                                         
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/100  [ 0:00:06 < -:--:-- , ? it/s ]Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/henan/Desktop/mfa/Montreal-Forced-Aligner-main-2/montreal_forced_aligner/__main__.py", line 6, in <module>
    mfa_cli()
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align.py", line 106, in align_corpus_cli
    aligner = PretrainedAligner(
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 74, in __init__
    self.acoustic_model = AcousticModel(acoustic_model_path)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/montreal_forced_aligner/models.py", line 379, in __init__
    super().__init__(source, root_directory)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/montreal_forced_aligner/models.py", line 133, in __init__
    unpack_archive(source, self.dirname)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/shutil.py", line 1278, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/shutil.py", line 1185, in _unpack_zipfile
    _ensure_directory(targetpath)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/shutil.py", line 1162, in _ensure_directory
    os.makedirs(dirname)
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/henan/Documents/MFA/extracted_models/acoustic/english_us_arpa_acoustic/english_us_arpa'
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/100  [ 0:00:06 < -:--:-- , ? it/s ]Exception ignored in: <function TopLevelMfaWorker.__del__ at 0x7fdb1bde0700>
Traceback (most recent call last):
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/montreal_forced_aligner/abc.py", line 559, in __del__
TypeError: 'NoneType' object is not callable
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/100  [ 0:00:07 < -:--:-- , ? it/s ] ERROR    There was an error in the run, please see the log.                                                                          
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/100  [ 0:00:07 < -:--:-- , ? it/s ]Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table corpus already exists

**Comment by Kiri0824** [comment]
Do you know how to solve this?i got same problem when i use mfa 2.1.7😥
