### ISSUE TITLE
[BUG]sqlite3.OperationalError: table corpus already exists

### ISSUE THREAD

**Issue by Eie1** [MontrealCorpusTools/Montreal-Forced-Aligner#699]
dear author, the tool is nice. 
but I find the same error when run ' python __main__.py train ./data_mytest  english_us_arpa ./data_mytestout.zip' and  run ' python __main__.py align ./data_mytest  english_us_arpa english_us_arpa out'
the error is "sqlite3.OperationalError: table corpus already exists",could you help to have a look? thanks very much.
details are as follows, 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/henan/anaconda3/envs/aligner_mfa/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table corpus already exists

The above exception was the direct cause of the following exception:

**Comment by mmcauliffe** [comment]
Can you try rerunning but with the `--clean` flag added?  That will clean any database tables and cached data from any previous runs.
