### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by fangg2000** [MontrealCorpusTools/Montreal-Forced-Aligner#703]
# mfa version
Traceback (most recent call last):
  File "/home/fangg/tools/anacodna3/envs/mfa/bin/mfa", line 8, in <module>
    sys.exit(mfa_cli())
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 149, in mfa_cli
    check_third_party()
  File "/home/fangg/tools/anacodna3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/utils.py", line 282, in check_third_party
    raise ThirdpartyError("initdb")
montreal_forced_aligner.exceptions.ThirdpartyError: ThirdpartyError:

Could not find 'initdb'.
Please ensure that you have installed MFA's conda dependencies and are in the correct environment.
#

I install mfa like this:

conda install kaldi pynini
pip install montreal-forced-aligner

But it doesn't have 'Thirdparty' command ...

**Comment by fangg2000** [comment]
![2023-10-05 23-59-35屏幕截图](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/131591502/c0b3a34b-e7da-459a-b5c4-fee64c13f4a4)

what the 'initdb' is?

**Comment by Micae1o** [comment]
How did you fix it?

**Comment by mmcauliffe** [comment]
I'd recommend installing everything through conda via `conda install -c conda-forge montreal-forced-aligner` that'll ensure all dependencies are there.  With that said, initdb is from postgresql, which is not strictly required any more, so I'll remove that check when `--use_postgres` isn't specified.

**Comment by blldd** [comment]
We cannot access network with conda, only can install with pip. And met the same error (raise ThirdpartyError("initdb")) 
Do you have any idea how to fix it?

**Comment by blldd** [comment]
> I'd recommend installing everything through conda via `conda install -c conda-forge montreal-forced-aligner` that'll ensure all dependencies are there. With that said, initdb is from postgresql, which is not strictly required any more, so I'll remove that check when `--use_postgres` isn't specified.

We cannot access network with conda, only can install with pip. And met the same error (raise ThirdpartyError("initdb"))
Do you have any idea how to fix it?
