### ISSUE TITLE
no successful alignments

### ISSUE THREAD

**Issue by Oreoluwa1234** [MontrealCorpusTools/Montreal-Forced-Aligner#719]
I am using a swahilli corpus that already has a pretrained acoustic model and dictionary from mfa. 
(mfa_env) C:\Users\user\Downloads\ALL>mfa align C:\Users\user\Downloads\ALL\dev C:\Users\user\Downloads\ALL\MFA\pretrained_models\dictionary\swahili_mfa.dict  C:\Users\user\Downloads\ALL\MFA\swahili_mfa C:\Users\user\Downloads\ALL\Alignments.

I am using miniconda prompt on  windows

this is the error below.

 ERROR    There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\mfa_env\Scripts\mfa-script.py", line 9, in <module>
    sys.exit(mfa_cli())
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\montreal_forced_aligner\command_line\align.py", line 113, in align_corpus_cli
    aligner.align()
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\montreal_forced_aligner\alignment\pretrained.py", line 413, in align
    super().align()
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\montreal_forced_aligner\alignment\base.py", line 350, in align
    self.align_utterances()
  File "C:\Users\user\miniconda3\envs\mfa_env\lib\site-packages\montreal_forced_aligner\alignment\mixins.py", line 447, in align_utterances
    raise NoAlignmentsError(
montreal_forced_aligner.exceptions.NoAlignmentsError: NoAlignmentsError:

There were no successful alignments for 211 utterances.
The current set up used a beam of 10 and a retry beam of 40.
You can try rerunning with a larger beam (i.e. "mfa align ... --beam 100 --retry_beam 400").
If increasing the beam size does not help, then there are likely issues with the corpus, dictionary, or acoustic model, and can be further diagnosed with the "mfa validate" command

**Comment by rukix1ng** [comment]
i also faced with this same issue

**Comment by My-captain** [comment]
same issue

**Comment by maxime-fily** [comment]
Same issue on Russian_mfa

**Comment by miseulkim** [comment]
Has anyone solved this problem???

**Comment by ueiyang2** [comment]
Same issue on Mandarin_mfa
