### ISSUE TITLE
[BUG] DLL load failed while importing _kalpy

### ISSUE THREAD

**Issue by shozuru** [MontrealCorpusTools/Montreal-Forced-Aligner#731]
**Debugging checklist**

[ Yes ] Have you updated to latest MFA version?
[ Yes ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
When I type `mfa version` into the Anaconda Prompt (Miniconda3), I get the following issue:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\aligner\Scripts\mfa-script.py", line 5, in <module>
    from montreal_forced_aligner.command_line.mfa import mfa_cli
  File "C:\ProgramData\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\__init__.py", line 4, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "C:\ProgramData\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\acoustic_modeling\__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "C:\ProgramData\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\acoustic_modeling\base.py", line 12, in <module>
    from _kalpy.gmm import AccumAmDiagGmm
ImportError: DLL load failed while importing _kalpy: The specified module could not be found.

**For Reproducing your issue**
Open Anaconda Prompt (Miniconda3)
`conda activate aligner`
`mfa version`

1. Corpus structure
   * What language is the corpus in?
   * How many files/speakers?
   * Are you using lab files or TextGrid files for input?
4. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset?
5. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [Windows 10]
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**

**Comment by yeungpinghei** [comment]
I'm running into the same issue. May I know how you fixed it?

**Comment by SaurabhKNath** [comment]
Same issue. Please help!

**Comment by Kedersha** [comment]
Same here! Not sure if closed issues always generate notifications, so I'm going to tag @shozuru as well. Do you recall what you did to resolve this issue?

**Comment by mmcauliffe** [comment]
Hi all, I'm having trouble replicating this, but if you can provide the following information, that would help in me tracking down the root cause:

1. What version of Windows are you running? I've only seen reports on Windows 10 so far, and I only have access to Windows 11.
2. For your environment, what is the output of running `conda list`?  Specifically looking at the version of montreal-forced-aligner, kalpy and kaldi.

Can you try out some potential fixes and see if any of them fix the issue:

1. Double check you're using the cpu version of Kaldi, as there was this issue: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/774 (on Linux, and I'm not sure if the issue would manifest as a DLL load error on windows, but it might), so try running `conda install -c conda-forge kaldi=5.5.1112=cpu*`
2. Use mamba as a solver, see the note in https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#general-installation and then run `mamba update -c conda-forge montreal-forced-aligner --update-deps` to make sure everything's up to the latest version (you can try using `--update-deps` with base conda, but I find the environment solving very slow)
3. Re-create an environment with specific versions: `conda create -n aligner -c conda-forge python=3.11 montreal-forced-aligner=3.0.2 kalpy=0.6.2 kaldi=5.5.1112=cpu*`
4. Try environments with different versions of python in case there's some interaction with Windows 10/MSVC versions?

**Comment by shozuru** [comment]
If I remember correctly, I uninstalled and then installed a more stable version.

**Comment by SaurabhKNath** [comment]
Hi Michael, @mmcauliffe, I am using Windows 10 and the versions of montreal-forced-aligner, kalpy, kaldi were 3.0.2, 0.6.3, 5.5.1112 respectively. 

Thanks for sharing the fixes, and the 3rd option fixed the issue of importing _kalpy and allowed me to go to the mfa validate xx step, which was successful. However, when I ran mfa align xx, I got another error called [WinError 183]. Please see the screenshot attached. Do you have any suggestions for fixing this? Thanks a lot. 

PS: I'm working on Assamese using the english_mfa acoustic model. 

![screenshot](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/126633694/fa4738b3-ff57-48bb-b951-b18ab5e4c4e9)

**Comment by HamidMojarrad** [comment]
I am having the same problem. I found the problem in both my Windows and Linux computers. Would you please walk me through the solution? It's really driving me crazy. Downgrading the aligner to a lower version might help but it lacks enough acoustic and dictionary dataset.

**Comment by lcavasso** [comment]
Here's the requested info from one computer that had this issue:

OS: Windows 11 Home Edition 22H2

```
(aligner) PS C:\Users\Abby> conda list
# packages in environment at C:\Users\Abby\miniconda3\envs\aligner:
#
# Name                    Version                   Build  Channel
aom                       3.8.2                h63175ca_0    conda-forge
audioread                 3.0.1            py39hcbf5309_1    conda-forge
baumwelch                 0.3.8                h1c255cb_1    conda-forge
biopython                 1.79             py39ha55989b_3    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0            py39h1f6ef14_0    conda-forge
cudatoolkit               11.8.0              h09e9e62_13    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.9            py39h99910a6_0    conda-forge
dataclassy                1.0.1              pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dlfcn-win32               1.4.1                h63175ca_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
ffmpeg                    6.1.1           gpl_hb766fab_106    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.50.0           py39ha55989b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
getopt-win32              0.1                  hcfcfb64_1    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
graphviz                  9.0.0                h51cb2cd_1    conda-forge
greenlet                  3.0.3            py39h99910a6_0    conda-forge
gts                       0.7.6                h6b5321d_4    conda-forge
harfbuzz                  8.3.0                h7ab893a_0    conda-forge
hdbscan                   0.8.33           py39hd88c2e4_4    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
kaldi                     5.5.1112        cuda118h7ef4547_1    conda-forge
kalpy                     0.6.4           cuda118py39h50aeb40_0    conda-forge
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
kneed                     0.8.5              pyhd8ed1ab_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lame                      3.100             hcfcfb64_1003    conda-forge
lazy_loader               0.3                pyhd8ed1ab_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflac                   1.4.3                h63175ca_0    conda-forge
libgd                     2.3.3                h312136b_9    conda-forge
libglib                   2.80.0               h39d0aa6_1    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
liblapacke                3.9.0              21_win64_mkl    conda-forge
libmad                    0.15.1b           hcfcfb64_1001    conda-forge
libmagma                  2.7.2                h5fa9d3e_2    conda-forge
libmagma_sparse           2.7.2                h5fa9d3e_3    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.2                 hdb24f17_1    conda-forge
librosa                   0.10.1             pyhd8ed1ab_0    conda-forge
libsndfile                1.2.2                h81429f1_1    conda-forge
libsqlite                 3.45.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.12.6               hc3477c8_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
llvmlite                  0.42.0           py39hd28a505_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magma                     2.7.2                h4a06d07_3    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
matplotlib-base           3.8.3            py39hf19769e_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
montreal-forced-aligner   3.0.3              pyhd8ed1ab_0    conda-forge
mpg123                    1.32.4               h63175ca_0    conda-forge
msgpack-python            1.0.7            py39h1f6ef14_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ngram                     1.3.15               h91493d7_2    conda-forge
numba                     0.59.1           py39h6836801_0    conda-forge
numpy                     1.26.4           py39hddb5d58_0    conda-forge
openfst                   1.8.3                h91493d7_2    conda-forge
openh264                  2.4.1                h63175ca_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pango                     1.52.1               h07c897b_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pgvector                  0.6.2                h5ca1f66_0    conda-forge
pgvector-python           0.2.5              pyhe093146_0    conda-forge
pillow                    10.2.0           py39h368b509_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.8.1              pyhd8ed1ab_0    conda-forge
postgresql                16.2                 h94c9ec1_1    conda-forge
praatio                   6.0.0              pyhd8ed1ab_0    conda-forge
psycopg2                  2.9.9            py39h64827e7_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pynini                    2.1.6            py39h1f6ef14_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pysoundfile               0.12.1           pypyhd8ed1ab_1    conda-forge
python                    3.9.19          h4de0772_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pyyaml                    6.0.1            py39ha55989b_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rich-click                1.7.4              pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.2            py39hfa9d973_2    conda-forge
scipy                     1.12.0           py39hddb5d58_2    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sox                       14.4.2            hd569473_1018    conda-forge
soxr                      0.1.3                hcfcfb64_3    conda-forge
soxr-python               0.3.7            py39hd88c2e4_0    conda-forge
sqlalchemy                2.0.29           py39ha55989b_0    conda-forge
sqlite                    3.45.2               hcfcfb64_0    conda-forge
svt-av1                   1.8.0                h63175ca_0    conda-forge
tbb                       2021.11.0            h91493d7_1    conda-forge
threadpoolctl             3.4.0              pyhc1e730c_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.1.1                hcd874cb_0    conda-forge
xorg-libsm                1.2.4                hcd874cb_0    conda-forge
xorg-libx11               1.8.7                hefa74cf_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.17               hcd874cb_0    conda-forge
xorg-libxt                1.3.0                hcd874cb_1    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by camille-lnrs** [comment]
Hey everyone,
I have the same error and the line conda create -n aligner -c conda-forge python=3.11 montreal-forced-aligner=3.0.2 kalpy=0.6.2 kaldi=5.5.1112=cpu* havn't resolved the problem. Any other cues ? I tried all the mentionned solution and mfa works in terminal but not in python, however I do need it to work on python.

OS : Windows 11

Thank you in advanced !

**Comment by mmcauliffe** [comment]
Can you try running `conda update -c montreal-forced-aligner kalpy kaldi=*=cpu* --update-deps`? That will get the latest version that should be synced across all versions.  From 3.0.5 onward, there is a `mfa_update` command you can run that will get the latest versions of everything, see: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#updating-montreal-forced-aligner

**Comment by JiaoPaner** [comment]
same error in wsl2
```bash
pip install montreal-forced-aligner
mfa version
```
```bash
from _kalpy.gmm import AccumAmDiagGmm
ModuleNotFoundError: No module named '_kalpy'
```

**Comment by bank010** [comment]
> WSL2 中的相同错误
> 
> ```shell
> pip install montreal-forced-aligner
> mfa version
> ```
> 
> ```shell
> from _kalpy.gmm import AccumAmDiagGmm
> ModuleNotFoundError: No module named '_kalpy'
> ```

您好，找到解决方法了嘛

**Comment by thomas-ferraz** [comment]
Hi, I'm finding this same problem on Mac and Linux in different versions. Have you found a solution? It's seems not possible to install MFA

**Comment by Gnilbren** [comment]
> Can you try running `conda update -c montreal-forced-aligner kalpy kaldi=*=cpu* --update-deps`? That will get the latest version that should be synced across all versions. From 3.0.5 onward, there is a `mfa_update` command you can run that will get the latest versions of everything, see: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#updating-montreal-forced-aligner

a simple 'mfa_update' command worked for me, luckily.... I was getting a very similar error as ghost was.  Mine was line 6, 4, 7, and 11, instead of the 5, 4, 7, 12 line errors.
