### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'construct_path'

### ISSUE THREAD

**Issue by Jon-Zbw** [MontrealCorpusTools/Montreal-Forced-Aligner#735]
**Debugging checklist**

[ ] Have you updated to latest MFA version? 
version==2.2.4
[ ] Have you tried rerunning the command with the `--clean` flag?
 yes 
 --single_speaker --clean -t "$temp_dir/$parent_dir_name/$dir_name"_temp -j 1

**Describe the issue**
run in docker,
**For Reproducing your issue**
Please fill out the following:
INFO     Generating final features...                                          
   0%                                  0/177,071  [ 0:00:01 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.                    
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7f6a551b50f0>>
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/mfa.py", line 97, in history_save_handler
    raise self.exception
  File "/env/bin/mfa", line 11, in <module>
    sys.exit(mfa_cli())
  File "/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/command_line/align.py", line 113, in align_corpus_cli
    aligner.align()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 411, in align
    self.setup()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 205, in setup
    self.load_corpus()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1227, in load_corpus
    self.generate_features()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 471, in generate_features
    self.generate_final_features()
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 389, in generate_final_features
    for _ in run_kaldi_function(FinalFeatureFunction, arguments, pbar.update):
  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/utils.py", line 753, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 1 encountered an error:
Traceback (most recent call last):

  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 85, in run
    yield from self._run()

  File "/env/lib/python3.10/site-packages/montreal_forced_aligner/corpus/features.py", line 591, in _run
    feats_scp_path = job.construct_path(self.data_directory, "feats", "scp")

AttributeError: 'NoneType' object has no attribute 'construct_path'
1. Corpus structure
   * What language is the corpus in?
   mandarin 
   * How many files/speakers?
    INFO   Found 1 speaker across 177071 files, average number of utterances per 
          speaker: 177071.0 
   * Are you using lab files or TextGrid files for input?
   use txt files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   yes!  Mandarin MFA dictionary v2.0.0a
   * If it's a custom dictionary, what is the phoneset?
   MFA 
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   yes ! Mandarin MFA acoustic model v2.0.0a
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[align.1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14036247/align.1.log)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [Ubuntu 20.04]
 - Any other details about the setup (Cloud, Docker, etc)
Docker
**Additional context**

**Comment by Jon-Zbw** [comment]
a lot of folders processed together, only some of them got this problem

**Comment by mmcauliffe** [comment]
You can try upgrading to 3.0.0 or 2.2.17, 2.2.4 is pretty old, feel free to reopen if this is still an issue in 3.0.0.
