### ISSUE TITLE
 INFO     montreal_forced_aligner.exceptions.KaldiProcessingError: KaldiProcessingError:    

### ISSUE THREAD

**Issue by nannu634** [MontrealCorpusTools/Montreal-Forced-Aligner#744]
**Debugging checklist**

[ ] Have you updated to the latest MFA version?
[ ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
montreal_forced_aligner.exceptions.KaldiProcessingError: KaldiProcessingError:

There were 1 job(s) with errors when running Kaldi binaries.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * language: English
   * 1 wav file and 1 speaker
   * lab files
2. Dictionary
   english_mfa
   
3. Acoustic model
   * english_mfa
  

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[align.1.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14237509/align.1.log)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 11
 - Any other details about the setup (Cloud, Docker, etc)

**Additional context**
This error only occurs for some files while other files are getting aligned
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:06 < 0:00:00 , ? it/s ]
 INFO     Performing first-pass alignment...
 INFO     Generating alignments...
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:01:19 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x0000025314794250>>
Traceback (most recent call last):
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\command_line\mfa.py", line 98, in history_save_handler
    raise self.exception
  File "C:\Users\DELL\miniconda3\envs\aligner\Scripts\mfa-script.py", line 9, in <module>
    sys.exit(mfa_cli())
             ^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\command_line\align.py", line 113, in align_corpus_cli
    aligner.align()
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\alignment\pretrained.py", line 413, in align
    super().align()
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\alignment\base.py", line 350, in align
    self.align_utterances()
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\alignment\mixins.py", line 436, in align_utterances
    for utterance, log_likelihood in run_kaldi_function(
  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\utils.py", line 757, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 1 encountered an error:
Traceback (most recent call last):

  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\abc.py", line 92, in run
    yield from self._run()

  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\alignment\multiprocessing.py", line 1003, in _run
    self.check_call(align_proc)

  File "C:\Users\DELL\miniconda3\envs\aligner\Lib\site-packages\montreal_forced_aligner\abc.py", line 119, in check_call
    raise KaldiProcessingError([self.log_path])

montreal_forced_aligner.exceptions.KaldiProcessingError: KaldiProcessingError:

There were 1 job(s) with errors when running Kaldi binaries.
See the log files below for more information.
C:\Users\DELL\Documents\MFA\input\alignment\log\align.1.log

**Comment by mmcauliffe** [comment]
You can retry running it with a higher beam `mfa align ... --beam 100` or something, but I would recommend aligning more files or if it's a single long file then breaking it up.  If you update MFA you'll get an explicit error that no files were aligned and to try increasing the beam or checking your transcript for the file.
