### ISSUE TITLE
[BUG] f"Transition model update: Overall {objf_impr/count} " -> ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by William-N-Havard** [MontrealCorpusTools/Montreal-Forced-Aligner#746]
**Debugging checklist**

[ X] Have you updated to latest MFA version?
[ X] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
When trying to validate or train an acoustic model, this error is raised:
```
INFO     Initialization complete!                  
 INFO     monophone - Iteration 1 of 40             
 INFO     Generating alignments...                  
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:01:00 < -:--:-- , ? it/s ]
 INFO     Accumulating statistics...                
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1  [ 0:00:02 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.                                             
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7fbd545f4cd0>>
Traceback (most recent call last):
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/command_line/mfa.py", line 107, in history_save_handler
    raise self.exception
  File "/home/whavard/.conda/envs/MFA/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
             ^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/click/core.py", line 1157, in __call__ 
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/command_line/validate.py", line 112, in validate_corpus_cli
    validator.validate()
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/validation/corpus_validator.py", line 512, in validate
    self.train()
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 523, in train
    trainer.train()
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 390, in train
    self.train_iteration()
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 363, in train_iteration
    self.acc_stats()
  File "/home/whavard/.conda/envs/MFA/lib/python3.11/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 319, in acc_stats
    f"Transition model update: Overall {objf_impr/count} "
                                        ~~~~~~~~~^~~~~~
ZeroDivisionError: float division by zero
```

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in?
Maurition Creole
   * How many files/speakers?
1 file and 1 speaker (but problem persists if the same file is duplicated to have 2 files / 2 speakers)
   * Are you using lab files or TextGrid files for input?
lab files

2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
No
   * If it's a custom dictionary, what is the phoneset?
IPA (same symbols as in the French dictionary

3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).
[my_corp.log](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/files/14260609/my_corp.log)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Linux
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] Debian GNU/Linux 11
 - Any other details about the setup (Cloud, Docker, etc) Conda env

**Comment by mmcauliffe** [comment]
Do you only have 2 files total?  Training requires many more files than 2.  If you have a really small number like that, I would recommend using a pretrained model from another similar language with a pronunciation dictionary using those phones (i.e., French in this case).

**Comment by mmcauliffe** [comment]
I'm going to close this for now, I've added a section to the troubleshooting about training on small datasets: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html#errors-training-on-small-corpora

**Comment by William-N-Havard** [comment]
Yes, I had only one very long file ... I'll try to find a workaround. Thanks!
