### ISSUE TITLE
centos install

### ISSUE THREAD

**Issue by yanyanxixi** [MontrealCorpusTools/Montreal-Forced-Aligner#76]
hi
can centos 7 install this code?
when i am install this job in centos7 ,i have a error:
build PKG-00.pkg
cant find this file
hope your replay,thanks a lot

**Comment by mmcauliffe** [comment]
Could you provide more context, like copy and pasting the commands you entered and what output was given from the terminal?

**Comment by yanyanxixi** [comment]
when i run :pyinstaller --clean -y \
--additional-hooks-dir=freezing/hooks \
--exclude-module tkinter \
--exclude-module matplotlib \
--exclude-module pytz \
--exclude-module sphinx \
--exclude-module numpy \
--exclude-module scipy \
 aligner/command_line/train_and_align.py


then the error log is 
40 INFO: PyInstaller: 3.4.dev0+6e5c70e06
40 INFO: Python: 3.6.5
41 INFO: Platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.5.1804-Core
41 INFO: wrote /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/train_and_align.spec
43 INFO: UPX is not available.
43 INFO: Removing temporary files and cleaning cache in /home/yan/.cache/pyinstaller
47 INFO: Extending PYTHONPATH with paths
['/home/yan/cyy/merlin/MTTS/tools/Montreal-Forced-Aligner-master',
 '/home/yan/cyy/merlin/MTTS/tools/Montreal-Forced-Aligner-master']
47 INFO: checking Analysis
47 INFO: Building Analysis because Analysis-00.toc is non existent
48 INFO: Initializing module dependency graph...
49 INFO: Initializing module graph hooks...
50 INFO: Analyzing base_library.zip ...
3049 INFO: running Analysis Analysis-00.toc
3056 INFO: Caching module hooks...
3059 INFO: Analyzing /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/aligner/command_line/train_and_align.py
3969 INFO: Processing pre-find module path hook   distutils
4356 INFO: Processing pre-safe import module hook   six.moves
10411 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
14679 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
15178 INFO: Processing pre-find module path hook   site
15178 INFO: site: retargeting to fake-dir '/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/fake-modules'
36619 INFO: Loading module hooks...
36619 INFO: Loading module hook "hook-IPython.py"...
36625 INFO: Excluding import 'PyQt5'
36631 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
36631 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
36631 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
36631 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
36631 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
36632 INFO: Excluding import 'matplotlib'
36638 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
36640 INFO: Excluding import 'PySide'
36645 INFO:   Removing import of PySide from module IPython.external.qt_loaders
36646 INFO: Excluding import 'PyQt4'
36651 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
36652 INFO: Excluding import 'gtk'
36660 INFO: Loading module hook "hook-PIL.Image.py"...
37059 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
37063 INFO: Excluding import 'tkinter'
37066 INFO: Import to be excluded not found: 'FixTk'
37066 INFO: Loading module hook "hook-PIL.py"...
37069 INFO: Excluding import 'PyQt5'
37072 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
37072 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
37073 INFO: Excluding import 'PySide'
37077 INFO:   Removing import of PySide from module PIL.ImageQt
37078 INFO: Import to be excluded not found: 'FixTk'
37078 INFO: Excluding import 'PyQt4'
37081 INFO:   Removing import of PyQt4 from module PIL.ImageQt
37082 INFO: Excluding import 'tkinter'
37085 INFO:   Removing import of tkinter from module PIL.ImageTk
37086 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
37164 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
37213 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
37364 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
37444 INFO: Loading module hook "hook-PyQt5.py"...
38387 INFO: Loading module hook "hook-certifi.py"...
38388 INFO: Loading module hook "hook-cryptography.py"...
38610 INFO: Loading module hook "hook-distutils.py"...
38611 INFO: Loading module hook "hook-docutils.py"...
40513 INFO: Loading module hook "hook-encodings.py"...
40574 INFO: Loading module hook "hook-jedi.py"...
40575 INFO: Loading module hook "hook-jinja2.py"...
40596 INFO: Loading module hook "hook-jsonschema.py"...
40597 INFO: Loading module hook "hook-lib2to3.py"...
40598 INFO: Loading module hook "hook-lxml.etree.py"...
40599 INFO: Loading module hook "hook-openpyxl.py"...
40601 INFO: Loading module hook "hook-pandas.py"...
41348 INFO: Loading module hook "hook-pkg_resources.py"...
41723 INFO: Processing pre-safe import module hook   win32com
41924 INFO: Loading module hook "hook-pycparser.py"...
42164 INFO: Loading module hook "hook-pydoc.py"...
42164 INFO: Loading module hook "hook-pygments.py"...
43601 INFO: Loading module hook "hook-pytest.py"...
44176 INFO: Loading module hook "hook-requests.py"...
44177 INFO: Loading module hook "hook-setuptools.py"...
44739 INFO: Loading module hook "hook-sqlalchemy.py"...
44885 INFO:   Found 4 sqlalchemy hidden imports
44886 WARNING: Hidden import "MySQLdb" not found!
44886 WARNING: Hidden import "psycopg2" not found!
45778 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
45789 INFO: Import to be excluded not found: 'sqlalchemy.testing'
45789 INFO: Loading module hook "hook-sqlite3.py"...
45844 INFO: Loading module hook "hook-sysconfig.py"...
45851 INFO: Loading module hook "hook-tables.py"...
45852 INFO: Loading module hook "hook-xml.dom.domreg.py"...
45852 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
45853 INFO: Loading module hook "hook-xml.py"...
45853 INFO: Loading module hook "hook-zmq.py"...
46977 INFO: Loading module hook "hook-aligner.py"...
47223 INFO: Loading module hook "hook-gevent.monkey.py"...
47309 INFO: Looking for ctypes DLLs
47395 WARNING: library user32 required via ctypes not found
48047 INFO: Analyzing run-time hooks ...
48075 INFO: Including run-time hook 'pyi_rth_traitlets.py'
48077 INFO: Including run-time hook 'pyi_rth_pkgres.py'
48078 INFO: Including run-time hook 'pyi_rth_qt5.py'
48080 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
48134 INFO: Looking for dynamic libraries
ldd: 警告: 你没有执行权限  `/home/yanyancao/anaconda3/plugins/platforms/../../lib/libgcc_s.so.1'
50688 INFO: Looking for eggs
50688 INFO: Using Python library /home/yan/anaconda3/lib/python3.6/site-packages/markupsafe/../../../libpython3.6m.so.1.0
50731 INFO: Warnings written to /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/build/train_and_align/warn-train_and_align.txt
50982 INFO: Graph cross-reference written to /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/build/train_and_align/xref-train_and_align.html
51066 INFO: checking PYZ
51066 INFO: Building PYZ because PYZ-00.toc is non existent
51066 INFO: Building PYZ (ZlibArchive) /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/build/train_and_align/PYZ-00.pyz
53898 INFO: Building PYZ (ZlibArchive) /home/yan/merlin/MTTS/tools/Montreal-Forced-Aligner-master/build/train_and_align/PYZ-00.pyz completed successfully.
53971 INFO: checking PKG
53971 INFO: Building PKG because PKG-00.toc is non existent
53971 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "/home/yan/anaconda3/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/yan/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "/home/yan/anaconda3/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType


thanks a lot!
