### ISSUE TITLE
[BUG] Error on Windows when validating or aligning

### ISSUE THREAD

**Issue by stefanocoretta** [MontrealCorpusTools/Montreal-Forced-Aligner#793]
**Debugging checklist**

[x] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there?
[x] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
When running `mfa validate` or `mfa align` we get this error

<details>
ERROR    There was an error in the run, please see the log.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\water\miniconda3\envs\aligner\Scripts\mfa-script.py", line 9, in <module>
    sys.exit(mfa_cli())
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\rich_click\rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\validate.py", line 137, in validate_corpus_cli
    validator.validate()
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\validation\corpus_validator.py", line 505, in validate
    self.setup()
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\validation\corpus_validator.py", line 485, in setup
    self.generate_features()
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 535, in generate_features
    self.generate_final_features()
  File "C:\Users\water\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\corpus\acoustic_corpus.py", line 482, in generate_final_features
    raise FeatureGenerationError(
montreal_forced_aligner.exceptions.FeatureGenerationError: FeatureGenerationError:

No utterances had features, please check the logs in C:\U 

</details>

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Swahili
   * How many files/speakers? 3
   * Are you using lab files or TextGrid files for input? lab files
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? swahili_mfa
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? swahili_mfa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version windows 10
 - Any other details about the setup (Cloud, Docker, etc): installed with mambda rather than conda

**Additional context**

**Comment by mmcauliffe** [comment]
Can you attach the log file in `~/Documents/MFA/{corpus_name}/{corpus_name}/split3/make_mfcc.1.log` or something similar?  I haven't updated the swahili_mfa model for 3.0 changes yet, but other models trained on 2.X are passing tests fine.

**Comment by stefanocoretta** [comment]
Alas, no. It was a student at a workshop I ran and I don't think I can get hold of the file. :(
