### ISSUE TITLE
[BUG] cannot execute mfa align

### ISSUE THREAD

**Issue by cc-willchang** [MontrealCorpusTools/Montreal-Forced-Aligner#801]
Hi all,

I have installed the montreal-forced-aligner via conda and prepared .wav sound filles as well as Texigrid. However, when I try to execute mfa align (or mfa validate) command, I always get the following error message:

```
(aligner) willchang@dhcp-10-8-038-178 desktop % mfa align ./force_aligner_try/ mandarin_china_mfa mandarin_mfa ./force_aligner_output/
 INFO     Setting up corpus information...                                                                                  
 ERROR    There was an error in the run, please see the log.                                                                
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/willchang/miniconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 360, in __call__
    return super().__call__(*args, **kwargs)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align.py", line 122, in align_corpus_cli
    aligner.align()
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 333, in align
    self.setup()
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 207, in setup
    self.load_corpus()
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1094, in load_corpus
    self._load_corpus()
  File "/Users/willchang/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/corpus/base.py", line 1594, in _load_corpus
    raise CorpusError(
montreal_forced_aligner.exceptions.CorpusError: CorpusError:

There were no sound files found of the appropriate format. Please double check the corpus path and/or run the validation utility (mfa validate).
```
 
I have tried to put the sound and Textgrid files onto my colleagues computer and there's no problem running there. I would appreciate it very much for any guidance to resolve the issue. 

I'm using a MacBook Air (M1, 2020) version 11.3.1.

Thanks much!

**Comment by cc-willchang** [comment]
I found simply change the folder name and re-run the commands again then it works!
