### ISSUE TITLE
[BUG]: MFA train on Portuguese Data

### ISSUE THREAD

**Issue by shreeshailgan** [MontrealCorpusTools/Montreal-Forced-Aligner#827]
**Describe the issue**
When running `mfa train` on Portuguese dataset, I am getting the following error
```
INFO     Generating MFCCs...                                                                                                                          
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39,230/39,230  [ 0:07:51 < 0:00:00 , 42 it/s ]
 INFO     Calculating CMVN...                                                                                                                          
 INFO     Generating final features...                                                                                                                 
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39,230/39,230  [ 0:00:08 < 0:00:00 , 4,500 it/s ]
 INFO     Creating corpus split...                                                                                                                     
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39,230/39,230  [ 0:00:01 < 0:00:00 , 29,505 it/s ]
 INFO     Filtering utterances for training...                                                                                                         
 INFO     Creating subset directory with 10000 utterances...                                                                                           
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10,000/10,000  [ 0:00:01 < 0:00:00 , 9,176 it/s ]
 INFO     Initializing training for monophone...                                                                                                       
 INFO     Compiling training graphs...                                                                                                                 
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7883ae238430>                                                                                 
Traceback (most recent call last):      
  File "/home/shreeshail/miniconda3/envs/mfa313/lib/python3.10/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__                             
    del self._compiler                  
AttributeError: _compiler               
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7883ae238430>                                                                                 
Traceback (most recent call last):      
  File "/home/shreeshail/miniconda3/envs/mfa313/lib/python3.10/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__                             
    del self._compiler                  
AttributeError: _compiler               
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7883ae238430>                                                                                 
Traceback (most recent call last):      
  File "/home/shreeshail/miniconda3/envs/mfa313/lib/python3.10/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__                             
    del self._compiler                  
AttributeError: _compiler               


...



montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:                                                                                   

Job 1 encountered an error:             
Traceback (most recent call last):      

  File "/home/shreeshail/miniconda3/envs/mfa313/lib/python3.10/site-packages/montreal_forced_aligner/abc.py", line 104, in run                                   
    self._run()                         

  File "/home/shreeshail/miniconda3/envs/mfa313/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 445, in _run
    compiler = TrainingGraphCompiler(                                           

TypeError: TrainingGraphCompiler.__init__() missing 1 required positional argument: 'words_symbols'
```

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   language: Portuguese (from Multilingual LibriSpeech)
   around 40k wavs / 60 speakers
   using label files
2. Dictionary
   I created my own dictionary using [phonemizer](https://pypi.org/project/phonemizer/)
   phoneset = espeak-ng IPA
3. Acoustic model
   Don't have an existing acoustic model. I am running `mfa train`

**Desktop**
 - OS: Linux: Ubuntu 22.04
 - MFA version: `montreal-forced-aligner   3.1.3              pyhd8ed1ab_0    conda-forge`

**Comment by shreeshailgan** [comment]
For now, I am able to work by shifting to version `3.0.6`

**Comment by mmcauliffe** [comment]
Should be fixed by https://github.com/conda-forge/montreal-forced-aligner-feedstock/pull/84, if you can run `conda update -c conda-forge montreal-forced-aligner` it should pick up the update to kalpy as well.
