### ISSUE TITLE
[BUG] mfa adapt does not save alignments

### ISSUE THREAD

**Issue by chirila** [MontrealCorpusTools/Montreal-Forced-Aligner#830]
**Debugging checklist**

[X ] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there?
[ X] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`? 3.1.2
[X ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

I'm adapting the Tamil_cv model to a corpus from Australian data.  Initial alignment works, but it looks like a file isn't saving, and I get the error below (final.alimdl not found)

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? (Various Australian Indigenous languages)
   * How many files/speakers? 53 speakers, 219 files (but same error with subsets of files)
   * Are you using lab files or TextGrid files for input? TextGrids
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? No, bespoke dictionary
   * If it's a custom dictionary, what is the phoneset? same as tamil_cv (validate worked with no errors, but the log says there are phones not in the dataset) 
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? tamil_cv
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

```
 INFO     Setting up corpus information...                                                                                                                                                                INFO     Loading corpus from source files...                                                                                                                                                             100% -------------------------------------------------------------------------------------------------------------------------------------------------------- 219/100  [ 0:00:00 < 0:00:00 , 169 it/s ]  INFO     Found 53 speakers across 219 files, average number of utterances per speaker: 1097.867924528302                                                                                                 INFO     Initializing multiprocessing jobs...                                                                                                                                                            INFO     Normalizing text...                                                                                                                                                                             100% ----------------------------------------------------------------------------------------------------------------------------------------------- 58,187/58,187  [ 0:00:04 < 0:00:00 , 14,455 it/s ]  INFO     Generating MFCCs...                                                                                                                                                                              98% ----------------------------------------------------------------------------------------------------------------------------------------------- -- 57,017/58,187  [ 0:02:55 < 0:00:07 , 184 it/s ]  INFO     Calculating CMVN...                                                                                                                                                                             INFO     Generating final features...                                                                                                                                                                     98% --------------------------------------------------------------------------------------------------------------------------------------------- -- 57,017/58,187  [ 0:00:20 < 0:00:01 , 2,857 it/s ]  WARNING  There were 1170 utterances ignored due to an issue in feature generation, see the log file for full details or run `mfa validate` on the corpus.                                                INFO     Creating corpus split...                                                                                                                                                                         98% -------------------------------------------------------------------------------------------------------------------------------------------- -- 57,017/58,187  [ 0:00:03 < 0:00:01 , 19,956 it/s ]  WARNING  There were 11702 pronunciations in the dictionary that were ignored for containing one of 30 phones not present in the trained acoustic model.  Please run `mfa validate` to get more details.  INFO     Compiling training graphs...                                                                                                                                                                    INFO     Performing first-pass alignment...                                                                                                                                                              INFO     Generating alignments...                                                                                                                                                                         91% ------------------------------------------------------------------------------------------------------------------------------------ ------------- 52,915/58,187  [ 0:01:55 < 0:00:30 , 180 it/s ]  ERROR    There was an error in the run, please see the log.                                                                                                                                             Error in atexit._run_exitfuncs:                                                                                                                                                                          Traceback (most recent call last):                                                                                                                                                                         File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\Scripts\mfa-script.py", line 9, in <module>                                                                                                      sys.exit(mfa_cli())                                                                                                                                                                                    File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1157, in __call__                                                                                         return self.main(*args, **kwargs)                                                                                                                                                                      File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\rich_click\rich_command.py", line 126, in main                                                                                 rv = self.invoke(ctx)                                                                                                                                                                                  File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1688, in invoke                                                                                           return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 1434, in invoke                                                                                           return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                         File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\click\core.py", line 783, in invoke                                                                                            return __callback(*args, **kwargs)                                                                                                                                                                     File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\click\decorators.py", line 33, in new_func                                                                                     return f(get_current_context(), *args, **kwargs)                                                                                                                                                       File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\command_line\adapt.py", line 101, in adapt_model_cli                                                   adapter.adapt()                                                                                                                                                                                        File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\site-packages\montreal_forced_aligner\alignment\adapting.py", line 208, in adapt                                                             shutil.copyfile(                                                                                                                                                                                       File "C:\Users\clb3\AppData\Local\miniconda3\envs\aligner\lib\shutil.py", line 264, in copyfile                                                                                                            with open(src, 'rb') as fsrc:                                                                                                                                                                        FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\clb3\\Documents\\MFA\\trainset\\alignment\\final.alimdl'   
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Windows
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] 10
 - Any other details about the setup (Cloud, Docker, etc) miniconda

**Additional context**

**Comment by ad-jones** [comment]
Hello! I just wanted to bump this bug post. I'm experiencing the same issue, and it seems the final.alimdl file is not being generated and saved to the alignment folder for the corpus. Within the MFA's files that are generated when working with a corpus, I see all other .mdl and .ark files that are made after alignment. I've tried the adapt command on version 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.7. All give the same error as shown in the original post referencing missing final.alimdl. I have also tested this on a MacBook pro and a Windows 11 machine. Any information on how to overcome this would be greatly appreciated for our research goals.

**Comment by MassimoDaul** [comment]
Hi all - I am experiencing the same issue, tested on MacOS with 3.1.2 and 3.1.3. If I run the adapt command on a folder called "~/Desktop/ex_corpus" I can find the final.alimdl in "~/Desktop/ex_corpus/alignment", which only exists when I navigate to it directly via command line, and does not exist in the original folder. Information regarding a version with a functioning adapt method, or a way to specify where to look for this missing file would enormously help our research project.

**Comment by turinaf** [comment]
`mfa train` not saving alignments for me, when I run using this command from [this tutorial](https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#first-steps-align-train-acoustic-model)

```
mfa train ~/mfa_data/my_corpus ~/mfa_data/my_dictionary.txt ~/mfa_data/new_acoustic_model.zip --output_directory ~/mfa_data/my_corpus_aligned  # Export both trained model and alignments
```
