### ISSUE TITLE
[BUG] Mandarin MFA not working

### ISSUE THREAD

**Issue by Gnilbren** [MontrealCorpusTools/Montreal-Forced-Aligner#849]
Hi, help please! 

I am trying to align a single file with align_one using the mandarin MFA acoustic pre trained model. Currently, I am using mfa align_one in order to accomplish my task and I am getting the following error:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/miniconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align_one.py", line 156, in align_one_cli
    tokenizer = generate_language_tokenizer(acoustic_model.meta["language"])
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/tokenization/spacy.py", line 66, in generate_language_tokenizer
    name = language_model_mapping[language]
KeyError: 'chinese'

I tried editing the JSON file to make the language key_key paired with the value "mandarin" instead of chinese and I could not fix the error and got the following error instead:

File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/miniconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return this.main(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align_one.py", line 184, in align_one_cli
    ctm = align_utterance_online(
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/online/alignment.py", line 78, in align_utterance_online
    graph_compiler = TrainingGraphCompiler(
TypeError: __init__() missing 1 required positional argument: 'words_symbols'

Any suggestions on further steps that I can try to resolve my issues?

**Comment by mmcauliffe** [comment]
Can you try the commands here: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#updating-montreal-forced-aligner, it looks like you might not be on the latest version of kalpy.

**Comment by Gnilbren** [comment]
Did that, and now I am getting new error:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/miniconda3/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align_one.py", line 184, in align_one_cli
    ctm = align_utterance_online(
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/online/alignment.py", line 78, in align_utterance_online
    graph_compiler = TrainingGraphCompiler(
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 75, in __init__
    ReadKaldiObject(str(model_path), self.transition_model)
RuntimeError: kaldi::KaldiFatalError
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x12342ec10>
Traceback (most recent call last):
  File "/Users/miniconda3/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 93, in __del__
AttributeError: _compiler

**Comment by Gnilbren** [comment]
Just trying to use this aligner for the mfa align_one command, that is it. Please help!
