### ISSUE TITLE
CTMInterval error and Alignment Export Error

### ISSUE THREAD

**Issue by aabdumalikov** [MontrealCorpusTools/Montreal-Forced-Aligner#851]
The following exceptions were encountered during the output of the alignments to TextGrids:

AlignmentExportError:

Error was encountered in exporting TextGrid/11992.TextGrid:

Traceback (most recent call last):

  File "/home/aziz/anaconda3/envs/mfa_env/lib/python3.10/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 1642, in run
    for output_path in construct_textgrid_output(

  File "/home/aziz/anaconda3/envs/mfa_env/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 419, in construct_textgrid_output
    export_textgrid(data, output_path, file_duration, frame_shift, output_format)

  File "/home/aziz/anaconda3/envs/mfa_env/lib/python3.10/site-packages/montreal_forced_aligner/textgrid.py", line 552, in export_textgrid
    tg_interval = a.to_tg_interval()

  File "/home/aziz/anaconda3/envs/mfa_env/lib/python3.10/site-packages/montreal_forced_aligner/data.py", line 2079, in to_tg_interval
    raise CtmError(self)

montreal_forced_aligner.exceptions.CtmError: CtmError:

Error was encountered in processing CTM interval: CtmInterval(begin=5.26, end=2.611995, label='tushadi', confidence=None)

**Comment by CriDora** [comment]
Hello, I have the same problem as you, have you solved it?

**Comment by aabdumalikov** [comment]
> Hello, I have the same problem as you, have you solved it?

Not yet

**Comment by aabdumalikov** [comment]
[input_data.zip](https://github.com/user-attachments/files/17990790/input_data.zip)

The following exceptions were encountered during the output of the alignments to TextGrids:

AlignmentExportError:

Error was encountered in exporting TextGrid\8f9f3893-4b06-415a-a317-a0e77b28269c.TextGrid:


Traceback (most recent call last):

  File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\alignment\multiprocessing.py", line 1642, in run
    for output_path in construct_textgrid_output(

  File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\textgrid.py", line 419, in construct_textgrid_output
    export_textgrid(data, output_path, file_duration, frame_shift, output_format)

  File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\textgrid.py", line 552, in export_textgrid
    tg_interval = a.to_tg_interval()

  File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\data.py", line 2079, in to_tg_interval
    raise CtmError(self)

montreal_forced_aligner.exceptions.CtmError: CtmError:

Error was encountered in processing CTM interval: CtmInterval(begin=8.29, end=2.575011, label='etdilar', confidence=None)

**Comment by aabdumalikov** [comment]
> To help me reproduce this locally, is it possible to share the input date for the file that's throwing this (11992)? What acoustic model/dictionary are you using?

[input_data.zip](https://github.com/user-attachments/files/17990825/input_data.zip)



The following exceptions were encountered during the output of the alignments to TextGrids:

AlignmentExportError:

Error was encountered in exporting TextGrid\8f9f3893-4b06-415a-a317-a0e77b28269c.TextGrid:

Traceback (most recent call last):

File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\alignment\multiprocessing.py", line 1642, in run
for output_path in construct_textgrid_output(

File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\textgrid.py", line 419, in construct_textgrid_output
export_textgrid(data, output_path, file_duration, frame_shift, output_format)

File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\textgrid.py", line 552, in export_textgrid
tg_interval = a.to_tg_interval()

File "C:\Users\aisha\ansel\envs\mfa_env\lib\site-packages\montreal_forced_aligner\data.py", line 2079, in to_tg_interval
raise CtmError(self)

montreal_forced_aligner.exceptions.CtmError: CtmError:

Error was encountered in processing CTM interval: CtmInterval(begin=8.29, end=2.575011, label='etdilar', confidence=None)

**Comment by William-N-Havard** [comment]
Same mistake here!

**Comment by aabdumalikov** [comment]
Is theere any update? Thank you in advance! @mmcauliffe
