### ISSUE TITLE
[BUG] mfa train_g2p crash

### ISSUE THREAD

**Issue by lifeiteng** [MontrealCorpusTools/Montreal-Forced-Aligner#852]
```
mfa train_g2p --evaluate exp/g2p_english_us_mfa/english_us_mfa.txt exp/g2p_english_us_mfa/english_us_mfa_Pynini.zip

 INFO     Training aligner                                                                                                                                 
 INFO     Calculating alignments...                                                                                                                        
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/250  [ 0:00:01 < -:--:-- , ? it/s ]
 ERROR    There was an error in the run, please see the log.                                                                                               
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7793955e5c60>>
Traceback (most recent call last):
  File "/home/lifeiteng/code/MontrealCorpusTools/Montreal-Forced-Aligner/montreal_forced_aligner/command_line/mfa.py", line 110, in history_save_handler
    raise self.exception
  File "/home/lifeiteng/.local/bin/mfa", line 8, in <module>
    sys.exit(mfa_cli())
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lifeiteng/code/MontrealCorpusTools/Montreal-Forced-Aligner/montreal_forced_aligner/command_line/train_g2p.py", line 78, in train_g2p_cli
    trainer.train()
  File "/home/lifeiteng/code/MontrealCorpusTools/Montreal-Forced-Aligner/montreal_forced_aligner/g2p/trainer.py", line 859, in train
    self.align_g2p()
  File "/home/lifeiteng/code/MontrealCorpusTools/Montreal-Forced-Aligner/montreal_forced_aligner/g2p/trainer.py", line 457, in align_g2p
    self._alignments()
  File "/home/lifeiteng/code/MontrealCorpusTools/Montreal-Forced-Aligner/montreal_forced_aligner/g2p/trainer.py", line 607, in _alignments
    raise PyniniAlignmentError(error_dict)
montreal_forced_aligner.exceptions.PyniniAlignmentError: <exception str() failed>
```

**Comment by lifeiteng** [comment]
figure it out.
