### ISSUE TITLE
TextGrid import error after building from source

### ISSUE THREAD

**Issue by sirifarif** [MontrealCorpusTools/Montreal-Forced-Aligner#9]
Hi, 
After following the steps for __building from source__. I got the following error, when try to execute __mfa_align__. 

```
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 34, in <module>
    from aligner.corpus import Corpus
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "aligner/__init__.py", line 10, in <module>
    import aligner.aligner as aligner
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "aligner/aligner/__init__.py", line 2, in <module>
    from .trainable import TrainableAligner
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "aligner/aligner/trainable.py", line 10, in <module>
    from ..multiprocessing import (align, mono_align_equal, compile_train_graphs,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "aligner/multiprocessing.py", line 8, in <module>
    from .textgrid import ctm_to_textgrid, parse_ctm
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "aligner/textgrid.py", line 5, in <module>
    from textgrid import TextGrid, IntervalTier
ImportError: cannot import name TextGrid
Failed to execute script align
```

I have installed all the pre-requisite in the __requirements.txt__ file and also checked that __import textgrid__ works in some other python script.

**Comment by sirifarif** [comment]
I was not using pip3, after changing to pip3 it worked.

**Comment by mmcauliffe** [comment]
Glad you got it working!
